Repository woowacourse-teams/2023-fun-eat, pull requests merged in 2023-11, with the labels that each got.

#839 [FE] feat: 리뷰, 꿀조합 좋아요에 낙관적 업데이트 적용
  frontend/src/components/Recipe/RecipeFavorite/RecipeFavorite.tsx
  frontend/src/components/Recipe/RecipeFavoriteButton/RecipeFavoriteButton.tsx
  frontend/src/components/Recipe/index.ts
  frontend/src/components/Review/ReviewFavoriteButton/ReviewFavoriteButton.tsx
  frontend/src/components/Review/ReviewItem/ReviewItem.tsx
  frontend/src/components/Review/index.ts
  frontend/src/hooks/queries/recipe/useRecipeFavoriteMutation.ts
  frontend/src/hooks/queries/review/useReviewFavoriteMutation.ts
  frontend/src/pages/RecipeDetailPage.tsx
Labels: 🔑 FE, ✨ Feature

#841 [FE] refactor: 디자인 시스템 컴포넌트로 교체
  frontend/package.json
  frontend/src/components/Common/Carousel/Carousel.stories.tsx
  frontend/src/components/Common/Carousel/Carousel.tsx
  frontend/src/components/Common/ImageUploader/ImageUploader.tsx
  frontend/src/components/Common/Input/Input.stories.tsx
  frontend/src/components/Common/Input/Input.tsx
  frontend/src/components/Common/Skeleton/Skeleton.stories.tsx
  frontend/src/components/Common/Skeleton/Skeleton.tsx
  frontend/src/components/Common/Toast/Toast.stories.tsx
  frontend/src/components/Common/Toast/Toast.tsx
  frontend/src/components/Common/index.ts
  frontend/src/components/Members/MemberModifyInput/MemberModifyInput.tsx
  frontend/src/components/Members/MemberReviewItem/MemberReviewItem.stories.tsx
  frontend/src/components/Members/MemberReviewItem/MemberReviewItem.tsx
  frontend/src/components/Product/ProductItem/ProductItem.tsx
  frontend/src/components/Rank/RecipeRankingItem/RecipeRankingItem.tsx
  frontend/src/components/Rank/RecipeRankingList/RecipeRankingList.tsx
  frontend/src/components/Recipe/CommentForm/CommentForm.tsx
  frontend/src/components/Recipe/RecipeItem/RecipeItem.tsx
  frontend/src/components/Recipe/RecipeNameInput/RecipeNameInput.tsx
  frontend/src/components/Recipe/RecipeRegisterForm/RecipeRegisterForm.tsx
  frontend/src/components/Recipe/RecipeUsedProducts/RecipeUsedProducts.tsx
  frontend/src/components/Review/ReviewRegisterForm/ReviewRegisterForm.tsx
  frontend/src/contexts/ToastContext.tsx
  frontend/src/hooks/common/index.ts
  frontend/src/hooks/common/useImageUploader.ts
  frontend/src/hooks/common/useToast.ts
  frontend/src/hooks/context/index.ts
  frontend/src/hooks/context/useToastActionContext.ts
  frontend/src/hooks/context/useToastValueContext.ts
  frontend/src/hooks/queries/members/useLogoutMutation.ts
  frontend/src/hooks/search/useSearch.ts
  frontend/src/index.tsx
  frontend/src/pages/IntegratedSearchPage.tsx
  frontend/src/pages/MemberModifyPage.tsx
  frontend/src/pages/SearchPage.tsx
  frontend/yarn.lock
Labels: 🔑 FE, 🔧 Refactor

#847 [FE] fix: 디자인 시스템 업데이트 에러
  frontend/src/hooks/queries/recipe/useRecipeFavoriteMutation.ts
  frontend/src/hooks/queries/review/useReviewFavoriteMutation.ts
Labels: 🔑 FE, 🐛 Bug
