Repository woowacourse-teams/2023-fun-eat, pull requests merged in 2023-07, with the labels that each got.

#11 [BE] feat: 전체 엔티티 설계 및 구현
  backend/src/main/java/com/funeat/category/domain/Category.java
  backend/src/main/java/com/funeat/category/domain/CategoryType.java
  backend/src/main/java/com/funeat/member/domain/Gender.java
  backend/src/main/java/com/funeat/member/domain/Member.java
  backend/src/main/java/com/funeat/member/domain/bookmark/ProductBookmark.java
  backend/src/main/java/com/funeat/member/domain/bookmark/RecipeBookmark.java
  backend/src/main/java/com/funeat/member/domain/favorite/RecipeFavorite.java
  backend/src/main/java/com/funeat/member/domain/favorite/ReviewFavorite.java
  backend/src/main/java/com/funeat/product/domain/Product.java
  backend/src/main/java/com/funeat/product/domain/ProductRecipe.java
  backend/src/main/java/com/funeat/recipe/domain/Recipe.java
  backend/src/main/java/com/funeat/recipe/domain/RecipeImage.java
  backend/src/main/java/com/funeat/review/domain/Review.java
  backend/src/main/java/com/funeat/review/domain/ReviewTag.java
  backend/src/main/java/com/funeat/tag/domain/Tag.java
Labels: 🔒 BE, ✨ Feature

#18 [FE] chore: storybook 설치 및 웹팩 설정 추가
  frontend/.babelrc.json
  frontend/.eslintrc.js
  frontend/.storybook/main.ts
  frontend/.storybook/preview.ts
  frontend/package.json
  frontend/yarn.lock
Labels: 🔑 FE, ⚙️ Chore

#19 [FE] chore: msw 설정
  frontend/.storybook/preview.ts
  frontend/package.json
  frontend/public/mockServiceWorker.js
  frontend/src/index.tsx
  frontend/src/mocks/.gitkeep
  frontend/src/mocks/browser.ts
  frontend/src/mocks/handlers.ts
  frontend/tsconfig.json
  frontend/yarn.lock
Labels: 🔑 FE, ⚙️ Chore

#21 [BE] test: 인수테스트에 대한 템플릿 작성
  backend/build.gradle
  backend/src/main/java/com/funeat/product/domain/Category.java
  backend/src/main/java/com/funeat/product/domain/CategoryType.java
  backend/src/main/java/com/funeat/product/domain/Product.java
  backend/src/main/java/com/funeat/product/domain/SortOrderType.java
  backend/src/main/java/com/funeat/product/domain/SortType.java
  backend/src/main/java/com/funeat/product/persistence/CategoryRepository.java
  backend/src/main/java/com/funeat/product/persistence/ProductRepository.java
  backend/src/main/java/com/funeat/product/presentation/CategoryProductResponse.java
  backend/src/main/java/com/funeat/product/presentation/CategoryResponse.java
  backend/src/main/java/com/funeat/product/presentation/ProductResponse.java
  backend/src/main/java/com/funeat/tag/domain/Tag.java
  backend/src/main/java/com/funeat/tag/domain/TagDto.java
  backend/src/test/java/com/funeat/acceptance/common/AcceptanceTest.java
  backend/src/test/java/com/funeat/acceptance/common/CommonSteps.java
  backend/src/test/java/com/funeat/acceptance/product/ProductAcceptanceTest.java
  backend/src/test/java/com/funeat/acceptance/product/ProductSteps.java
  backend/src/test/resources/application.properties
Labels: 🔒 BE, 💻 Test

#37 [FE] chore: 디자인 시스템 설치 및 적용
  frontend/package.json
  frontend/src/index.tsx
  frontend/yarn.lock
Labels: 🔑 FE, ⚙️ Chore

#35 [FE] chore: import 순서 lint 적용
  frontend/.babelrc.json
  frontend/.eslintrc.js
  frontend/package.json
  frontend/src/index.tsx
  frontend/src/mocks/browser.ts
  frontend/src/types/index.ts
  frontend/yarn.lock
Labels: 🔑 FE, ⚙️ Chore

#39 [FE] SvgSprite, SvgIcon 컴포넌트 추가
  frontend/.eslintrc.js
  frontend/.storybook/preview-body.html
  frontend/.storybook/preview.ts
  frontend/package.json
  frontend/src/components/.gitkeep
  frontend/src/components/Common/Svg/SvgIcon.stories.tsx
  frontend/src/components/Common/Svg/SvgIcon.tsx
  frontend/src/components/Common/Svg/SvgSprite.tsx
  frontend/src/components/Common/index.ts
  frontend/src/index.tsx
  frontend/src/types/index.ts
  frontend/yarn.lock
Labels: 🔑 FE, ✨ Feature, 🎨 UI

#25 [BE] feat: 카테고리 목록 조회 기능 추가
  backend/src/main/java/com/funeat/common/StringToCategoryTypeConverter.java
  backend/src/main/java/com/funeat/common/WebConfig.java
  backend/src/main/java/com/funeat/product/application/CategoryService.java
  backend/src/main/java/com/funeat/product/persistence/CategoryRepository.java
  backend/src/main/java/com/funeat/product/presentation/CategoryController.java
  backend/src/test/java/com/funeat/acceptance/common/AcceptanceTest.java
  backend/src/test/java/com/funeat/acceptance/product/ProductAcceptanceTest.java
  backend/src/test/java/com/funeat/acceptance/product/ProductSteps.java
  backend/src/test/java/com/funeat/product/persistence/CategoryRepositoryTest.java
Labels: 🔒 BE, ✨ Feature

#24 [BE] feat: 리뷰 작성 기능 구현
  backend/src/main/java/com/funeat/config/EnvProperties.java
  backend/src/main/java/com/funeat/member/domain/Member.java
  backend/src/main/java/com/funeat/member/persistence/MemberRepository.java
  backend/src/main/java/com/funeat/member/persistence/ProductBookmarkRepository.java
  backend/src/main/java/com/funeat/member/persistence/RecipeBookMarkRepository.java
  backend/src/main/java/com/funeat/member/persistence/RecipeFavoriteRepository.java
  backend/src/main/java/com/funeat/member/persistence/ReviewFavoriteRepository.java
  backend/src/main/java/com/funeat/product/persistence/CategoryRepository.java
  backend/src/main/java/com/funeat/product/persistence/ProductRecipeRepository.java
  backend/src/main/java/com/funeat/product/persistence/ProductRepository.java
  backend/src/main/java/com/funeat/recipe/persistence/RecipeImageRepository.java
  backend/src/main/java/com/funeat/recipe/persistence/RecipeRepository.java
  backend/src/main/java/com/funeat/review/application/ImageService.java
  backend/src/main/java/com/funeat/review/application/ImageUploader.java
  backend/src/main/java/com/funeat/review/application/ReviewService.java
  backend/src/main/java/com/funeat/review/domain/Review.java
  backend/src/main/java/com/funeat/review/domain/ReviewTag.java
  backend/src/main/java/com/funeat/review/persistence/ReviewRepository.java
  backend/src/main/java/com/funeat/review/persistence/ReviewTagRepository.java
  backend/src/main/java/com/funeat/review/presentation/ReviewController.java
  backend/src/main/java/com/funeat/review/presentation/dto/ReviewCreateRequest.java
  backend/src/main/java/com/funeat/tag/domain/Tag.java
  backend/src/main/java/com/funeat/tag/persistence/TagRepository.java
  backend/src/main/resources/properties/env.properties
  backend/src/test/java/com/funeat/acceptance/review/ReviewAcceptanceTest.java
  backend/src/test/java/com/funeat/review/application/ReviewServiceTest.java
  backend/src/test/java/com/funeat/review/application/TestImageUploader.java
  backend/src/test/java/com/funeat/tag/persistence/TagRepositoryTest.java
  backend/src/test/resources/application.properties
Labels: 🔒 BE, ✨ Feature

#44 [FE] feat: RankingProductItem, RankingProductList 컴포넌트 추가
  frontend/.storybook/preview.tsx
  frontend/src/components/RankingProductItem/RankingProductItem.stories.tsx
  frontend/src/components/RankingProductItem/RankingProductItem.tsx
  frontend/src/components/RankingProductList/RankingProductList.stories.tsx
  frontend/src/components/RankingProductList/RankingProductList.tsx
  frontend/src/constants/.gitkeep
  frontend/src/mocks/data/rankingProducts.json
  frontend/src/types/.gitkeep
  frontend/src/types/Ranking.ts
  frontend/src/types/index.ts
  frontend/src/types/ranking.ts
  frontend/tsconfig.json
Labels: 🔑 FE, ✨ Feature

#40 [BE] feat: 특정 상품의 리뷰 목록 조회 기능 추가
  backend/src/main/java/com/funeat/member/domain/Member.java
  backend/src/main/java/com/funeat/member/domain/favorite/ReviewFavorite.java
  backend/src/main/java/com/funeat/review/application/ReviewService.java
  backend/src/main/java/com/funeat/review/domain/Review.java
  backend/src/main/java/com/funeat/review/domain/ReviewTag.java
  backend/src/main/java/com/funeat/review/persistence/ReviewRepository.java
  backend/src/main/java/com/funeat/review/presentation/ReviewController.java
  backend/src/main/java/com/funeat/review/presentation/dto/SortingReviewDto.java
  backend/src/main/java/com/funeat/review/presentation/dto/SortingReviewsPageDto.java
  backend/src/main/java/com/funeat/review/presentation/dto/SortingReviewsResponse.java
  backend/src/test/java/com/funeat/acceptance/common/AcceptanceTest.java
  backend/src/test/java/com/funeat/acceptance/review/ReviewAcceptanceTest.java
  backend/src/test/java/com/funeat/review/application/ReviewServiceTest.java
Labels: 🔒 BE, ✨ Feature

#46 [BE] feat: 특정 상품의 리뷰 좋아요, 좋아요 취소 기능 추가
  backend/src/main/java/com/funeat/member/domain/Member.java
  backend/src/main/java/com/funeat/member/domain/favorite/ReviewFavorite.java
  backend/src/main/java/com/funeat/member/persistence/ReviewFavoriteRepository.java
  backend/src/main/java/com/funeat/review/application/ReviewService.java
  backend/src/main/java/com/funeat/review/domain/Review.java
  backend/src/main/java/com/funeat/review/presentation/ReviewController.java
  backend/src/main/java/com/funeat/review/presentation/dto/ReviewFavoriteRequest.java
  backend/src/test/java/com/funeat/acceptance/common/CommonSteps.java
  backend/src/test/java/com/funeat/acceptance/review/ReviewAcceptanceTest.java
  backend/src/test/java/com/funeat/member/persistence/ReviewFavoriteRepositoryTest.java
  backend/src/test/java/com/funeat/review/application/ReviewServiceTest.java
Labels: 🔒 BE, ✨ Feature

#52 [FE] chore: 절대경로를 '@'에서 '@/'로 변경
  frontend/src/index.tsx
  frontend/tsconfig.json
  frontend/webpack.common.js
Labels: 🔑 FE, ⚙️ Chore

#47 [BE] feat: 좋아요 수를 기준으로 리뷰 랭킹 조회 기능 추가
  backend/src/main/java/com/funeat/review/application/ReviewService.java
  backend/src/main/java/com/funeat/review/persistence/ReviewRepository.java
  backend/src/main/java/com/funeat/review/presentation/ReviewController.java
  backend/src/main/java/com/funeat/review/presentation/dto/RankingReviewDto.java
  backend/src/main/java/com/funeat/review/presentation/dto/RankingReviewsResponse.java
  backend/src/test/java/com/funeat/acceptance/common/AcceptanceTest.java
  backend/src/test/java/com/funeat/acceptance/review/ReviewAcceptanceTest.java
  backend/src/test/java/com/funeat/review/persistence/ReviewRepositoryTest.java
Labels: 🔒 BE, ✨ Feature

#43 [FE] feat: ProductItem, ProductList 컴포넌트 추가
  frontend/.babelrc.json
  frontend/package.json
  frontend/src/components/Product/ProductItem/ProductItem.stories.tsx
  frontend/src/components/Product/ProductItem/ProductItem.tsx
  frontend/src/components/Product/ProductList/ProductList.stories.tsx
  frontend/src/components/Product/ProductList/ProductList.tsx
  frontend/src/components/RankingProductItem/RankingProductItem.stories.tsx
  frontend/src/components/RankingProductItem/RankingProductItem.tsx
  frontend/src/components/RankingProductList/RankingProductList.stories.tsx
  frontend/src/components/RankingProductList/RankingProductList.tsx
  frontend/src/mocks/data/products.json
  frontend/src/types/Ranking.ts
  frontend/src/types/images.d.ts
  frontend/src/types/product.ts
  frontend/src/types/styled.d.ts
  frontend/yarn.lock
Labels: 🔑 FE, ✨ Feature, 🎨 UI

#51 [BE] feat: 카테고리별 상품 목록 조회 기능 추가
  backend/src/main/java/com/funeat/common/GrobalControllerAdvice.java
  backend/src/main/java/com/funeat/member/domain/Member.java
  backend/src/main/java/com/funeat/product/application/ProductService.java
  backend/src/main/java/com/funeat/product/domain/SortOrderType.java
  backend/src/main/java/com/funeat/product/domain/SortType.java
  backend/src/main/java/com/funeat/product/dto/CategoryResponse.java
  backend/src/main/java/com/funeat/product/dto/ProductInCategoryDto.java
  backend/src/main/java/com/funeat/product/dto/ProductResponse.java
  backend/src/main/java/com/funeat/product/dto/ProductsInCategoryPageDto.java
  backend/src/main/java/com/funeat/product/dto/ProductsInCategoryResponse.java
  backend/src/main/java/com/funeat/product/persistence/ProductRepository.java
  backend/src/main/java/com/funeat/product/presentation/CategoryController.java
  backend/src/main/java/com/funeat/product/presentation/ProductController.java
  backend/src/main/java/com/funeat/review/application/ReviewService.java
  backend/src/main/java/com/funeat/review/persistence/ReviewRepository.java
  backend/src/main/java/com/funeat/review/presentation/ReviewController.java
  backend/src/test/java/com/funeat/acceptance/common/AcceptanceTest.java
  backend/src/test/java/com/funeat/acceptance/product/ProductAcceptanceTest.java
  backend/src/test/java/com/funeat/acceptance/product/ProductSteps.java
  backend/src/test/java/com/funeat/common/DataCleaner.java
  backend/src/test/java/com/funeat/common/DataClearExtension.java
  backend/src/test/java/com/funeat/product/persistence/CategoryRepositoryTest.java
  backend/src/test/java/com/funeat/product/persistence/ProductRepositoryTest.java
  backend/src/test/java/com/funeat/review/TestImageUploader.java
  backend/src/test/java/com/funeat/review/persistence/ReviewRepositoryTest.java
  backend/src/test/resources/application.properties
Labels: 🔒 BE, ✨ Feature

#48 [FE] feat: Bottom Sheet Content 컴포넌트 추가
  frontend/src/components/Common/BottomSheetContent/BottomSheetContent.stories.tsx
  frontend/src/components/Common/BottomSheetContent/BottomSheetContent.tsx
  frontend/src/constants/index.ts
Labels: 🔑 FE, ✨ Feature, 🎨 UI

#57 [BE] feat: 특정 상품에 대한 상세 정보 조회 기능 추가
  backend/src/main/java/com/funeat/member/domain/Member.java
  backend/src/main/java/com/funeat/product/application/ProductService.java
  backend/src/main/java/com/funeat/product/dto/ProductResponse.java
  backend/src/main/java/com/funeat/product/presentation/ProductController.java
  backend/src/main/java/com/funeat/review/persistence/ReviewTagRepository.java
  backend/src/test/java/com/funeat/acceptance/product/ProductAcceptanceTest.java
  backend/src/test/java/com/funeat/acceptance/review/ReviewAcceptanceTest.java
  backend/src/test/java/com/funeat/acceptance/review/ReviewSteps.java
  backend/src/test/java/com/funeat/review/TestImageUploader.java
  backend/src/test/java/com/funeat/review/persistence/ReviewRepositoryTest.java
  backend/src/test/java/com/funeat/review/persistence/ReviewTagRepositoryTest.java
Labels: 🔒 BE, ✨ Feature

#50 [FE] feat: SortButton 컴포넌트 추가
  frontend/.storybook/preview-body.html
  frontend/src/components/Common/SortButton/SortButton.stories.tsx
  frontend/src/components/Common/SortButton/SortButton.tsx
  frontend/src/components/Common/SortOptionList/SortOptionList.stories.tsx
  frontend/src/components/Common/SortOptionList/SortOptionList.tsx
  frontend/src/components/Common/Svg/SvgIcon.tsx
  frontend/src/components/Common/Svg/SvgSprite.tsx
  frontend/src/constants/index.ts
  frontend/src/hooks/useBottomSheet.ts
  frontend/src/types/common.ts
Labels: 🔑 FE, ✨ Feature, 🎨 UI

#53 [FE] feat: 리뷰 랭킹 아이템, 리뷰 랭킹 리스트 컴포넌트 추가
  frontend/src/components/RankingProductItem/RankingProductItem.tsx
  frontend/src/components/Review/ReviewRankingItem/ReviewRankingItem.stories.tsx
  frontend/src/components/Review/ReviewRankingItem/ReviewRankingItem.tsx
  frontend/src/components/Review/ReviewRankingList/ReviewRankingList.stories.tsx
  frontend/src/components/Review/ReviewRankingList/ReviewRankingList.tsx
  frontend/src/components/Review/index.ts
  frontend/src/mocks/data/rankingReviewList.json
  frontend/src/types/ranking.ts
Labels: 🔑 FE, ✨ Feature, 🎨 UI

#54 [FE] feat: NavigationBar 컴포넌트 추가
  frontend/.storybook/preview-body.html
  frontend/package.json
  frontend/src/components/Common/NavigationBar/NavigationBar.stories.tsx
  frontend/src/components/Common/NavigationBar/NavigationBar.tsx
  frontend/src/components/Common/Svg/SvgIcon.tsx
  frontend/src/components/Common/Svg/SvgSprite.tsx
  frontend/src/constants/index.ts
  frontend/src/types/common.ts
  frontend/yarn.lock
Labels: 🔑 FE, 🎨 UI

#56 [FE] feat: ProductDetail, TagList 컴포넌트 추가
  frontend/src/components/Common/TagList/TagList.stories.tsx
  frontend/src/components/Common/TagList/TagList.tsx
  frontend/src/components/Product/ProductDetail/ProductDetail.stories.tsx
  frontend/src/components/Product/ProductDetail/ProductDetail.tsx
  frontend/src/mocks/data/productDetail.json
  frontend/src/types/common.ts
  frontend/src/types/product.ts
Labels: 🔑 FE, ✨ Feature, 🎨 UI

#73 [FE] refactor: RankingProduct -> ProductRanking 으로 변경
  frontend/src/components/Common/BottomSheetContent/BottomSheetContent.stories.tsx
  frontend/src/components/Common/BottomSheetContent/BottomSheetContent.tsx
  frontend/src/components/ProductRankingItem/ProductRankingItem.stories.tsx
  frontend/src/components/ProductRankingItem/ProductRankingItem.tsx
  frontend/src/components/ProductRankingList/ProductRankingList.stories.tsx
  frontend/src/components/ProductRankingList/ProductRankingList.tsx
  frontend/src/components/RankingProductList/RankingProductList.stories.tsx
  frontend/src/components/RankingProductList/RankingProductList.tsx
  frontend/src/components/Review/ReviewRankingList/ReviewRankingList.tsx
  frontend/src/mocks/data/productRanking.json
  frontend/src/mocks/data/reviewRankingList.json
  frontend/src/types/ranking.ts
Labels: 🔑 FE, 🔧 Refactor

#80 [FE] fix: SortOptionList 스토리 prop 타입 에러 수정
  frontend/src/components/Common/SortOptionList/SortOptionList.stories.tsx
Labels: 🔑 FE, 🐛 Bug

#81 [BE] chore: application.yml 환경마다 분리
  backend/src/main/java/com/funeat/config/EnvProperties.java
  backend/src/main/resources/application-dev.yml
  backend/src/main/resources/application-local.yml
  backend/src/main/resources/application-prod.yml
  backend/src/main/resources/application.properties
  backend/src/main/resources/application.yml
  backend/src/main/resources/properties/env.properties
  backend/src/test/resources/application.properties
  backend/src/test/resources/application.yml
Labels: 🔒 BE, ⚙️ Chore

#88 [BE] fix: datasource url 수정으로 테스트 통과 수정
  backend/src/test/resources/application.yml
Labels: 🔒 BE, 🐛 Bug

#90 [BE] refactor: 리뷰 관련 이슈 제외 코드 리팩터링
  backend/src/main/java/com/funeat/common/GrobalControllerAdvice.java
  backend/src/main/java/com/funeat/product/application/ProductService.java
  backend/src/main/java/com/funeat/product/dto/ProductsInCategoryPageDto.java
  backend/src/main/java/com/funeat/product/dto/ProductsInCategoryResponse.java
  backend/src/main/java/com/funeat/product/presentation/ProductController.java
  backend/src/test/java/com/funeat/acceptance/common/CommonSteps.java
  backend/src/test/java/com/funeat/common/DataClearExtension.java
  backend/src/test/java/com/funeat/product/persistence/CategoryRepositoryTest.java
  backend/src/test/java/com/funeat/product/persistence/ProductRepositoryTest.java
  backend/src/test/java/com/funeat/tag/persistence/TagRepositoryTest.java
Labels: 🔒 BE, 🔧 Refactor

#74 [FE] feat: TabMenu 컴포넌트 추가
  frontend/src/components/Common/TabMenu/TabMenu.stories.tsx
  frontend/src/components/Common/TabMenu/TabMenu.tsx
Labels: 🔑 FE, ✨ Feature, 🎨 UI

#86 [FE] feat: Header 컴포넌트 추가
  frontend/.storybook/main.ts
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/assets/.gitkeep
  frontend/src/assets/logo.svg
  frontend/src/components/Common/Header/Header.stories.tsx
  frontend/src/components/Common/Header/Header.tsx
  frontend/src/components/Common/index.ts
  frontend/src/types/images.d.ts
  frontend/webpack.common.js
  frontend/yarn.lock
Labels: ✨ Feature, 🎨 UI

#92 [FE] feat: 공통 레이아웃 컴포넌트 추가
  frontend/src/App.tsx
  frontend/src/components/Common/Layout/Layout.tsx
  frontend/src/components/Common/NavigationBar/NavigationBar.tsx
  frontend/src/components/Common/index.ts
  frontend/src/index.tsx
  frontend/src/styles/.gitkeep
  frontend/src/styles/index.ts
Labels: 🔑 FE, 🎨 UI

#78 [FE] feat: 상세 상품 리스트 페이지 타이틀 컴포넌트 추가 #55
  frontend/.storybook/preview-body.html
  frontend/src/components/Common/Svg/SvgIcon.tsx
  frontend/src/components/Common/Svg/SvgSprite.tsx
  frontend/src/components/Common/Title/Title.tsx
  frontend/src/components/Product/ProductRankingItem/ProductRankingItem.stories.tsx
  frontend/src/components/Product/ProductRankingItem/ProductRankingItem.tsx
  frontend/src/components/Product/ProductRankingList/ProductRankingList.stories.tsx
  frontend/src/components/Product/ProductRankingList/ProductRankingList.tsx
  frontend/src/components/Product/ProductTitle/ProductTitle.stories.tsx
  frontend/src/components/Product/ProductTitle/ProductTitle.tsx
  frontend/src/components/Product/index.ts
  frontend/src/mocks/data/productDetail.json
  frontend/src/types/product.ts
Labels: 🔑 FE, ✨ Feature

#91 [FE] feat: 편의점 PB 상품 아이템 컴포넌트 추가
  frontend/src/components/Product/PBProductItem/PBProductItem.stories.tsx
  frontend/src/components/Product/PBProductItem/PBProductItem.tsx
  frontend/src/components/Product/PBProductList/PBProductList.stories.tsx
  frontend/src/components/Product/PBProductList/PBProductList.tsx
  frontend/src/mocks/data/pbProducts.json
  frontend/src/types/product.ts
Labels: 🔑 FE, ✨ Feature, 🎨 UI

#95 [BE] refactor: 환경변수에 언더스코어 적용
  backend/src/main/resources/application-dev.yml
  backend/src/main/resources/application-prod.yml
  backend/src/main/resources/application.yml
Labels: 🔒 BE, 🔧 Refactor

#75 [FE] feat: ReviewItem 컴포넌트 추가
  frontend/.storybook/preview-body.html
  frontend/src/components/Common/Svg/SvgIcon.tsx
  frontend/src/components/Common/Svg/SvgSprite.tsx
  frontend/src/components/Common/index.ts
  frontend/src/components/Review/ReviewItem/ReviewItem.stories.tsx
  frontend/src/components/Review/ReviewItem/ReviewItem.tsx
  frontend/src/components/Review/index.ts
  frontend/src/mocks/data/reviews.json
  frontend/src/types/review.ts
Labels: 🔑 FE, ✨ Feature, 🎨 UI

#97 [FE] feat: Home 페이지 마크업
  frontend/package.json
  frontend/src/components/Common/CategoryMenu/CategoryMenu.tsx
  frontend/src/components/Common/Layout/Layout.tsx
  frontend/src/components/Common/NavigationBar/NavigationBar.tsx
  frontend/src/components/Common/SortOptionList/SortOptionList.tsx
  frontend/src/components/Product/PBProductItem/PBProductItem.tsx
  frontend/src/components/Product/ProductItem/ProductItem.tsx
  frontend/src/components/Product/ProductRankingItem/ProductRankingItem.tsx
  frontend/src/components/Product/index.ts
  frontend/src/components/Review/ReviewRankingItem/ReviewRankingItem.tsx
  frontend/src/mocks/data/foodCategory.json
  frontend/src/mocks/data/storeCategory.json
  frontend/src/pages/HomePage.tsx
  frontend/yarn.lock
Labels: 🔑 FE, 🎨 UI

#100 [FE] feat: svg icon 수정
  frontend/src/components/Review/ReviewRankingItem/ReviewRankingItem.tsx
  frontend/src/pages/HomePage.tsx
Labels: 🔑 FE, 🎨 UI

#101 [FE] feat: 상품 리스트 페이지 마크업
  frontend/src/components/Common/Title/Title.tsx
  frontend/src/components/Common/index.ts
  frontend/src/constants/path.ts
  frontend/src/hooks/.gitkeep
  frontend/src/pages/ProductList.tsx
  frontend/src/pages/ProductListPage.tsx
  frontend/src/router/index.tsx
Labels: 🔑 FE, 🎨 UI

#102 [FE] feat: 상품 상세 페이지 마크업
  frontend/src/components/Common/TagList/TagList.stories.tsx
  frontend/src/components/Product/ProductDetail/ProductDetail.stories.tsx
  frontend/src/components/Product/ProductDetailItem/ProductDetailItem.stories.tsx
  frontend/src/components/Product/ProductDetailItem/ProductDetailItem.tsx
  frontend/src/components/Product/ProductList/ProductList.tsx
  frontend/src/components/Product/ProductTitle/ProductTitle.tsx
  frontend/src/components/Product/index.ts
  frontend/src/mocks/data/productDetail.json
  frontend/src/mocks/data/productDetails.json
  frontend/src/pages/ProductDetailPage.tsx
  frontend/src/router/index.tsx
Labels: 🔑 FE, 🎨 UI

#115 [FE] feat: 상품, 리뷰 목 핸들러 함수 추가
  frontend/src/components/Product/ProductList/ProductList.tsx
  frontend/src/mocks/browser.ts
  frontend/src/mocks/data/foodCategory.json
  frontend/src/mocks/data/productDetail.json
  frontend/src/mocks/data/products.json
  frontend/src/mocks/data/reviews.json
  frontend/src/mocks/handlers.ts
  frontend/src/mocks/handlers/index.ts
  frontend/src/mocks/handlers/productHandlers.ts
  frontend/src/mocks/handlers/reviewHandlers.ts
  frontend/src/mocks/handlers/utils.ts
  frontend/src/pages/ProductDetailPage.tsx
  frontend/src/types/common.ts
  frontend/src/types/review.ts
Labels: 🔑 FE, ✨ Feature

#117 [BE] test: 특정 상품에서 평점순으로 리뷰 목록을 조회하는 테스트 추가
  backend/src/test/java/com/funeat/acceptance/review/ReviewAcceptanceTest.java
  backend/src/test/java/com/funeat/review/application/ReviewServiceTest.java
Labels: 🔒 BE, ✨ Feature

#114 [FE] feat: title 변경과 favicon 추가
  frontend/public/assets/apple-icon-180x180.png
  frontend/public/assets/favicon-16x16.png
  frontend/public/assets/favicon-32x32.png
  frontend/public/assets/favicon.ico
  frontend/public/index.html
  frontend/public/manifest.json
Labels: 🔑 FE

#118 [FE] feat: 별점 컴포넌트 구현
  frontend/src/components/Review/StarRate/StarRate.stories.tsx
  frontend/src/components/Review/StarRate/StarRate.tsx
  frontend/src/hooks/useStarRate.ts
Labels: 🔑 FE, ✨ Feature, 🎨 UI

#113 [FE] feat: 리뷰 상품 요약 컴포넌트 구현
  frontend/src/components/Product/ProductOverviewItem/ProductOverviewItem.stories.tsx
  frontend/src/components/Product/ProductOverviewItem/ProductOverviewItem.tsx
  frontend/src/components/Product/ProductRankingItem/ProductRankingItem.stories.tsx
  frontend/src/components/Product/ProductRankingItem/ProductRankingItem.tsx
  frontend/src/components/Product/ProductRankingList/ProductRankingList.tsx
  frontend/src/components/Product/index.ts
Labels: 🔑 FE, ✨ Feature, 🎨 UI

#119 [FE] feat: 리뷰 사진 업로드 컴포넌트 추가
  frontend/src/components/Review/ReviewImageUploader/ReviewImageUploader.stories.tsx
  frontend/src/components/Review/ReviewImageUploader/ReviewImageUploader.tsx
Labels: 🔑 FE, ✨ Feature, 🎨 UI

#122 [FE] feat: api 기본 설정 및 카테고리 api 연결
  frontend/.gitignore
  frontend/package.json
  frontend/public/mockServiceWorker.js
  frontend/src/apis/.gitkeep
  frontend/src/apis/ApiClient.ts
  frontend/src/apis/fetch.ts
  frontend/src/apis/index.ts
  frontend/src/components/Product/ProductItem/ProductItem.stories.tsx
  frontend/src/components/Review/ReviewItem/ReviewItem.stories.tsx
  frontend/src/hooks/product/index.ts
  frontend/src/hooks/product/useCategory.ts
  frontend/src/hooks/useGet.ts
  frontend/src/hooks/useMutate.ts
  frontend/src/pages/HomePage.tsx
  frontend/webpack.common.js
  frontend/yarn.lock
Labels: 🔑 FE, ✨ Feature

#94 [BE] feat: 이미지 업로드 분기처리, 상품 평균 평점 기능 구현
  backend/src/main/java/com/funeat/product/domain/Product.java
  backend/src/main/java/com/funeat/review/application/ReviewService.java
  backend/src/main/java/com/funeat/review/domain/Review.java
  backend/src/main/java/com/funeat/review/presentation/ReviewController.java
  backend/src/main/java/com/funeat/review/presentation/dto/RankingReviewDto.java
  backend/src/main/java/com/funeat/review/presentation/dto/ReviewCreateRequest.java
  backend/src/main/java/com/funeat/review/presentation/dto/SortingReviewDto.java
  backend/src/test/java/com/funeat/acceptance/product/ProductAcceptanceTest.java
  backend/src/test/java/com/funeat/acceptance/review/ReviewAcceptanceTest.java
  backend/src/test/java/com/funeat/member/persistence/ReviewFavoriteRepositoryTest.java
  backend/src/test/java/com/funeat/product/domain/ProductTest.java
  backend/src/test/java/com/funeat/review/application/ReviewServiceTest.java
  backend/src/test/java/com/funeat/review/persistence/ReviewRepositoryTest.java
  backend/src/test/java/com/funeat/review/persistence/ReviewTagRepositoryTest.java
Labels: 🔒 BE, ✨ Feature, 🔧 Refactor

#128 [BE] fix: productId 삭제한거 충돌로 build 실패 수정
  backend/src/main/java/com/funeat/review/presentation/ReviewApiController.java
  backend/src/main/java/com/funeat/review/presentation/ReviewController.java
Labels: 🔒 BE, 🐛 Bug

#124 [FE] feat: 리뷰 작성 컴포넌트 구현
  frontend/package.json
  frontend/src/components/Review/ReviewTextarea/ReviewTextarea.stories.tsx
  frontend/src/components/Review/ReviewTextarea/ReviewTextarea.tsx
  frontend/yarn.lock
Labels: 🔑 FE, 🎨 UI

#135 [BE] refactor: 멤버의 나이, 성별, 전화번호 삭제
  backend/src/main/java/com/funeat/member/domain/Gender.java
  backend/src/main/java/com/funeat/member/domain/Member.java
  backend/src/test/java/com/funeat/acceptance/product/ProductAcceptanceTest.java
  backend/src/test/java/com/funeat/acceptance/review/ReviewAcceptanceTest.java
  backend/src/test/java/com/funeat/member/persistence/ReviewFavoriteRepositoryTest.java
  backend/src/test/java/com/funeat/review/application/ReviewServiceTest.java
  backend/src/test/java/com/funeat/review/persistence/ReviewRepositoryTest.java
  backend/src/test/java/com/funeat/review/persistence/ReviewTagRepositoryTest.java
Labels: 🔒 BE, 🔧 Refactor

#120 [FE] feat: 태그 컴포넌트 구현
  frontend/package.json
  frontend/src/components/Review/ReviewTagItem/ReviewTagItem.stories.tsx
  frontend/src/components/Review/ReviewTagItem/ReviewTagItem.tsx
  frontend/src/components/Review/ReviewTagList/ReviewTagList.stories.tsx
  frontend/src/components/Review/ReviewTagList/ReviewTagList.tsx
  frontend/src/components/Review/index.ts
  frontend/src/mocks/data/reviewTagList.json
  frontend/yarn.lock
Labels: 🔑 FE, ✨ Feature, 🎨 UI

#141 [FE] feat: 정렬 버튼 분리
  frontend/package.json
  frontend/src/components/Common/SortButton/SortButton.stories.tsx
  frontend/src/components/Common/SortButton/SortButton.tsx
  frontend/src/components/Common/SortOptionList/SortOptionList.stories.tsx
  frontend/src/components/Common/SortOptionList/SortOptionList.tsx
  frontend/src/constants/index.ts
  frontend/src/hooks/useSortOption.ts
  frontend/src/pages/ProductDetailPage.tsx
  frontend/src/pages/ProductListPage.tsx
  frontend/src/types/common.ts
  frontend/yarn.lock
Labels: 🔑 FE, ✨ Feature, 🎨 UI

#149 [BE] test: test github actions workflow script 작성
  .github/workflows/test.yml
Labels: 🔒 BE, ⚙️ Chore

#143 [FE] feat: 상품 상세 조회 API 연결
  frontend/src/apis/index.ts
  frontend/src/hooks/product/index.ts
  frontend/src/hooks/product/useProductDetail.ts
  frontend/src/mocks/handlers/productHandlers.ts
  frontend/src/pages/ProductDetailPage.tsx
Labels: 🔑 FE, ✨ Feature

#144 [FE] feat: 상품 리뷰 조회 API 연결
  frontend/package.json
  frontend/src/components/Common/SortButton/SortButton.stories.tsx
  frontend/src/components/Common/SortButton/SortButton.tsx
  frontend/src/components/Common/SortOptionList/SortOptionList.stories.tsx
  frontend/src/components/Common/SortOptionList/SortOptionList.tsx
  frontend/src/constants/index.ts
  frontend/src/hooks/product/index.ts
  frontend/src/hooks/product/useProductReview.ts
  frontend/src/hooks/useBottomSheet.ts
  frontend/src/hooks/useSortOption.ts
  frontend/src/mocks/data/reviews.json
  frontend/src/pages/ProductDetailPage.tsx
  frontend/src/pages/ProductListPage.tsx
  frontend/src/types/response.ts
  frontend/yarn.lock
Labels: 🔑 FE, ✨ Feature

#146 [BE] feat : 카테고리별 상품 목록 조회시 정렬 조건 추가 (평점순 / 리뷰개수순)
  backend/src/main/java/com/funeat/product/application/ProductService.java
  backend/src/main/java/com/funeat/product/domain/Product.java
  backend/src/main/java/com/funeat/product/dto/ProductInCategoryDto.java
  backend/src/main/java/com/funeat/product/dto/ProductsInCategoryPageDto.java
  backend/src/main/java/com/funeat/product/persistence/ProductRepository.java
  backend/src/test/java/com/funeat/acceptance/product/ProductAcceptanceTest.java
  backend/src/test/java/com/funeat/product/persistence/ProductRepositoryTest.java
Labels: 🔒 BE, ✨ Feature

#147 [FE] feat: 리뷰 좋아요 API 연결
  frontend/src/apis/ApiClient.ts
  frontend/src/components/Review/ReviewItem/ReviewItem.stories.tsx
  frontend/src/components/Review/ReviewItem/ReviewItem.tsx
  frontend/src/hooks/review/index.ts
  frontend/src/hooks/review/useReviewFavorite.ts
  frontend/src/hooks/useMutate.ts
  frontend/src/pages/ProductDetailPage.tsx
Labels: 🔑 FE, ✨ Feature

#148 [FE] feat: 카테고리별 상품을 가져오는 API 연결
  frontend/.eslintrc.js
  frontend/src/components/Common/CategoryMenu/CategoryMenu.tsx
  frontend/src/components/Common/NavigationBar/NavigationBar.tsx
  frontend/src/components/Common/Title/Title.tsx
  frontend/src/components/Product/PBProductList/PBProductList.tsx
  frontend/src/components/Product/ProductList/ProductList.tsx
  frontend/src/components/Product/ProductTitle/ProductTitle.tsx
  frontend/src/constants/index.ts
  frontend/src/contexts/CategoryContext.tsx
  frontend/src/hooks/context/index.ts
  frontend/src/hooks/context/useCategoryContext.ts
  frontend/src/hooks/product/index.ts
  frontend/src/hooks/product/useCategoryProducts.ts
  frontend/src/hooks/useRouteBack.ts
  frontend/src/mocks/data/foodCategory.json
  frontend/src/mocks/data/storeCategory.json
  frontend/src/pages/HomePage.tsx
  frontend/src/pages/ProductListPage.tsx
  frontend/src/router/index.tsx
  frontend/src/types/common.ts
  frontend/src/types/response.ts
Labels: 🔑 FE, ✨ Feature

#152 [BE] feat: 리뷰 생성 시간 필드 추가
  backend/src/main/java/com/funeat/review/domain/Review.java
  backend/src/test/java/com/funeat/review/application/ReviewServiceTest.java
Labels: 🔒 BE, ✨ Feature

#155 [BE] fix: Service Test에 Data Cleaner 적용
  backend/src/test/java/com/funeat/member/persistence/ReviewFavoriteRepositoryTest.java
  backend/src/test/java/com/funeat/review/application/ReviewServiceTest.java
Labels: 🔒 BE, 🐛 Bug

#161 [BE] feat: 전체 태그 목록 조회 기능 추가
  backend/src/main/java/com/funeat/product/dto/ProductResponse.java
  backend/src/main/java/com/funeat/tag/application/TagService.java
  backend/src/main/java/com/funeat/tag/domain/Tag.java
  backend/src/main/java/com/funeat/tag/domain/TagType.java
  backend/src/main/java/com/funeat/tag/dto/TagDto.java
  backend/src/main/java/com/funeat/tag/dto/TagsResponse.java
  backend/src/main/java/com/funeat/tag/persistence/TagRepository.java
  backend/src/main/java/com/funeat/tag/presentation/TagApiController.java
  backend/src/main/java/com/funeat/tag/presentation/TagController.java
  backend/src/test/java/com/funeat/acceptance/product/ProductAcceptanceTest.java
  backend/src/test/java/com/funeat/acceptance/review/ReviewAcceptanceTest.java
  backend/src/test/java/com/funeat/acceptance/tag/TagAcceptanceTest.java
  backend/src/test/java/com/funeat/acceptance/tag/TagSteps.java
  backend/src/test/java/com/funeat/review/application/ReviewServiceTest.java
  backend/src/test/java/com/funeat/review/persistence/ReviewTagRepositoryTest.java
  backend/src/test/java/com/funeat/tag/persistence/TagRepositoryTest.java
Labels: 🔒 BE, ✨ Feature

#150 [FE] feat: 리뷰 작성 페이지 구현
  frontend/.storybook/preview-body.html
  frontend/package.json
  frontend/src/components/Common/Svg/SvgIcon.tsx
  frontend/src/components/Common/Svg/SvgSprite.tsx
  frontend/src/components/Product/ProductOverviewItem/ProductOverviewItem.tsx
  frontend/src/components/Product/ProductRankingList/ProductRankingList.tsx
  frontend/src/components/Review/ReviewImageUploader/ReviewImageUploader.tsx
  frontend/src/components/Review/ReviewRegisterForm/ReviewRegisterForm.stories.tsx
  frontend/src/components/Review/ReviewRegisterForm/ReviewRegisterForm.tsx
  frontend/src/components/Review/ReviewTagList/ReviewTagList.tsx
  frontend/src/components/Review/ReviewTextarea/ReviewTextarea.tsx
  frontend/src/components/Review/StarRate/StarRate.tsx
  frontend/src/components/Review/index.ts
  frontend/src/mocks/data/productDetail.json
  frontend/src/pages/ProductDetailPage.tsx
Labels: 🔑 FE, ✨ Feature, 🎨 UI

#167 [FE] 충돌 해결
  frontend/src/components/Common/CategoryMenu/CategoryMenu.tsx
  frontend/src/components/Review/StarRate/StarRate.tsx
  frontend/src/pages/ProductDetailPage.tsx
Labels: 🔑 FE, 🐛 Bug

#169 [FE] fix: 바텀시트 오류 해결
  frontend/src/pages/ProductDetailPage.tsx
Labels: 🔑 FE, 🐛 Bug

#170 [FE] Tag 컴포넌트 디자인 수정
  frontend/src/components/Review/ReviewTagItem/ReviewTagItem.stories.tsx
  frontend/src/components/Review/ReviewTagItem/ReviewTagItem.tsx
  frontend/src/components/Review/ReviewTagList/ReviewTagList.tsx
  frontend/src/constants/index.ts
  frontend/src/hooks/review/index.ts
  frontend/src/hooks/review/useReviewTag.ts
  frontend/src/mocks/data/reviewTagList.json
  frontend/src/types/common.ts
  frontend/src/types/review.ts
Labels: 🔑 FE, 🔧 Refactor

#164 [FE] feat: 상품 목록 정렬 기능 API 연결
  frontend/src/hooks/product/useCategoryProducts.ts
  frontend/src/hooks/product/useProductReview.ts
  frontend/src/hooks/useGet.ts
  frontend/src/pages/ProductListPage.tsx
Labels: 🔑 FE, ✨ Feature

#162 [FE] feat: 로그인 페이지 구현
  frontend/.storybook/preview-body.html
  frontend/src/App.tsx
  frontend/src/apis/ApiClient.ts
  frontend/src/apis/index.ts
  frontend/src/assets/logo.svg
  frontend/src/components/Common/Header/Header.tsx
  frontend/src/components/Common/Svg/SvgIcon.tsx
  frontend/src/components/Common/Svg/SvgSprite.tsx
  frontend/src/components/Common/index.ts
  frontend/src/components/Layout/AuthLayout.tsx
  frontend/src/components/Layout/DefaultLayout.tsx
  frontend/src/components/Layout/index.ts
  frontend/src/constants/path.ts
  frontend/src/hooks/auth/index.ts
  frontend/src/hooks/auth/useLogin.ts
  frontend/src/hooks/useGet.ts
  frontend/src/hooks/useMutate.ts
  frontend/src/mocks/browser.ts
  frontend/src/mocks/handlers/authHandlers.ts
  frontend/src/mocks/handlers/index.ts
  frontend/src/pages/LoginPage.tsx
  frontend/src/router/App.tsx
  frontend/src/router/index.tsx
Labels: 🔑 FE, ✨ Feature, 🎨 UI

#176 [FE] feat: 리뷰 태그 조회 API 연결
  frontend/src/apis/index.ts
  frontend/src/components/Review/ReviewTagList/ReviewTagList.tsx
  frontend/src/hooks/review/index.ts
  frontend/src/hooks/review/useDisplayTag.ts
  frontend/src/hooks/review/useReviewTag.ts
  frontend/src/hooks/review/useReviewTags.ts
  frontend/src/mocks/handlers/reviewHandlers.ts
Labels: 🔑 FE, ✨ Feature

#171 [BE] test: 특정 상품에서 최신순으로 리뷰 목록을 조회하는 테스트 추가
  backend/src/test/java/com/funeat/acceptance/review/ReviewAcceptanceTest.java
  backend/src/test/java/com/funeat/review/application/ReviewServiceTest.java
Labels: 🔒 BE, 💻 Test

#174 [BE] fix: 정렬된 리뷰 목록 페이징 요청시 API가 정상적으로 응답하도록 수정
  backend/src/main/java/com/funeat/review/presentation/dto/SortingReviewDto.java
  backend/src/main/java/com/funeat/tag/dto/TagDto.java
Labels: 🔒 BE, 🐛 Bug

#182 [FE] feat: 상세 레이아웃 추가
  frontend/src/components/Layout/DetailLayout.tsx
  frontend/src/components/Layout/index.ts
  frontend/src/pages/ProductDetailPage.tsx
  frontend/src/router/App.tsx
  frontend/src/router/index.tsx
Labels: 🔑 FE, 🔧 Refactor, 🎨 UI
