Repository woowacourse-teams/2023-fun-eat, pull requests merged in 2023-08, with the labels that each got.

#180 [FE] feat: 리뷰랭킹 조회 API 연결
  frontend/src/apis/index.ts
  frontend/src/components/Product/index.ts
  frontend/src/components/Rank/ProductRankingList/ProductRankingList.stories.tsx
  frontend/src/components/Rank/ProductRankingList/ProductRankingList.tsx
  frontend/src/components/Rank/ReviewRankingItem/ReviewRankingItem.stories.tsx
  frontend/src/components/Rank/ReviewRankingItem/ReviewRankingItem.tsx
  frontend/src/components/Rank/ReviewRankingList/ReviewRankingList.stories.tsx
  frontend/src/components/Rank/ReviewRankingList/ReviewRankingList.tsx
  frontend/src/components/Rank/index.ts
  frontend/src/components/Review/index.ts
  frontend/src/hooks/rank/index.ts
  frontend/src/hooks/rank/useReviewRanking.ts
  frontend/src/mocks/browser.ts
  frontend/src/mocks/handlers/index.ts
  frontend/src/mocks/handlers/rankingHandlers.ts
  frontend/src/pages/HomePage.tsx
  frontend/src/types/index.ts
  frontend/src/types/response.ts
  frontend/yarn.lock
Labels: 🔒 BE, 🔑 FE, ✨ Feature

#190 [BE] feat: CORS 설정 추가
  backend/src/main/java/com/funeat/common/WebConfig.java
Labels: 🔒 BE, ✨ Feature

#193 [BE] fix: CORS에서 모든 헤더를 열어주는 것으로 수정
  backend/src/main/java/com/funeat/common/WebConfig.java
Labels: 🔒 BE, 🐛 Bug

#195 [BE] refactor: 로그인 url 변경
  backend/src/main/java/com/funeat/auth/presentation/AuthController.java
  backend/src/test/java/com/funeat/auth/presentation/AuthControllerTest.java
Labels: 🔒 BE, 🔧 Refactor

#198 [BE] refactor: get 요청에서 post 요청으로 변경
  backend/src/main/java/com/funeat/auth/presentation/AuthController.java
  backend/src/test/java/com/funeat/auth/presentation/AuthControllerTest.java
Labels: 🔒 BE, 🔧 Refactor

#199 [ALL] 로그인 API 연결
  frontend/src/apis/index.ts
  frontend/src/hooks/auth/index.ts
  frontend/src/hooks/auth/useAuth.ts
  frontend/src/pages/AuthPage.tsx
  frontend/src/pages/LoginPage.tsx
  frontend/src/router/index.tsx
Labels: 🔒 BE, 🔑 FE, ✨ Feature

#201 [BE] fix: 회원을 등록할 때, 새로운 트랜잭션에서 수행되도록 수정
  backend/src/main/java/com/funeat/member/application/MemberService.java
Labels: 🔒 BE, 🐛 Bug

#203 [BE] refactor: readonly 제거
  backend/src/main/java/com/funeat/auth/application/AuthService.java
  backend/src/main/java/com/funeat/member/application/MemberService.java
Labels: 🔒 BE, 🐛 Bug

#186 [BE] feat: 회원 정보를 수정하는 기능 추가
  backend/src/main/java/com/funeat/member/application/MemberService.java
  backend/src/main/java/com/funeat/member/domain/Member.java
  backend/src/main/java/com/funeat/member/dto/MemberRequest.java
  backend/src/main/java/com/funeat/member/presentation/MemberApiController.java
  backend/src/main/java/com/funeat/member/presentation/MemberController.java
  backend/src/test/java/com/funeat/acceptance/member/MemberAcceptanceTest.java
  backend/src/test/java/com/funeat/acceptance/member/MemberSteps.java
  backend/src/test/java/com/funeat/member/application/MemberServiceTest.java
  backend/src/test/java/com/funeat/member/domain/MemberTest.java
Labels: 🔒 BE, ✨ Feature

#191 [BE] feat: 로그인 Swagger UI 추가
  backend/src/main/java/com/funeat/auth/presentation/AuthApiController.java
  backend/src/main/java/com/funeat/auth/presentation/AuthController.java
  backend/src/test/java/com/funeat/auth/presentation/AuthApiControllerTest.java
Labels: 🔒 BE, 🔧 Refactor

#209 [FE] feat: 정렬 필터링 추가
  frontend/src/constants/index.ts
Labels: 🔑 FE, ✨ Feature

#206 [BE] feat: 리뷰 작성과 리뷰 좋아요 기능에 로그인 붙이기
  backend/src/main/java/com/funeat/auth/util/AuthHandlerInterceptor.java
  backend/src/main/java/com/funeat/common/WebConfig.java
  backend/src/main/java/com/funeat/member/domain/favorite/ReviewFavorite.java
  backend/src/main/java/com/funeat/review/application/ReviewService.java
  backend/src/main/java/com/funeat/review/presentation/ReviewApiController.java
  backend/src/main/java/com/funeat/review/presentation/ReviewController.java
  backend/src/main/java/com/funeat/review/presentation/dto/ReviewCreateRequest.java
  backend/src/main/java/com/funeat/review/presentation/dto/ReviewFavoriteRequest.java
  backend/src/test/java/com/funeat/acceptance/common/LoginSteps.java
  backend/src/test/java/com/funeat/acceptance/product/ProductAcceptanceTest.java
  backend/src/test/java/com/funeat/acceptance/review/ReviewAcceptanceTest.java
  backend/src/test/java/com/funeat/acceptance/review/ReviewSteps.java
  backend/src/test/java/com/funeat/review/application/ReviewServiceTest.java
Labels: 🔒 BE, ✨ Feature

#211 [FE] feat: 회원 정보 API 연결 및 회원, 비회원 처리
  frontend/src/apis/ApiClient.ts
  frontend/src/apis/index.ts
  frontend/src/contexts/MemberContext.tsx
  frontend/src/hooks/auth/index.ts
  frontend/src/hooks/auth/useLogin.ts
  frontend/src/hooks/context/index.ts
  frontend/src/hooks/context/useMemberActionContext.ts
  frontend/src/hooks/context/useMemberValueContext.ts
  frontend/src/index.tsx
  frontend/src/mocks/browser.ts
  frontend/src/mocks/handlers/authHandlers.ts
  frontend/src/mocks/handlers/index.ts
  frontend/src/mocks/handlers/loginHandlers.ts
  frontend/src/mocks/handlers/memberHandlers.ts
  frontend/src/pages/AuthPage.tsx
  frontend/src/pages/LoginPage.tsx
  frontend/src/pages/ProfilePage.tsx
  frontend/src/types/member.ts
Labels: 🔑 FE, ✨ Feature

#212 [BE] 회원 정보를 조회하는 기능 추가
  backend/src/main/java/com/funeat/member/application/MemberService.java
  backend/src/main/java/com/funeat/member/dto/MemberProfileResponse.java
  backend/src/main/java/com/funeat/member/presentation/MemberApiController.java
  backend/src/main/java/com/funeat/member/presentation/MemberController.java
  backend/src/test/java/com/funeat/acceptance/member/MemberAcceptanceTest.java
  backend/src/test/java/com/funeat/acceptance/member/MemberSteps.java
  backend/src/test/java/com/funeat/member/application/MemberServiceTest.java
Labels: 🔒 BE, ✨ Feature

#216 [BE] refactor: 사용자 정보 조회, 수정 요청을 할 때, 쿠키를 통해 사용자를 파악할 수 있도록 수정
  backend/src/main/java/com/funeat/auth/dto/LoginInfo.java
  backend/src/main/java/com/funeat/auth/presentation/AuthApiController.java
  backend/src/main/java/com/funeat/auth/presentation/AuthController.java
  backend/src/main/java/com/funeat/auth/util/AuthArgumentResolver.java
  backend/src/main/java/com/funeat/auth/util/MemberHandlerInterceptor.java
  backend/src/main/java/com/funeat/common/WebConfig.java
  backend/src/main/java/com/funeat/member/presentation/MemberApiController.java
  backend/src/main/java/com/funeat/member/presentation/MemberController.java
  backend/src/main/java/com/funeat/review/presentation/ReviewApiController.java
  backend/src/main/java/com/funeat/review/presentation/ReviewController.java
  backend/src/test/java/com/funeat/acceptance/member/MemberAcceptanceTest.java
  backend/src/test/java/com/funeat/acceptance/member/MemberSteps.java
Labels: 🔒 BE, 🔧 Refactor

#220 [BE] fix: POST -> GET, 302 Found -> 200 OK로 변경
  backend/src/main/java/com/funeat/auth/presentation/AuthApiController.java
  backend/src/test/java/com/funeat/acceptance/common/LoginSteps.java
  backend/src/test/java/com/funeat/auth/presentation/AuthApiControllerTest.java
Labels: 🔒 BE, 🐛 Bug

#222 [FE] refactor: 세션 아이디 요청 메서드 POST -> GET으로 수정
  frontend/src/hooks/auth/useAuth.ts
  frontend/src/mocks/handlers/loginHandlers.ts
  frontend/src/pages/AuthPage.tsx
Labels: 🔑 FE, 🐛 Bug

#229 [FE] feat: 회원 정보 요청 제거
  frontend/src/pages/AuthPage.tsx
Labels: 🔑 FE, 🐛 Bug

#214 [FE] feat: 홈 화면에 보이는 상품 개수 조절 및 엑박 수정
  frontend/src/assets/characters.svg
  frontend/src/assets/logo.svg
  frontend/src/assets/samgakgimbab.svg
  frontend/src/components/Product/PBProductItem/PBProductItem.tsx
  frontend/src/components/Product/ProductDetailItem/ProductDetailItem.tsx
  frontend/src/components/Product/ProductItem/ProductItem.tsx
  frontend/src/pages/HomePage.tsx
Labels: 🔑 FE, 🎨 UI

#217 [FE] refactor: 버튼 내부에 div 태그 제거
  frontend/src/components/Common/SortButton/SortButton.tsx
  frontend/src/components/Common/Title/Title.tsx
  frontend/src/components/Review/ReviewTagList/ReviewTagList.tsx
Labels: 🔑 FE, 🎨 UI

#231 [FE] feat: 세션 아이디 요청에 credentials 옵션 추가
  frontend/src/pages/AuthPage.tsx
Labels: 🔑 FE, 🐛 Bug

#204 [BE] feat: 상품 랭킹 기능 추가
  backend/src/main/java/com/funeat/product/application/ProductService.java
  backend/src/main/java/com/funeat/product/domain/Product.java
  backend/src/main/java/com/funeat/product/dto/ProductReviewCountDto.java
  backend/src/main/java/com/funeat/product/dto/RankingProductDto.java
  backend/src/main/java/com/funeat/product/dto/RankingProductsResponse.java
  backend/src/main/java/com/funeat/product/persistence/ProductRepository.java
  backend/src/main/java/com/funeat/product/presentation/ProductApiController.java
  backend/src/main/java/com/funeat/product/presentation/ProductController.java
  backend/src/test/java/com/funeat/acceptance/product/ProductAcceptanceTest.java
  backend/src/test/java/com/funeat/acceptance/product/ProductSteps.java
  backend/src/test/java/com/funeat/product/application/ProductServiceTest.java
  backend/src/test/java/com/funeat/product/domain/ProductTest.java
  backend/src/test/java/com/funeat/product/persistence/ProductRepositoryTest.java
Labels: 🔒 BE, ✨ Feature

#238 [BE] fix: CORS 설정 Nginx로 이관
  backend/src/main/java/com/funeat/common/WebConfig.java
Labels: 🔒 BE, 🐛 Bug

#242 [FE] feat: 세션 아이디 로그 확인
  frontend/src/pages/AuthPage.tsx
Labels: 🔑 FE

#244 fix: MemberHandlerInterceptor의 매핑 url pattern 수정
  backend/src/main/java/com/funeat/auth/util/AuthArgumentResolver.java
  backend/src/main/java/com/funeat/common/WebConfig.java
Labels: 🔒 BE, 🐛 Bug

#246 [BE] feat: 디버그용 log 추가
  backend/src/main/java/com/funeat/auth/util/MemberHandlerInterceptor.java
  backend/src/main/java/com/funeat/common/WebConfig.java
Labels: 🔒 BE, 🐛 Bug

#249 [FE] fix: 리뷰 작성 헤더 삭제
  frontend/src/components/Review/ReviewRegisterForm/ReviewRegisterForm.tsx
Labels: 🔑 FE, 🐛 Bug

#251 [BE] chore: 파일 업로드 관련 의존성 추가
  backend/build.gradle
Labels: 🔒 BE, ⚙️ Chore

#252 [BE] fix: 의존성 에러 수정
  backend/build.gradle
Labels: 🔒 BE, ⚙️ Chore

#253 [BE] chore: multipart 관련 yml 수정
  backend/src/main/resources/application.yml
Labels: 🔒 BE, ⚙️ Chore

#255 [FE] fix: blob 추가
  frontend/src/components/Review/ReviewRegisterForm/ReviewRegisterForm.tsx
Labels: 🔑 FE, 🐛 Bug

#257 [FE] feat: 이미지 링크 수정
  frontend/src/components/Review/ReviewRegisterForm/ReviewRegisterForm.tsx
  frontend/src/hooks/review/useReviewImageUploader.ts
Labels: 🔑 FE, 🔧 Refactor

#259 [FE] feat: 이미지 링크 전송 함수 작성
  frontend/src/apis/ApiClient.ts
  frontend/src/components/Review/ReviewImageUploader/ReviewImageUploader.tsx
  frontend/src/components/Review/ReviewRegisterForm/ReviewRegisterForm.tsx
  frontend/src/hooks/review/useReviewImageUploader.ts
Labels: 🔑 FE, ✨ Feature

#262 [BE] chore: 파일 업로드 관련 의존성 제거
  backend/build.gradle
Labels: 🔒 BE, ⚙️ Chore

#268 [FE] feat: 리뷰 좋아요 요청 수정
  frontend/src/components/Review/ReviewItem/ReviewItem.tsx
  frontend/src/hooks/review/useReviewFavorite.ts
Labels: 🔑 FE, ✨ Feature

#270 [FE] fix: 리뷰 좋아요 요청 본문 수정
  frontend/src/components/Review/ReviewItem/ReviewItem.tsx
  frontend/src/types/review.ts
Labels: 🔑 FE, 🐛 Bug

#274 [BE] fix: 리뷰 좋아요 시 NPE 발생 수정
  backend/src/main/java/com/funeat/member/domain/favorite/ReviewFavorite.java
  backend/src/main/java/com/funeat/review/application/ReviewService.java
  backend/src/main/java/com/funeat/review/presentation/dto/ReviewCreateRequest.java
  backend/src/main/java/com/funeat/review/presentation/dto/SortingReviewDto.java
  backend/src/test/java/com/funeat/acceptance/review/ReviewAcceptanceTest.java
Labels: 🔒 BE, 🐛 Bug

#239 [BE] refactor: 리뷰 페이징 dto에 작성 시간을 추가
  backend/src/main/java/com/funeat/review/presentation/dto/SortingReviewDto.java
Labels: 🔒 BE, 🔧 Refactor

#241 [BE] fix: 기존 회원은 홈으로, 신규 회원은 마이페이지로 이동
  backend/src/main/java/com/funeat/auth/dto/SignUserDto.java
  backend/src/main/java/com/funeat/auth/presentation/AuthApiController.java
  backend/src/test/java/com/funeat/auth/presentation/AuthApiControllerTest.java
  backend/src/test/java/com/funeat/member/application/MemberServiceTest.java
Labels: 🔒 BE, 🐛 Bug

#276 [BE] fix: 리뷰 좋아요가 존재하거나 존재하지 않을 때 분기처리 수정
  backend/src/main/java/com/funeat/review/application/ReviewService.java
Labels: 🔒 BE, 🐛 Bug

#278 [FE] feat: 리뷰 좋아요 요청 본문 수정
  frontend/src/components/Review/ReviewItem/ReviewItem.tsx
  frontend/src/types/review.ts
Labels: 🔑 FE, ✨ Feature

#280 [FE] fix: 재구매 철자 수정과 이미지 경로 수정
  frontend/src/components/Review/ReviewItem/ReviewItem.tsx
  frontend/src/components/Review/ReviewRegisterForm/ReviewRegisterForm.tsx
Labels: 🔑 FE, 🐛 Bug

#289 [BE] feat: 로그인 에러 핸들링 기능 추가
  backend/src/main/java/com/funeat/auth/exception/LoginException.java
  backend/src/main/java/com/funeat/auth/util/AuthHandlerInterceptor.java
  backend/src/main/java/com/funeat/auth/util/MemberHandlerInterceptor.java
  backend/src/main/java/com/funeat/common/WebConfig.java
  backend/src/main/java/com/funeat/exception/presentation/GlobalControllerAdvice.java
  backend/src/main/java/com/funeat/review/presentation/ReviewApiController.java
  backend/src/main/java/com/funeat/review/presentation/ReviewController.java
  backend/src/test/java/com/funeat/acceptance/review/ReviewAcceptanceTest.java
Labels: 🔒 BE, ✨ Feature

#293 [BE] fix: 로그인된 회원 기준으로 좋아요 조회되게 수정
  backend/src/main/java/com/funeat/member/domain/favorite/ReviewFavorite.java
  backend/src/main/java/com/funeat/review/application/ReviewService.java
  backend/src/main/java/com/funeat/review/presentation/ReviewApiController.java
  backend/src/main/java/com/funeat/review/presentation/dto/SortingReviewDto.java
  backend/src/test/java/com/funeat/acceptance/review/ReviewAcceptanceTest.java
  backend/src/test/java/com/funeat/review/application/ReviewServiceTest.java
Labels: 🔒 BE, ✨ Feature, 🐛 Bug

#297 [FE] feat: 리뷰 조회 회원, 비회원 처리
  frontend/src/components/Review/ReviewList/ReviewList.tsx
  frontend/src/components/Review/index.ts
  frontend/src/contexts/ProductReviewContext.tsx
  frontend/src/hooks/context/index.ts
  frontend/src/hooks/context/useProductReviewContext.ts
  frontend/src/hooks/product/index.ts
  frontend/src/hooks/product/useInfiniteProductReviews.ts
  frontend/src/hooks/product/useProductReview.ts
  frontend/src/hooks/useGet.ts
  frontend/src/mocks/handlers/productHandlers.ts
  frontend/src/mocks/handlers/reviewHandlers.ts
  frontend/src/pages/ProductDetailPage.tsx
  frontend/src/router/index.tsx
Labels: 🔑 FE, ✨ Feature

#287 [FE] feat: 리뷰 작성 필수값 미입력시 작성 버튼 비활성화
  frontend/src/components/Review/ReviewRegisterForm/ReviewRegisterForm.tsx
Labels: 🔑 FE, 🔧 Refactor

#292 [FE] feat: 로그인 안 했을 때 리뷰 작성 막기, 작성 완료 후 모달 닫기, 개발 환경일 때 이미지 경로 수정
  frontend/src/components/Review/ReviewItem/ReviewItem.tsx
  frontend/src/components/Review/ReviewRegisterForm/ReviewRegisterForm.tsx
  frontend/src/pages/ProductDetailPage.tsx
Labels: 🔑 FE, ✨ Feature

#300 [BE] fix: 트랜잭션 전파 옵션을 설정
  backend/src/main/java/com/funeat/member/application/MemberService.java
  backend/src/test/java/com/funeat/member/application/MemberServiceTest.java
  backend/src/test/java/com/funeat/member/application/TestMemberService.java
Labels: 🔒 BE, 🐛 Bug

#299 [FE] feat: 상품 랭킹 API 연결
  frontend/src/components/Rank/ProductRankingList/ProductRankingList.stories.tsx
  frontend/src/components/Rank/ProductRankingList/ProductRankingList.tsx
  frontend/src/components/Rank/ReviewRankingList/ReviewRankingList.stories.tsx
  frontend/src/hooks/rank/index.ts
  frontend/src/hooks/rank/useProductRanking.ts
  frontend/src/mocks/data/productRanking.json
  frontend/src/mocks/data/productRankingList.json
  frontend/src/mocks/handlers/rankingHandlers.ts
  frontend/src/pages/HomePage.tsx
  frontend/src/types/ranking.ts
  frontend/src/types/response.ts
  frontend/yarn.lock
Labels: 🔒 BE, 🔑 FE, ✨ Feature

#304 [FE] feat: 리뷰 Post 후 get 로직 구현과 리뷰 기본 값 최신 작성순으로 변경
  frontend/src/components/Review/ReviewRegisterForm/ReviewRegisterForm.tsx
  frontend/src/constants/index.ts
  frontend/src/contexts/ProductReviewContext.tsx
  frontend/src/hooks/product/useInfiniteProductReviews.ts
  frontend/src/mocks/data/reviews.json
  frontend/src/mocks/handlers/utils.ts
Labels: 🔑 FE, ✨ Feature, 🔧 Refactor

#306 [FE] fix: 타입 에러 수정과 페이지 컨텍스트 분리
  frontend/src/components/Review/ReviewRegisterForm/ReviewRegisterForm.tsx
  frontend/src/contexts/ProductReviewContext.tsx
  frontend/src/hooks/context/useProductReviewPageContext.ts
  frontend/src/hooks/product/useInfiniteProductReviews.ts
Labels: 🔑 FE, 🐛 Bug

#308 [FE] feat: 폼 작성 후 리셋
  frontend/src/components/Review/ReviewRegisterForm/ReviewRegisterForm.tsx
Labels: 🔑 FE, ✨ Feature

#310 [FE] feat: 리뷰 좋아요 시 리뷰 숫자 업데이트 구현
  frontend/src/components/Review/ReviewItem/ReviewItem.tsx
  frontend/src/pages/ProductDetailPage.tsx
Labels: 🔑 FE, ✨ Feature

#311 [FE] fix: 폼 작성 후 리셋 에러 수정
  frontend/src/components/Review/ReviewRegisterForm/ReviewRegisterForm.tsx
Labels: 🔑 FE, 🐛 Bug

#316 [FE] feat: 마이페이지 접근시 회원 정보 조회 요청 추가
  frontend/package.json
  frontend/src/hooks/auth/index.ts
  frontend/src/hooks/auth/useMember.ts
  frontend/src/pages/AuthPage.tsx
  frontend/src/pages/ProfilePage.tsx
  frontend/yarn.lock
Labels: 🔑 FE, ✨ Feature

#227 [FE] feat: 상품 리스트에서 PB상품, 공통 상품 이동 기능 추가
  frontend/src/components/Common/CategoryMenu/CategoryMenu.tsx
  frontend/src/components/Common/Title/Title.tsx
  frontend/src/components/Product/PBProductItem/PBProductItem.stories.tsx
  frontend/src/hooks/product/useCategory.ts
  frontend/src/mocks/data/pbProducts.json
  frontend/src/mocks/handlers/productHandlers.ts
  frontend/src/pages/ProductListPage.tsx
  frontend/src/types/common.ts
  frontend/src/types/product.ts
Labels: 🔑 FE, ✨ Feature, 🎨 UI

#281 [FE] feat: 리뷰 작성 페이지 웹 접근성 고려
  frontend/src/components/Product/ProductOverviewItem/ProductOverviewItem.tsx
  frontend/src/components/Review/ReviewImageUploader/ReviewImageUploader.tsx
  frontend/src/components/Review/ReviewRegisterForm/ReviewRegisterForm.tsx
  frontend/src/components/Review/ReviewTagList/ReviewTagList.tsx
  frontend/src/components/Review/ReviewTextarea/ReviewTextarea.tsx
  frontend/src/components/Review/StarRate/StarRate.tsx
  frontend/src/hooks/useEnterKeyDown.ts
Labels: 🔑 FE, ✨ Feature, 🔧 Refactor

#319 [FE] feat: 상품 상세 로그인 필요 메시지에 로그인 링크 추가
  frontend/src/components/Review/ReviewList/ReviewList.tsx
  frontend/src/pages/ProfilePage.tsx
Labels: 🔑 FE, ✨ Feature

#322 [FE] fix: 리뷰 작성 폼 에러 수정
  frontend/src/components/Review/ReviewImageUploader/ReviewImageUploader.tsx
  frontend/src/components/Review/ReviewRegisterForm/ReviewRegisterForm.tsx
  frontend/src/components/Review/ReviewTagItem/ReviewTagItem.tsx
  frontend/src/hooks/review/useReviewImageUploader.ts
Labels: 🔑 FE, 🐛 Bug

#324 [BE] fix: 카카오 로그인 경로 수정
  backend/src/main/java/com/funeat/auth/util/KakaoPlatformUserProvider.java
Labels: 🔒 BE, 🐛 Bug

#327 [BE] feat: warn, error 발생 시 슬랙으로 알람기능 추가
  backend/build.gradle
  backend/src/main/resources/logback-spring.xml
Labels: 🔒 BE, ✨ Feature

#342 [FE] feat: 라우터 관련 이슈 해결
  frontend/src/components/Common/Header/Header.tsx
  frontend/src/components/Common/Title/Title.tsx
  frontend/src/components/Product/ProductTitle/ProductTitle.tsx
  frontend/src/hooks/useRouteBack.ts
  frontend/src/hooks/useRoutePage.ts
  frontend/src/pages/LoginPage.tsx
Labels: 🔑 FE, ✨ Feature, 🐛 Bug

#345 [FE] feat: 리뷰 작성 리팩터링
  frontend/package.json
  frontend/src/apis/index.ts
  frontend/src/components/Review/ReviewImageUploader/ReviewImageUploader.tsx
  frontend/src/components/Review/ReviewRegisterForm/ReviewRegisterForm.tsx
  frontend/src/components/Review/ReviewTagList/ReviewTagList.tsx
  frontend/src/components/Review/StarRate/StarRate.tsx
  frontend/src/hooks/context/index.ts
  frontend/src/hooks/review/index.ts
  frontend/src/hooks/review/useFormData.ts
  frontend/src/hooks/review/useReviewImageUploader.ts
  frontend/src/hooks/review/useReviewRegisterForm.ts
  frontend/src/hooks/review/useStarRating.ts
  frontend/src/hooks/useEnterKeyDown.ts
  frontend/src/pages/ProductDetailPage.tsx
  frontend/src/types/review.ts
  frontend/yarn.lock
Labels: 🔑 FE, 🔧 Refactor

#352 [FE] refactor: 리뷰 작성 폼 컨텍스트로 리팩터링
  frontend/src/components/Review/RebuyCheckbox/RebuyCheckbox.tsx
  frontend/src/components/Review/ReviewRegisterForm/ReviewRegisterForm.tsx
  frontend/src/components/Review/ReviewTagItem/ReviewTagItem.tsx
  frontend/src/components/Review/ReviewTagList/ReviewTagList.tsx
  frontend/src/components/Review/ReviewTextarea/ReviewTextarea.tsx
  frontend/src/components/Review/StarRate/StarRate.tsx
  frontend/src/contexts/ReviewFormContext.tsx
  frontend/src/hooks/context/index.ts
  frontend/src/hooks/context/useReviewFormActionContext.ts
  frontend/src/hooks/context/useReviewFormValueContext.ts
  frontend/src/hooks/review/index.ts
  frontend/src/hooks/review/useReviewTextarea.ts
  frontend/src/hooks/review/useSelectedTags.ts
  frontend/src/hooks/review/useStarRating.ts
  frontend/src/hooks/review/useStarRatingHover.ts
  frontend/src/pages/ProductDetailPage.tsx
  frontend/src/types/review.ts
Labels: 🔑 FE, 🔧 Refactor

#349 [BE] feat: 꿀조합 작성 기능 구현
  backend/src/main/java/com/funeat/common/ImageService.java
  backend/src/main/java/com/funeat/common/ImageUploader.java
  backend/src/main/java/com/funeat/common/WebConfig.java
  backend/src/main/java/com/funeat/product/domain/ProductRecipe.java
  backend/src/main/java/com/funeat/recipe/application/RecipeService.java
  backend/src/main/java/com/funeat/recipe/domain/Recipe.java
  backend/src/main/java/com/funeat/recipe/domain/RecipeImage.java
  backend/src/main/java/com/funeat/recipe/dto/RecipeCreateRequest.java
  backend/src/main/java/com/funeat/recipe/presentation/RecipeApiController.java
  backend/src/main/java/com/funeat/recipe/presentation/RecipeController.java
  backend/src/main/java/com/funeat/recipe/utill/RecipeHandlerInterceptor.java
  backend/src/main/java/com/funeat/review/application/ReviewService.java
  backend/src/main/resources/application-dev.yml
  backend/src/main/resources/application-local.yml
  backend/src/main/resources/application-prod.yml
  backend/src/test/java/com/funeat/FuneatApplicationTests.java
  backend/src/test/java/com/funeat/acceptance/recipe/RecipeAcceptanceTest.java
  backend/src/test/java/com/funeat/acceptance/recipe/RecipeSteps.java
  backend/src/test/java/com/funeat/common/TestImageUploader.java
  backend/src/test/java/com/funeat/recipe/application/RecipeServiceTest.java
Labels: 🔒 BE, ✨ Feature

#355 [FE] feat: 이미지 압축 구현
  frontend/src/components/Review/ReviewImageUploader/ReviewImageUploader.tsx
  frontend/src/hooks/review/useReviewImageUploader.ts
Labels: 🔑 FE, ✨ Feature

#357 [FE] feat: react-query 도입
  frontend/.eslintrc.js
  frontend/package.json
  frontend/src/components/Review/ReviewList/ReviewList.tsx
  frontend/src/components/Review/ReviewRegisterForm/ReviewRegisterForm.tsx
  frontend/src/contexts/ProductReviewContext.tsx
  frontend/src/hooks/context/index.ts
  frontend/src/hooks/context/useProductReviewContext.ts
  frontend/src/hooks/context/useProductReviewPageContext.ts
  frontend/src/hooks/product/index.ts
  frontend/src/hooks/product/useInfiniteProductReviews.ts
  frontend/src/hooks/product/useInfiniteProductReviewsQuery.ts
  frontend/src/hooks/product/useInfiniteProducts.ts
  frontend/src/hooks/product/useInfiniteProductsQuery.ts
  frontend/src/hooks/review/index.ts
  frontend/src/hooks/review/useReviewRegisterForm.ts
  frontend/src/hooks/review/useReviewRegisterFormMutation.ts
  frontend/src/index.tsx
  frontend/src/mocks/handlers/productHandlers.ts
  frontend/src/pages/ProductDetailPage.tsx
  frontend/src/pages/ProductListPage.tsx
  frontend/src/router/index.tsx
  frontend/yarn.lock
Labels: 🔑 FE, ✨ Feature, ⚙️ Chore

#362 [FE] fix: 이미지 압축 패키지 설치 및 웹팩 설정 수정
  frontend/package.json
  frontend/webpack.common.js
  frontend/yarn.lock
Labels: 🔑 FE, 🐛 Bug

#368 [BE] feat: logback 환경 분리 설정
  backend/src/main/resources/application.yml
  backend/src/main/resources/logback-spring-dev.xml
  backend/src/main/resources/logback-spring-prod.xml
  backend/src/main/resources/logback-spring.xml
  backend/src/main/resources/logback-variables.yml
Labels: 🔒 BE, ✨ Feature

#371 [BE] fix: test trace log 제거
  backend/src/main/resources/logback-spring.xml
Labels: 🔒 BE, 🐛 Bug

#183 [FE] chore: testing-library 및 jest 설정
  .github/workflows/test-fe.yml
  frontend/.eslintrc.js
  frontend/.gitignore
  frontend/.storybook/main.ts
  frontend/.storybook/preview.tsx
  frontend/__tests__/hooks/useStarRating.test.ts
  frontend/jest.config.js
  frontend/package.json
  frontend/tsconfig.json
  frontend/yarn.lock
Labels: 🔑 FE, 💻 Test, ⚙️ Chore

#365 [FE] fix: 상품 상세 페이지에서 무한스크롤 안되는 버그 수정
  frontend/src/components/Product/ProductList/ProductList.tsx
  frontend/src/hooks/useIntersectionObserver.ts
  frontend/src/mocks/handlers/reviewHandlers.ts
Labels: 🔑 FE, 🐛 Bug

#369 [FE] feat: 에러, 로딩 UI 추가
  frontend/src/components/Common/ErrorBoundary/ErrorBoundary.tsx
  frontend/src/components/Common/ErrorComponent/ErrorComponent.stories.tsx
  frontend/src/components/Common/ErrorComponent/ErrorComponent.tsx
  frontend/src/components/Common/Loading/Loading.stories.tsx
  frontend/src/components/Common/Loading/Loading.tsx
  frontend/src/pages/NotFoundPage.tsx
  frontend/src/router/index.tsx
Labels: 🔑 FE, ✨ Feature, 🎨 UI

#380 [FE] feat: Input 컴포넌트 추가
  frontend/.storybook/preview.tsx
  frontend/src/components/Common/Input/Input.stories.tsx
  frontend/src/components/Common/Input/Input.tsx
  frontend/src/components/Common/index.ts
  frontend/yarn.lock
Labels: 🔑 FE, ✨ Feature, 🎨 UI

#359 [FE] feat: 카테고리에 따른 태그 색상 변경
  frontend/src/components/Common/ScrollButton/ScrollButton.tsx
  frontend/src/components/Common/TagList/TagList.tsx
  frontend/src/components/Review/ReviewTagItem/ReviewTagItem.tsx
  frontend/src/components/Review/ReviewTagList/ReviewTagList.tsx
  frontend/src/mocks/data/productDetail.json
  frontend/src/mocks/data/productDetails.json
  frontend/src/types/common.ts
  frontend/src/utils/.gitkeep
  frontend/src/utils/convertTagColor.ts
Labels: 🔑 FE, ✨ Feature

#389 [FE] fix: 태그 저장 오류 해결
  frontend/src/components/Common/TagList/TagList.tsx
Labels: 🔑 FE, 🐛 Bug

#391 [FE] refactor: productTitle 이름 변경
  frontend/src/components/Common/SectionTitle/SectionTitle.stories.tsx
  frontend/src/components/Common/SectionTitle/SectionTitleTitle.tsx
  frontend/src/components/Common/index.ts
  frontend/src/components/Product/index.ts
  frontend/src/pages/ProductDetailPage.tsx
Labels: 🔑 FE, 🔧 Refactor

#384 [FE] refactor: 리액트 쿼리로 마이그레이션
  frontend/.storybook/main.ts
  frontend/.storybook/preview.tsx
  frontend/src/components/Common/CategoryMenu/CategoryMenu.stories.tsx
  frontend/src/components/Common/CategoryMenu/CategoryMenu.tsx
  frontend/src/components/Product/PBProductList/PBProductList.tsx
  frontend/src/components/Product/ProductDetailItem/ProductDetailItem.stories.tsx
  frontend/src/components/Product/ProductDetailItem/ProductDetailItem.tsx
  frontend/src/components/Product/ProductList/ProductList.tsx
  frontend/src/components/Product/ProductOverviewItem/ProductOverviewItem.tsx
  frontend/src/components/Rank/ProductRankingList/ProductRankingList.stories.tsx
  frontend/src/components/Rank/ProductRankingList/ProductRankingList.tsx
  frontend/src/components/Rank/ReviewRankingList/ReviewRankingList.stories.tsx
  frontend/src/components/Rank/ReviewRankingList/ReviewRankingList.tsx
  frontend/src/components/Review/ReviewList/ReviewList.tsx
  frontend/src/components/Review/ReviewRegisterForm/ReviewRegisterForm.stories.tsx
  frontend/src/components/Review/ReviewRegisterForm/ReviewRegisterForm.tsx
  frontend/src/components/Review/ReviewTagList/ReviewTagList.tsx
  frontend/src/hooks/auth/index.ts
  frontend/src/hooks/auth/useAuth.ts
  frontend/src/hooks/product/index.ts
  frontend/src/hooks/product/useCategory.ts
  frontend/src/hooks/product/useCategoryProducts.ts
  frontend/src/hooks/product/useProductDetail.ts
  frontend/src/hooks/product/useProductReview.ts
  frontend/src/hooks/queries/product/index.ts
  frontend/src/hooks/queries/product/useCategoryQuery.ts
  frontend/src/hooks/queries/product/useInfiniteProductReviewsQuery.ts
  frontend/src/hooks/queries/product/useInfiniteProductsQuery.ts
  frontend/src/hooks/queries/product/useProductDetailQuery.ts
  frontend/src/hooks/queries/rank/index.ts
  frontend/src/hooks/queries/rank/useProductRankingQuery.ts
  frontend/src/hooks/queries/rank/useReviewRankingQuery.ts
  frontend/src/hooks/queries/review/index.ts
  frontend/src/hooks/queries/review/useReviewRegisterFormMutation.ts
  frontend/src/hooks/queries/review/useReviewTagsQuery.ts
  frontend/src/hooks/rank/index.ts
  frontend/src/hooks/rank/useProductRanking.ts
  frontend/src/hooks/rank/useReviewRanking.ts
  frontend/src/hooks/review/index.ts
  frontend/src/hooks/review/useReviewFavorite.ts
  frontend/src/hooks/review/useReviewTags.ts
  frontend/src/hooks/useGet.ts
  frontend/src/hooks/useMutate.ts
  frontend/src/mocks/data/pbProducts.json
  frontend/src/mocks/data/productRankingList.json
  frontend/src/mocks/handlers/productHandlers.ts
  frontend/src/pages/HomePage.tsx
  frontend/src/pages/ProductDetailPage.tsx
  frontend/src/pages/ProductListPage.tsx
  frontend/src/utils/displaySlice.ts
Labels: 🔑 FE, 🔧 Refactor

#395 [BE] fix: 환경변수 관리 수정
  backend/src/main/resources/logback-spring-dev.xml
  backend/src/main/resources/logback-spring-prod.xml
  backend/src/main/resources/logback-variables.yml
Labels: 🔒 BE, 🐛 Bug

#396 [BE] feat: 모니터링 대시보드 추가
  backend/build.gradle
  backend/src/main/resources/application-dev.yml
  backend/src/main/resources/application-prod.yml
Labels: 🔒 BE, ✨ Feature

#398 [BE] fix: yml 에러 수정
  backend/src/main/resources/application-dev.yml
  backend/src/main/resources/application-prod.yml
Labels: 🔒 BE, 🐛 Bug

#401 [FE] refactor: 공통 hook들을 hooks/common으로 이동
  frontend/src/components/Common/ScrollButton/ScrollButton.tsx
  frontend/src/components/Common/SectionTitle/SectionTitleTitle.tsx
  frontend/src/components/Common/SortOptionList/SortOptionList.stories.tsx
  frontend/src/components/Product/ProductList/ProductList.tsx
  frontend/src/components/Review/RebuyCheckbox/RebuyCheckbox.tsx
  frontend/src/components/Review/ReviewImageUploader/ReviewImageUploader.tsx
  frontend/src/components/Review/ReviewItem/ReviewItem.tsx
  frontend/src/components/Review/ReviewList/ReviewList.tsx
  frontend/src/components/Review/ReviewRegisterForm/ReviewRegisterForm.tsx
  frontend/src/hooks/common/index.ts
  frontend/src/hooks/common/useDebounce.ts
  frontend/src/hooks/common/useEnterKeyDown.ts
  frontend/src/hooks/common/useIntersectionObserver.ts
  frontend/src/hooks/common/useRoutePage.ts
  frontend/src/hooks/common/useScroll.ts
  frontend/src/hooks/common/useSortOption.ts
  frontend/src/pages/LoginPage.tsx
  frontend/src/pages/ProductDetailPage.tsx
  frontend/src/pages/ProductListPage.tsx
Labels: 🔑 FE, 🔧 Refactor

#399 [FE] feat: pb 상품 더하기 버튼과 라우팅
  frontend/.storybook/preview-body.html
  frontend/src/components/Common/MoreButton/MoreButton.stories.tsx
  frontend/src/components/Common/MoreButton/MoreButton.tsx
  frontend/src/components/Common/Svg/SvgIcon.tsx
  frontend/src/components/Common/Svg/SvgSprite.tsx
  frontend/src/components/Common/index.ts
  frontend/src/components/Product/PBProductList/PBProductList.tsx
Labels: 🔑 FE, ✨ Feature, 🎨 UI

#364 [BE] feat: 꿀조합 상세 정보 조회 기능
  backend/src/main/java/com/funeat/member/domain/Member.java
  backend/src/main/java/com/funeat/member/domain/favorite/RecipeFavorite.java
  backend/src/main/java/com/funeat/member/persistence/RecipeFavoriteRepository.java
  backend/src/main/java/com/funeat/product/persistence/ProductRecipeRepository.java
  backend/src/main/java/com/funeat/product/presentation/ProductApiController.java
  backend/src/main/java/com/funeat/recipe/application/RecipeService.java
  backend/src/main/java/com/funeat/recipe/domain/Recipe.java
  backend/src/main/java/com/funeat/recipe/domain/RecipeImage.java
  backend/src/main/java/com/funeat/recipe/dto/ProductRecipeDto.java
  backend/src/main/java/com/funeat/recipe/dto/RecipeAuthorDto.java
  backend/src/main/java/com/funeat/recipe/dto/RecipeCreateRequest.java
  backend/src/main/java/com/funeat/recipe/dto/RecipeDetailResponse.java
  backend/src/main/java/com/funeat/recipe/persistence/RecipeImageRepository.java
  backend/src/main/java/com/funeat/recipe/presentation/RecipeApiController.java
  backend/src/main/java/com/funeat/recipe/presentation/RecipeController.java
  backend/src/test/java/com/funeat/acceptance/common/AcceptanceTest.java
  backend/src/test/java/com/funeat/acceptance/recipe/RecipeAcceptanceTest.java
  backend/src/test/java/com/funeat/acceptance/recipe/RecipeSteps.java
  backend/src/test/java/com/funeat/member/persistence/RecipeFavoriteRepositoryTest.java
  backend/src/test/java/com/funeat/product/persistence/ProductRecipeRepositoryTest.java
  backend/src/test/java/com/funeat/recipe/application/RecipeServiceTest.java
  backend/src/test/java/com/funeat/recipe/persistence/RecipeImageRepositoryTest.java
Labels: 🔒 BE, ✨ Feature

#411 [ALL] chore: 릴리즈 노트 워크플로우 작성
  .github/release-drafter.yml
  .github/workflows/release.yml
Labels: 🔑 FE

#386 [FE] feat: 검색 페이지 구현(상품)
  frontend/src/apis/index.ts
  frontend/src/components/Common/MarkedText/MarkedText.tsx
  frontend/src/components/Common/index.ts
  frontend/src/components/Review/ReviewItem/ReviewItem.tsx
  frontend/src/components/Search/RecommendList/RecommendList.tsx
  frontend/src/components/Search/SearchedList/SearchedList.tsx
  frontend/src/components/Search/index.ts
  frontend/src/hooks/common/index.ts
  frontend/src/hooks/common/useDebounce.ts
  frontend/src/hooks/common/useTimeout.ts
  frontend/src/hooks/queries/search/index.ts
  frontend/src/hooks/queries/search/useInfiniteSearchedProductsQuery.ts
  frontend/src/hooks/search/index.ts
  frontend/src/hooks/search/useSearch.ts
  frontend/src/mocks/browser.ts
  frontend/src/mocks/data/pbProducts.json
  frontend/src/mocks/data/searchedProducts.json
  frontend/src/mocks/handlers/index.ts
  frontend/src/mocks/handlers/searchHandlers.ts
  frontend/src/pages/SearchPage.tsx
  frontend/src/types/response.ts
  frontend/src/types/search.ts
Labels: 🔑 FE, ✨ Feature, 🎨 UI

#404 [FE] feat: 프로필 타이틀 컴포넌트 구현
  frontend/.storybook/preview-body.html
  frontend/src/components/Common/Svg/SvgIcon.tsx
  frontend/src/components/Common/Svg/SvgSprite.tsx
  frontend/src/components/Members/MembersTitle/MembersTitle.tsx
  frontend/src/components/Members/MembersTitle/MyPageTitle.stories.tsx
  frontend/src/components/Product/PBProductList/PBProductList.tsx
  frontend/src/mocks/data/members.json
  frontend/src/pages/ProfileModifyPage.tsx
  frontend/src/router/index.tsx
Labels: 🔑 FE, ✨ Feature, 🎨 UI

#409 [FE] feat: MemberTitle 컴포넌트 구현
  frontend/src/components/Memebers/MembersTitle/MembersTitle.stories.tsx
  frontend/src/components/Memebers/MembersTitle/MembersTitle.tsx
Labels: 🔑 FE, ✨ Feature, 🎨 UI

#387 [BE] feature: 전체 예외 처리, 로그 처리
  backend/build.gradle
  backend/src/main/java/com/funeat/auth/application/AuthService.java
  backend/src/main/java/com/funeat/auth/exception/AuthErrorCode.java
  backend/src/main/java/com/funeat/auth/exception/AuthException.java
  backend/src/main/java/com/funeat/auth/exception/LoginException.java
  backend/src/main/java/com/funeat/auth/util/AuthHandlerInterceptor.java
  backend/src/main/java/com/funeat/common/StringToCategoryTypeConverter.java
  backend/src/main/java/com/funeat/common/WebConfig.java
  backend/src/main/java/com/funeat/exception/CommonErrorCode.java
  backend/src/main/java/com/funeat/exception/ErrorCode.java
  backend/src/main/java/com/funeat/exception/GlobalException.java
  backend/src/main/java/com/funeat/exception/presentation/GlobalControllerAdvice.java
  backend/src/main/java/com/funeat/member/application/MemberService.java
  backend/src/main/java/com/funeat/member/dto/MemberRequest.java
  backend/src/main/java/com/funeat/member/exception/MemberErrorCode.java
  backend/src/main/java/com/funeat/member/exception/MemberException.java
  backend/src/main/java/com/funeat/member/presentation/MemberApiController.java
  backend/src/main/java/com/funeat/product/application/ProductService.java
  backend/src/main/java/com/funeat/product/domain/CategoryType.java
  backend/src/main/java/com/funeat/product/exception/CategoryErrorCode.java
  backend/src/main/java/com/funeat/product/exception/CategoryException.java
  backend/src/main/java/com/funeat/product/exception/ProductErrorCode.java
  backend/src/main/java/com/funeat/product/exception/ProductException.java
  backend/src/main/java/com/funeat/product/presentation/ProductApiController.java
  backend/src/main/java/com/funeat/recipe/application/RecipeService.java
  backend/src/main/java/com/funeat/recipe/dto/RecipeCreateRequest.java
  backend/src/main/java/com/funeat/recipe/exception/RecipeErrorCode.java
  backend/src/main/java/com/funeat/recipe/exception/RecipeException.java
  backend/src/main/java/com/funeat/recipe/presentation/RecipeApiController.java
  backend/src/main/java/com/funeat/recipe/util/RecipeHandlerInterceptor.java
  backend/src/main/java/com/funeat/review/application/ReviewService.java
  backend/src/main/java/com/funeat/review/exception/ReviewErrorCode.java
  backend/src/main/java/com/funeat/review/exception/ReviewException.java
  backend/src/main/java/com/funeat/review/presentation/ReviewApiController.java
  backend/src/main/java/com/funeat/review/presentation/dto/ReviewCreateRequest.java
  backend/src/main/java/com/funeat/review/presentation/dto/ReviewFavoriteRequest.java
  backend/src/test/java/com/funeat/acceptance/common/CommonSteps.java
  backend/src/test/java/com/funeat/acceptance/member/MemberAcceptanceTest.java
  backend/src/test/java/com/funeat/acceptance/product/CategoryAcceptanceTest.java
  backend/src/test/java/com/funeat/acceptance/product/CategorySteps.java
  backend/src/test/java/com/funeat/acceptance/product/ProductAcceptanceTest.java
  backend/src/test/java/com/funeat/acceptance/recipe/RecipeAcceptanceTest.java
  backend/src/test/java/com/funeat/acceptance/review/ReviewAcceptanceTest.java
  backend/src/test/java/com/funeat/member/application/MemberServiceTest.java
  backend/src/test/java/com/funeat/recipe/application/RecipeServiceTest.java
  backend/src/test/java/com/funeat/review/application/ReviewServiceTest.java
Labels: 🔒 BE, ✨ Feature, ⚙️ Chore

#428 [FE] feat: Input disabled 속성의 스타일 추가
  frontend/src/components/Common/Input/Input.stories.tsx
  frontend/src/components/Common/Input/Input.tsx
Labels: 🔑 FE, 🎨 UI

#422 [FE] feat: 상품 랭킹 클릭 시 해당 상품으로 라우팅 기능 추가
  frontend/src/components/Rank/ProductRankingList/ProductRankingList.tsx
  frontend/src/mocks/data/productRankingList.json
  frontend/src/types/ranking.ts
Labels: 🔑 FE, ✨ Feature

#403 [FE] feat: 꿀조합 전체 목록 페이지 구현(마크업)
  frontend/src/components/Common/ScrollButton/ScrollButton.tsx
  frontend/src/components/Layout/AuthLayout.tsx
  frontend/src/components/Layout/DefaultLayout.tsx
  frontend/src/components/Layout/DetailLayout.tsx
  frontend/src/components/Recipe/RecipeItem/RecipeItem.stories.tsx
  frontend/src/components/Recipe/RecipeItem/RecipeItem.tsx
  frontend/src/components/Recipe/RecipeList/RecipeList.stories.tsx
  frontend/src/components/Recipe/RecipeList/RecipeList.tsx
  frontend/src/components/Recipe/index.ts
  frontend/src/components/Review/ReviewItem/ReviewItem.tsx
  frontend/src/constants/index.ts
  frontend/src/mocks/data/recipes.json
  frontend/src/pages/ProductDetailPage.tsx
  frontend/src/pages/RecipePage.tsx
  frontend/src/types/recipe.ts
  frontend/src/types/response.ts
  frontend/src/utils/date.ts
Labels: 🔑 FE, 🎨 UI

#406 [FE] feat: 꿀조합 작성 페이지 구현
  frontend/.storybook/main.ts
  frontend/.storybook/preview.tsx
  frontend/src/apis/index.ts
  frontend/src/components/Common/ImageUploader/ImageUploader.stories.tsx
  frontend/src/components/Common/ImageUploader/ImageUploader.tsx
  frontend/src/components/Common/index.ts
  frontend/src/components/Recipe/RecipeDetailTextarea/RecipeDetailTextarea.stories.tsx
  frontend/src/components/Recipe/RecipeDetailTextarea/RecipeDetailTextarea.tsx
  frontend/src/components/Recipe/RecipeNameInput/RecipeNameInput.stories.tsx
  frontend/src/components/Recipe/RecipeNameInput/RecipeNameInput.tsx
  frontend/src/components/Recipe/RecipeRegisterForm/RecipeRegisterForm.stories.tsx
  frontend/src/components/Recipe/RecipeRegisterForm/RecipeRegisterForm.tsx
  frontend/src/components/Recipe/RecipeUsedProducts/RecipeUsedProducts.stories.tsx
  frontend/src/components/Recipe/RecipeUsedProducts/RecipeUsedProducts.tsx
  frontend/src/components/Recipe/index.ts
  frontend/src/components/Review/ReviewImageUploader/ReviewImageUploader.stories.tsx
  frontend/src/components/Review/ReviewImageUploader/ReviewImageUploader.tsx
  frontend/src/components/Review/ReviewRegisterForm/ReviewRegisterForm.stories.tsx
  frontend/src/components/Review/ReviewRegisterForm/ReviewRegisterForm.tsx
  frontend/src/components/Review/ReviewTagItem/ReviewTagItem.stories.tsx
  frontend/src/components/Review/ReviewTagList/ReviewTagList.stories.tsx
  frontend/src/components/Review/ReviewTextarea/ReviewTextarea.stories.tsx
  frontend/src/components/Review/StarRate/StarRate.stories.tsx
  frontend/src/contexts/RecipeFormContext.tsx
  frontend/src/hooks/common/index.ts
  frontend/src/hooks/common/useFormData.ts
  frontend/src/hooks/common/useImageUploader.ts
  frontend/src/hooks/context/index.ts
  frontend/src/hooks/context/useRecipeFormActionContext.ts
  frontend/src/hooks/context/useRecipeFormValueContext.ts
  frontend/src/hooks/queries/recipe/index.ts
  frontend/src/hooks/queries/recipe/useRecipeRegisterFormMutation.ts
  frontend/src/hooks/review/index.ts
  frontend/src/hooks/review/useFormData.ts
  frontend/src/mocks/browser.ts
  frontend/src/mocks/handlers/index.ts
  frontend/src/mocks/handlers/recipeHandlers.ts
  frontend/src/types/recipe.ts
Labels: 🔑 FE, ✨ Feature, 🎨 UI

#434 [FE] feat: 채널톡 구현
  frontend/src/pages/HomePage.tsx
  frontend/src/service/channelTalk.ts
Labels: 🔑 FE, ✨ Feature

#429 [FE] feat: 내가 작성한 리뷰 페이지 구현
  frontend/.storybook/preview-body.html
  frontend/src/components/Common/NavigableSectionTitle/NavigableSectionTitle.stories.tsx
  frontend/src/components/Common/NavigableSectionTitle/NavigableSectionTitle.tsx
  frontend/src/components/Common/SectionTitle/SectionTitle.stories.tsx
  frontend/src/components/Common/SectionTitle/SectionTitle.tsx
  frontend/src/components/Common/Svg/SvgIcon.tsx
  frontend/src/components/Common/Svg/SvgSprite.tsx
  frontend/src/components/Common/index.ts
  frontend/src/components/Members/MemberReviewList/MemberReviewList.stories.tsx
  frontend/src/components/Members/MemberReviewList/MemberReviewList.tsx
  frontend/src/components/Members/MembersInfo/MembersInfo.tsx
  frontend/src/components/Members/MembersInfo/MyPageInfo.stories.tsx
  frontend/src/components/Members/MembersTitle/MyPageTitle.stories.tsx
  frontend/src/components/Members/index.ts
  frontend/src/components/Memebers/MembersTitle/MembersTitle.stories.tsx
  frontend/src/components/Product/PBProductList/PBProductList.tsx
  frontend/src/components/Product/ProductList/ProductList.tsx
  frontend/src/components/Rank/ProductRankingList/ProductRankingList.tsx
  frontend/src/components/Rank/ReviewRankingList/ReviewRankingList.tsx
  frontend/src/constants/index.ts
  frontend/src/constants/path.ts
  frontend/src/hooks/queries/members/index.ts
  frontend/src/hooks/queries/members/useInfiniteMemberReviewQuery.ts
  frontend/src/mocks/data/profileReviews.json
  frontend/src/mocks/handlers/loginHandlers.ts
  frontend/src/mocks/handlers/memberHandlers.ts
  frontend/src/pages/HomePage.tsx
  frontend/src/pages/MemberModifyPage.tsx
  frontend/src/pages/MemberPage.tsx
  frontend/src/pages/MemberRecipePage.tsx
  frontend/src/pages/MemberReviewPage.tsx
  frontend/src/pages/ProfileModifyPage.tsx
  frontend/src/pages/ProfilePage.tsx
  frontend/src/router/index.tsx
  frontend/src/types/response.ts
Labels: 🔑 FE, ✨ Feature, 🎨 UI

#417 [BE] feat: Recipe에 생성 시간 추가
  backend/src/main/java/com/funeat/recipe/domain/Recipe.java
  backend/src/main/java/com/funeat/recipe/dto/RecipeAuthorDto.java
  backend/src/main/java/com/funeat/recipe/dto/RecipeDetailResponse.java
  backend/src/test/java/com/funeat/recipe/application/RecipeServiceTest.java
Labels: 🔒 BE, 🔧 Refactor

#419 [BE] refactor: 상품 상세 정보 조회 시 Response에 리뷰 개수 추가
  backend/src/main/java/com/funeat/product/application/ProductService.java
  backend/src/main/java/com/funeat/product/dto/ProductResponse.java
  backend/src/test/java/com/funeat/acceptance/product/ProductAcceptanceTest.java
Labels: 🔒 BE, ✨ Feature, 🔧 Refactor

#421 [BE] refactor: 상품 랭킹 조회 시 Response에 카테고리 타입 추가
  backend/src/main/java/com/funeat/product/domain/CategoryType.java
  backend/src/main/java/com/funeat/product/dto/RankingProductDto.java
Labels: 🔒 BE, ✨ Feature, 🔧 Refactor

#437 [BE] refactor: 신규 회원 리다이렉트 주소 변경
  backend/src/main/java/com/funeat/auth/presentation/AuthApiController.java
  backend/src/test/java/com/funeat/acceptance/auth/AuthAcceptanceTest.java
Labels: 🔒 BE, 🔧 Refactor

#420 [FE] feat: 꿀조합 상세 페이지 추가
  frontend/.storybook/main.ts
  frontend/src/components/Common/SectionTitle/SectionTitle.tsx
  frontend/src/components/Recipe/RecipeRegisterForm/RecipeRegisterForm.tsx
  frontend/src/components/Recipe/RecipeUsedProducts/RecipeUsedProducts.tsx
  frontend/src/hooks/queries/recipe/index.ts
  frontend/src/hooks/queries/recipe/useRecipeDetailQuery.ts
  frontend/src/mocks/data/recipeDetail.json
  frontend/src/mocks/handlers/recipeHandlers.ts
  frontend/src/pages/RecipeDetailPage.tsx
  frontend/src/router/index.tsx
  frontend/src/types/recipe.ts
Labels: 🔑 FE, ✨ Feature, 🎨 UI

#439 [FE] fix: 상품 리스트 정렬 에러 수정
  frontend/src/components/Product/ProductList/ProductList.tsx
  frontend/src/pages/ProductListPage.tsx
Labels: 🔑 FE, 🐛 Bug

#435 [BE] feat: 사용자 마이페이지 꿀조합 조회 기능 구현
  backend/src/main/java/com/funeat/common/dto/PageDto.java
  backend/src/main/java/com/funeat/member/dto/MemberRecipeDto.java
  backend/src/main/java/com/funeat/member/dto/MemberRecipesResponse.java
  backend/src/main/java/com/funeat/member/dto/MemberReviewsResponse.java
  backend/src/main/java/com/funeat/member/presentation/MemberApiController.java
  backend/src/main/java/com/funeat/member/presentation/MemberController.java
  backend/src/main/java/com/funeat/product/application/ProductService.java
  backend/src/main/java/com/funeat/product/dto/ProductResponse.java
  backend/src/main/java/com/funeat/product/dto/ProductsInCategoryPageDto.java
  backend/src/main/java/com/funeat/product/dto/ProductsInCategoryResponse.java
  backend/src/main/java/com/funeat/recipe/application/RecipeService.java
  backend/src/main/java/com/funeat/recipe/dto/RecipeDetailResponse.java
  backend/src/main/java/com/funeat/recipe/persistence/RecipeRepository.java
  backend/src/main/java/com/funeat/review/application/ReviewService.java
  backend/src/main/java/com/funeat/review/presentation/dto/SortingReviewsResponse.java
  backend/src/test/java/com/funeat/acceptance/common/AcceptanceTest.java
  backend/src/test/java/com/funeat/acceptance/member/MemberAcceptanceTest.java
  backend/src/test/java/com/funeat/acceptance/member/MemberSteps.java
  backend/src/test/java/com/funeat/acceptance/product/ProductAcceptanceTest.java
  backend/src/test/java/com/funeat/acceptance/review/ReviewAcceptanceTest.java
  backend/src/test/java/com/funeat/common/ServiceTest.java
  backend/src/test/java/com/funeat/recipe/application/RecipeServiceTest.java
  backend/src/test/java/com/funeat/review/application/ReviewServiceTest.java
Labels: 🔒 BE, ✨ Feature

#449 [FE] feat: 꿀조합 전체 목록 조회 요청 쿼리 추가
  frontend/src/components/Recipe/RecipeList/RecipeList.tsx
  frontend/src/hooks/queries/recipe/index.ts
  frontend/src/hooks/queries/recipe/useInfiniteRecipesQuery.ts
  frontend/src/mocks/handlers/recipeHandlers.ts
  frontend/src/mocks/handlers/reviewHandlers.ts
  frontend/src/mocks/handlers/utils.ts
  frontend/src/pages/RecipePage.tsx
  frontend/src/types/common.ts
Labels: 🔑 FE, ✨ Feature

#447 [FE] feat: 상품 검색 자동완성 쿼리 추가
  frontend/src/components/Search/RecommendList/RecommendList.tsx
  frontend/src/components/Search/SearchResultList/SearchResultList.tsx
  frontend/src/components/Search/index.ts
  frontend/src/hooks/queries/search/index.ts
  frontend/src/hooks/queries/search/useInfiniteProductSearchAutocompleteQuery.ts
  frontend/src/hooks/queries/search/useInfiniteProductSearchResultsQuery.ts
  frontend/src/hooks/queries/search/useInfiniteSearchedProductsQuery.ts
  frontend/src/mocks/data/productSearchResults.json
  frontend/src/mocks/data/searchingProducts.json
  frontend/src/mocks/handlers/searchHandlers.ts
  frontend/src/pages/SearchPage.tsx
  frontend/src/types/response.ts
  frontend/src/types/search.ts
Labels: 🔑 FE, ✨ Feature

#443 [FE] feat: useSuspendedQuery, useSuspendedInfiniteQuery 추가
  frontend/.eslintrc.js
  frontend/src/components/Common/CategoryMenu/CategoryMenu.tsx
  frontend/src/components/Members/MemberReviewList/MemberReviewList.tsx
  frontend/src/components/Product/PBProductList/PBProductList.tsx
  frontend/src/components/Product/ProductDetailItem/ProductDetailItem.tsx
  frontend/src/components/Product/ProductItem/ProductItem.tsx
  frontend/src/components/Product/ProductList/ProductList.tsx
  frontend/src/components/Product/ProductOverviewItem/ProductOverviewItem.tsx
  frontend/src/components/Rank/ProductRankingList/ProductRankingList.tsx
  frontend/src/components/Rank/ReviewRankingList/ReviewRankingList.tsx
  frontend/src/components/Recipe/RecipeList/RecipeList.tsx
  frontend/src/components/Review/ReviewList/ReviewList.tsx
  frontend/src/components/Review/ReviewRegisterForm/ReviewRegisterForm.tsx
  frontend/src/components/Review/ReviewTagList/ReviewTagList.tsx
  frontend/src/components/Search/RecommendList/RecommendList.tsx
  frontend/src/components/Search/SearchResultList/SearchResultList.tsx
  frontend/src/hooks/queries/index.ts
  frontend/src/hooks/queries/members/useInfiniteMemberReviewQuery.ts
  frontend/src/hooks/queries/product/useCategoryQuery.ts
  frontend/src/hooks/queries/product/useInfiniteProductReviewsQuery.ts
  frontend/src/hooks/queries/product/useInfiniteProductsQuery.ts
  frontend/src/hooks/queries/product/useProductDetailQuery.ts
  frontend/src/hooks/queries/rank/useProductRankingQuery.ts
  frontend/src/hooks/queries/rank/useReviewRankingQuery.ts
  frontend/src/hooks/queries/recipe/useInfiniteRecipesQuery.ts
  frontend/src/hooks/queries/recipe/useRecipeDetailQuery.ts
  frontend/src/hooks/queries/review/useReviewTagsQuery.ts
  frontend/src/hooks/queries/search/useInfiniteProductSearchAutocompleteQuery.ts
  frontend/src/hooks/queries/search/useInfiniteProductSearchResultsQuery.ts
  frontend/src/hooks/queries/useSuspendedInfiniteQuery.ts
  frontend/src/hooks/queries/useSuspendedQuery.ts
  frontend/src/mocks/handlers/reviewHandlers.ts
  frontend/src/pages/ProductDetailPage.tsx
  frontend/src/pages/RecipeDetailPage.tsx
Labels: 🔑 FE, ✨ Feature, 🔧 Refactor

#451 [FE] feat: 프로필 수정 기능 추가
  frontend/.storybook/preview-body.html
  frontend/src/apis/ApiClient.ts
  frontend/src/components/Common/Svg/SvgIcon.tsx
  frontend/src/components/Common/Svg/SvgSprite.tsx
  frontend/src/hooks/queries/members/index.ts
  frontend/src/hooks/queries/members/useMemberModifyMutation.ts
  frontend/src/mocks/handlers/memberHandlers.ts
  frontend/src/pages/MemberModifyPage.tsx
  frontend/src/types/member.ts
Labels: 🔑 FE, ✨ Feature, 🎨 UI

#440 [FE] feat: 내가 작성한 꿀조합 페이지 구현
  frontend/src/components/Members/MemberRecipeList/MemberRecipeList.stories.tsx
  frontend/src/components/Members/MemberRecipeList/MemberRecipeList.tsx
  frontend/src/components/Members/MemberReviewList/MemberReviewList.stories.tsx
  frontend/src/components/Members/MemberReviewList/MemberReviewList.tsx
  frontend/src/components/Members/index.ts
  frontend/src/components/Recipe/RecipeItem/RecipeItem.tsx
  frontend/src/hooks/queries/members/index.ts
  frontend/src/hooks/queries/members/useInfiniteMemberRecipeQuery.ts
  frontend/src/hooks/queries/members/useInfiniteMemberReviewQuery.ts
  frontend/src/mocks/data/memberRecipes.json
  frontend/src/mocks/data/memberReviews.json
  frontend/src/mocks/handlers/memberHandlers.ts
  frontend/src/pages/MemberPage.tsx
  frontend/src/pages/MemberRecipePage.tsx
  frontend/src/types/recipe.ts
  frontend/src/types/response.ts
Labels: 🔑 FE, ✨ Feature, 🎨 UI

#445 [BE] feat: 상품 검색 기능 구현
  backend/src/main/java/com/funeat/product/application/ProductService.java
  backend/src/main/java/com/funeat/product/dto/SearchProductDto.java
  backend/src/main/java/com/funeat/product/dto/SearchProductResultDto.java
  backend/src/main/java/com/funeat/product/dto/SearchProductResultsResponse.java
  backend/src/main/java/com/funeat/product/dto/SearchProductsResponse.java
  backend/src/main/java/com/funeat/product/persistence/ProductRepository.java
  backend/src/main/java/com/funeat/product/presentation/ProductApiController.java
  backend/src/main/java/com/funeat/product/presentation/ProductController.java
  backend/src/test/java/com/funeat/acceptance/product/ProductAcceptanceTest.java
  backend/src/test/java/com/funeat/acceptance/product/ProductSteps.java
  backend/src/test/java/com/funeat/fixture/ProductFixture.java
  backend/src/test/java/com/funeat/product/persistence/ProductRepositoryTest.java
Labels: 🔒 BE, ✨ Feature

#460 [BE] refactor: 마이페이지 꿀조합 조회 api 명세 조회 수정
  backend/src/main/java/com/funeat/member/dto/MemberRecipeDto.java
  backend/src/main/java/com/funeat/member/dto/MemberRecipeProductDto.java
  backend/src/main/java/com/funeat/recipe/application/RecipeService.java
  backend/src/test/java/com/funeat/acceptance/member/MemberAcceptanceTest.java
  backend/src/test/java/com/funeat/recipe/application/RecipeServiceTest.java
Labels: 🔒 BE, 🔧 Refactor

#462 [BE] fix: DEV, PROD, LOCAL 카카오 로그인 환경변수 분리
  backend/src/main/resources/application-dev.yml
  backend/src/main/resources/application-local.yml
  backend/src/main/resources/application-prod.yml
  backend/src/main/resources/application.yml
Labels: 🔒 BE, 🐛 Bug

#446 [FE] feat: 꿀조합 작성 폼에 사용된 상품 추가하는 기능 구현
  frontend/.storybook/preview.tsx
  frontend/src/components/Recipe/RecipeRegisterForm/RecipeRegisterForm.tsx
  frontend/src/components/Recipe/RecipeUsedProducts/RecipeUsedProducts.tsx
  frontend/src/components/Recipe/RecipeUsedProducts/SearchedProductList.tsx
  frontend/src/components/Recipe/index.ts
  frontend/src/constants/path.ts
  frontend/src/contexts/RecipeFormContext.tsx
  frontend/src/pages/RecipePage.tsx
Labels: 🔑 FE, ✨ Feature

#454 [BE] feat: 꿀조합 좋아요 기능 구현
  backend/src/main/java/com/funeat/common/WebConfig.java
  backend/src/main/java/com/funeat/member/domain/favorite/RecipeFavorite.java
  backend/src/main/java/com/funeat/member/persistence/RecipeFavoriteRepository.java
  backend/src/main/java/com/funeat/recipe/application/RecipeService.java
  backend/src/main/java/com/funeat/recipe/domain/Recipe.java
  backend/src/main/java/com/funeat/recipe/dto/RecipeFavoriteRequest.java
  backend/src/main/java/com/funeat/recipe/presentation/RecipeApiController.java
  backend/src/main/java/com/funeat/recipe/presentation/RecipeController.java
  backend/src/test/java/com/funeat/acceptance/common/AcceptanceTest.java
  backend/src/test/java/com/funeat/acceptance/recipe/RecipeAcceptanceTest.java
  backend/src/test/java/com/funeat/acceptance/recipe/RecipeSteps.java
  backend/src/test/java/com/funeat/common/RepositoryTest.java
  backend/src/test/java/com/funeat/fixture/ImageFixture.java
  backend/src/test/java/com/funeat/fixture/RecipeFixture.java
  backend/src/test/java/com/funeat/member/domain/favorite/RecipeFavoriteTest.java
  backend/src/test/java/com/funeat/member/persistence/RecipeFavoriteRepositoryTest.java
  backend/src/test/java/com/funeat/recipe/application/RecipeServiceTest.java
Labels: 🔒 BE, ✨ Feature

#466 [FE] feat: favicon, open-graph 설정
  frontend/public/assets/apple-icon-180x180.png
  frontend/public/assets/favicon-16x16.png
  frontend/public/assets/favicon-32x32.png
  frontend/public/assets/favicon.ico
  frontend/public/assets/og-image.png
  frontend/public/index.html
  frontend/public/manifest.json
Labels: 🔑 FE, ✨ Feature

#456 [FE] feat: 꿀조합 검색 기능 구현
  frontend/src/components/Common/TabMenu/TabMenu.tsx
  frontend/src/components/Common/index.ts
  frontend/src/components/Search/ProductSearchResultList/ProductSearchResultList.tsx
  frontend/src/components/Search/RecipeSearchResultList/RecipeSearchResultList.tsx
  frontend/src/components/Search/index.ts
  frontend/src/constants/index.ts
  frontend/src/hooks/queries/search/index.ts
  frontend/src/hooks/queries/search/useInfiniteRecipeSearchResultsQuery.ts
  frontend/src/mocks/data/recipes.json
  frontend/src/mocks/handlers/searchHandlers.ts
  frontend/src/pages/ProductDetailPage.tsx
  frontend/src/pages/RecipePage.tsx
  frontend/src/pages/SearchPage.tsx
Labels: 🔑 FE, ✨ Feature, 🎨 UI

#475 [FE] feat: 상품 상세에서 전체 리뷰 수 추가
  frontend/.nvmrc
  frontend/src/components/Product/ProductDetailItem/ProductDetailItem.stories.tsx
  frontend/src/components/Product/ProductDetailItem/ProductDetailItem.tsx
  frontend/src/mocks/data/productDetail.json
  frontend/src/mocks/data/productDetails.json
  frontend/src/pages/ProductDetailPage.tsx
  frontend/src/types/product.ts
Labels: 🔑 FE, 🔧 Refactor

#484 [FE] refactor: 꿀조합 작성 후 리다이렉트 경로 수정
  frontend/src/hooks/queries/recipe/useRecipeRegisterFormMutation.ts
Labels: 🔑 FE, 🔧 Refactor

#471 [BE] refactor: 내 정보 수정 로직 수정
  backend/src/main/java/com/funeat/common/ImageService.java
  backend/src/main/java/com/funeat/common/ImageUploader.java
  backend/src/main/java/com/funeat/member/application/MemberService.java
  backend/src/main/java/com/funeat/member/domain/Member.java
  backend/src/main/java/com/funeat/member/dto/MemberRequest.java
  backend/src/main/java/com/funeat/member/exception/MemberErrorCode.java
  backend/src/main/java/com/funeat/member/exception/MemberException.java
  backend/src/main/java/com/funeat/member/presentation/MemberApiController.java
  backend/src/main/java/com/funeat/member/presentation/MemberController.java
  backend/src/main/java/com/funeat/recipe/application/RecipeService.java
  backend/src/main/java/com/funeat/review/application/ReviewService.java
  backend/src/test/java/com/funeat/acceptance/common/CommonSteps.java
  backend/src/test/java/com/funeat/acceptance/member/MemberAcceptanceTest.java
  backend/src/test/java/com/funeat/acceptance/member/MemberSteps.java
  backend/src/test/java/com/funeat/acceptance/product/ProductAcceptanceTest.java
  backend/src/test/java/com/funeat/acceptance/recipe/RecipeAcceptanceTest.java
  backend/src/test/java/com/funeat/acceptance/recipe/RecipeSteps.java
  backend/src/test/java/com/funeat/acceptance/review/ReviewAcceptanceTest.java
  backend/src/test/java/com/funeat/acceptance/review/ReviewSteps.java
  backend/src/test/java/com/funeat/common/TestImageUploader.java
  backend/src/test/java/com/funeat/member/application/MemberServiceTest.java
  backend/src/test/java/com/funeat/member/application/TestMemberService.java
  backend/src/test/java/com/funeat/member/domain/MemberTest.java
Labels: 🔒 BE, 🔧 Refactor

#472 [BE] refactor: 카카오 로그아웃 기능 수정
  backend/src/main/java/com/funeat/auth/application/AuthService.java
  backend/src/main/java/com/funeat/auth/presentation/AuthApiController.java
  backend/src/main/java/com/funeat/auth/presentation/AuthController.java
  backend/src/main/java/com/funeat/auth/util/AuthArgumentResolver.java
  backend/src/main/java/com/funeat/auth/util/KakaoPlatformUserProvider.java
  backend/src/main/java/com/funeat/auth/util/PlatformUserProvider.java
  backend/src/main/java/com/funeat/common/WebConfig.java
  backend/src/main/java/com/funeat/member/application/MemberService.java
  backend/src/main/resources/application-dev.yml
  backend/src/main/resources/application-local.yml
  backend/src/main/resources/application-prod.yml
  backend/src/test/java/com/funeat/acceptance/auth/AuthAcceptanceTest.java
  backend/src/test/java/com/funeat/acceptance/auth/LoginSteps.java
  backend/src/test/java/com/funeat/acceptance/common/TestPlatformUserProvider.java
  backend/src/test/java/com/funeat/auth/application/AuthServiceTest.java
  backend/src/test/java/com/funeat/member/application/MemberServiceTest.java
Labels: 🔒 BE, 🔧 Refactor

#481 [FE] refactor: 검색 페이지 이슈 수정
  frontend/src/components/Search/RecommendList/RecommendList.tsx
  frontend/src/hooks/search/useSearch.ts
  frontend/src/pages/SearchPage.tsx
Labels: 🔑 FE, 🔧 Refactor

#490 fix: 이미지 오류 수정
  frontend/src/components/Recipe/RecipeItem/RecipeItem.tsx
  frontend/src/hooks/common/useFormData.ts
  frontend/src/pages/RecipeDetailPage.tsx
Labels: 🔑 FE, 🐛 Bug

#492 [FE] feat: options에 fileType: image/png 추가
  frontend/src/hooks/common/useFormData.ts
  frontend/src/hooks/common/useImageUploader.ts
Labels: 🔑 FE, 🔧 Refactor

#494 [BE] fix: request -> memberRequest
  backend/src/main/java/com/funeat/member/presentation/MemberApiController.java
  backend/src/test/java/com/funeat/acceptance/member/MemberSteps.java
Labels: 🔒 BE

#474 [BE] fix: 리뷰, 레시피 좋아요 데드락, 동시성 이슈 수정
  backend/src/main/java/com/funeat/member/domain/favorite/RecipeFavorite.java
  backend/src/main/java/com/funeat/member/domain/favorite/ReviewFavorite.java
  backend/src/main/java/com/funeat/member/exception/MemberErrorCode.java
  backend/src/main/java/com/funeat/member/exception/MemberException.java
  backend/src/main/java/com/funeat/recipe/application/RecipeService.java
  backend/src/main/java/com/funeat/recipe/persistence/RecipeRepository.java
  backend/src/main/java/com/funeat/review/application/ReviewService.java
  backend/src/main/java/com/funeat/review/persistence/ReviewRepository.java
Labels: 🔒 BE, 🐛 Bug

#489 [FE] feat: 로그아웃 기능 구현
  frontend/src/apis/index.ts
  frontend/src/components/Members/MembersInfo/MembersInfo.tsx
  frontend/src/hooks/queries/members/index.ts
  frontend/src/hooks/queries/members/useLogoutMutation.ts
  frontend/src/mocks/browser.ts
  frontend/src/mocks/handlers/index.ts
  frontend/src/mocks/handlers/logoutHandlers.ts
Labels: 🔑 FE, ✨ Feature

#497 [FE] feat: invalidateQueries 추가
  frontend/src/hooks/queries/members/useMemberModifyMutation.ts
Labels: 🔑 FE, ✨ Feature

#477 [BE] feat: 꿀조합 검색 기능 구현
  backend/src/main/java/com/funeat/recipe/application/RecipeService.java
  backend/src/main/java/com/funeat/recipe/dto/SearchRecipeResultDto.java
  backend/src/main/java/com/funeat/recipe/dto/SearchRecipeResultsResponse.java
  backend/src/main/java/com/funeat/recipe/persistence/RecipeRepository.java
  backend/src/main/java/com/funeat/recipe/presentation/RecipeApiController.java
  backend/src/main/java/com/funeat/recipe/presentation/RecipeController.java
  backend/src/test/java/com/funeat/acceptance/recipe/RecipeAcceptanceTest.java
  backend/src/test/java/com/funeat/acceptance/recipe/RecipeSteps.java
  backend/src/test/java/com/funeat/recipe/persistence/RecipeRepositoryTest.java
Labels: 🔒 BE, ✨ Feature

#502 [FE] refactor: Member 새로고침과 경로 수정
  frontend/src/hooks/queries/members/useLogoutMutation.ts
Labels: 🔑 FE, 🔧 Refactor

#485 [FE] feat: 상품 상세 페이지 꿀조합 탭 구현
  frontend/src/components/Product/ProductRecipeList/ProductRecipeList.tsx
  frontend/src/components/Product/index.ts
  frontend/src/hooks/queries/product/index.ts
  frontend/src/hooks/queries/product/useInfiniteProductRecipesQuery.ts
  frontend/src/mocks/handlers/recipeHandlers.ts
  frontend/src/mocks/handlers/reviewHandlers.ts
  frontend/src/pages/ProductDetailPage.tsx
  frontend/src/types/common.ts
Labels: 🔑 FE, ✨ Feature, 🎨 UI

#478 [FE] feat: 꿀조합 랭킹 컴포넌트 추가
  frontend/src/components/Common/Carousel/Carousel.stories.tsx
  frontend/src/components/Common/Carousel/Carousel.tsx
  frontend/src/components/Common/index.ts
  frontend/src/components/Rank/RecipeRankingItem/RecipeRankingItem.stories.tsx
  frontend/src/components/Rank/RecipeRankingItem/RecipeRankingItem.tsx
  frontend/src/components/Rank/RecipeRankingList/RecipeRankingList.stories.tsx
  frontend/src/components/Rank/RecipeRankingList/RecipeRankingList.tsx
  frontend/src/components/Rank/index.ts
  frontend/src/mocks/data/recipeRankingList.json
  frontend/src/pages/HomePage.tsx
  frontend/src/types/common.ts
  frontend/src/types/ranking.ts
Labels: 🔑 FE, ✨ Feature, 🎨 UI

#488 [BE] feat: 꿀조합 랭킹 기능 구현
  backend/src/main/java/com/funeat/recipe/application/RecipeService.java
  backend/src/main/java/com/funeat/recipe/dto/RankingRecipeDto.java
  backend/src/main/java/com/funeat/recipe/dto/RankingRecipesResponse.java
  backend/src/main/java/com/funeat/recipe/persistence/RecipeRepository.java
  backend/src/main/java/com/funeat/recipe/presentation/RecipeApiController.java
  backend/src/main/java/com/funeat/recipe/presentation/RecipeController.java
  backend/src/test/java/com/funeat/acceptance/recipe/RecipeAcceptanceTest.java
  backend/src/test/java/com/funeat/acceptance/recipe/RecipeSteps.java
  backend/src/test/java/com/funeat/recipe/persistence/RecipeRepositoryTest.java
Labels: 🔒 BE, ✨ Feature

#503 [FE] feat: 하트 색 살리기와 실패 시에도 폼 비우기
  frontend/src/components/Recipe/RecipeItem/RecipeItem.tsx
  frontend/src/components/Recipe/RecipeRegisterForm/RecipeRegisterForm.tsx
  frontend/src/components/Review/ReviewRegisterForm/ReviewRegisterForm.tsx
Labels: 🔑 FE, 🔧 Refactor

#495 [BE] feat: 특정 상품의 꿀조합 목록 조회 기능 구현
  backend/src/main/java/com/funeat/product/application/ProductService.java
  backend/src/main/java/com/funeat/product/presentation/ProductApiController.java
  backend/src/main/java/com/funeat/product/presentation/ProductController.java
  backend/src/main/java/com/funeat/recipe/persistence/RecipeRepository.java
  backend/src/test/java/com/funeat/acceptance/product/ProductAcceptanceTest.java
  backend/src/test/java/com/funeat/acceptance/product/ProductSteps.java
  backend/src/test/java/com/funeat/product/persistence/ProductRecipeRepositoryTest.java
  backend/src/test/java/com/funeat/recipe/persistence/RecipeRepositoryTest.java
Labels: 🔒 BE, ✨ Feature

#513 [FE] fix: 로그아웃 멤버 초기화 수정
  frontend/src/components/Layout/AuthLayout.tsx
  frontend/src/components/Members/MembersInfo/MembersInfo.tsx
  frontend/src/hooks/queries/members/useMemberQuery.ts
  frontend/src/hooks/queries/useSuspendedQuery.ts
  frontend/src/mocks/handlers/logoutHandlers.ts
  frontend/src/mocks/handlers/memberHandlers.ts
  frontend/src/pages/MemberModifyPage.tsx
Labels: 🔑 FE, 🐛 Bug

#507 [FE] refactor: 이미지 없을 때 처리 및 꿀조합 아이템 스타일 수정
  frontend/src/assets/plate.svg
  frontend/src/components/Members/MembersInfo/MembersInfo.tsx
  frontend/src/components/Product/PBProductItem/PBProductItem.tsx
  frontend/src/components/Product/ProductDetailItem/ProductDetailItem.tsx
  frontend/src/components/Product/ProductItem/ProductItem.tsx
  frontend/src/components/Rank/RecipeRankingItem/RecipeRankingItem.tsx
  frontend/src/components/Recipe/RecipeItem/RecipeItem.tsx
  frontend/src/components/Review/ReviewItem/ReviewItem.tsx
  frontend/src/constants/index.ts
  frontend/src/constants/path.ts
  frontend/src/mocks/data/recipeDetail.json
  frontend/src/mocks/data/recipes.json
  frontend/src/pages/ProductDetailPage.tsx
  frontend/src/pages/RecipeDetailPage.tsx
  frontend/src/types/product.ts
  frontend/src/types/ranking.ts
  frontend/src/types/recipe.ts
Labels: 🔑 FE, 🔧 Refactor

#499 [BE] feat: 이미지가 존재하는 리뷰중에 가장 많은 좋아요를 받은 리뷰 이미지로 상품 이미지 변경 기능 추가
  backend/src/main/java/com/funeat/product/domain/Product.java
  backend/src/main/java/com/funeat/review/application/ReviewService.java
  backend/src/main/java/com/funeat/review/domain/Review.java
  backend/src/main/java/com/funeat/review/persistence/ReviewRepository.java
  backend/src/main/java/com/funeat/review/presentation/ReviewApiController.java
  backend/src/test/java/com/funeat/acceptance/common/CommonSteps.java
  backend/src/test/java/com/funeat/acceptance/review/ReviewAcceptanceTest.java
  backend/src/test/java/com/funeat/fixture/ReviewFixture.java
  backend/src/test/java/com/funeat/review/application/ReviewServiceTest.java
  backend/src/test/java/com/funeat/review/persistence/ReviewRepositoryTest.java
Labels: 🔒 BE, ✨ Feature

#518 [FE] refactor: invalidateQueries를 removeQueries로 수정
  frontend/src/hooks/queries/members/useLogoutMutation.ts
Labels: 🔑 FE, 🐛 Bug

#504 [FE] feat: 꿀조합 랭킹 api 연결
  frontend/src/components/Rank/RecipeRankingList/RecipeRankingList.tsx
  frontend/src/hooks/queries/rank/index.ts
  frontend/src/hooks/queries/rank/useRecipeRankingQuery.ts
  frontend/src/mocks/handlers/rankingHandlers.ts
  frontend/src/pages/HomePage.tsx
  frontend/src/types/response.ts
Labels: 🔑 FE, ✨ Feature

#508 [FE] feat: 꿀조합 사용된 상품명 길이가 길 때 디자인 대응
  frontend/src/components/Recipe/RecipeUsedProducts/RecipeUsedProducts.tsx
Labels: 🔑 FE, 🎨 UI

#512 [FE] fix: 라우팅 에러 수정
  frontend/src/components/Product/ProductRecipeList/ProductRecipeList.tsx
Labels: 🔑 FE, 🐛 Bug

#514 [BE] fix: 꿀조합 검색 시 중복 검색되는 버그 해결
  backend/src/main/java/com/funeat/recipe/persistence/RecipeRepository.java
  backend/src/test/java/com/funeat/acceptance/recipe/RecipeAcceptanceTest.java
Labels: 🔒 BE, 🐛 Bug

#517 [FE] refactor: 꿀조합 버튼 변경
  frontend/src/components/Common/ScrollButton/ScrollButton.tsx
  frontend/src/pages/RecipePage.tsx
Labels: 🔑 FE, 🔧 Refactor

#522 [BE] refactor: 꿀조합 랭킹 Response 변경
  backend/src/main/java/com/funeat/recipe/dto/RankingRecipeDto.java
Labels: 🔒 BE, 🔧 Refactor

#519 [FE] feat: 마이페이지 - 리뷰/꿀조합 없을 때 처리
  frontend/src/components/Common/Carousel/Carousel.tsx
  frontend/src/components/Members/MemberRecipeList/MemberRecipeList.tsx
  frontend/src/components/Members/MemberReviewList/MemberReviewList.tsx
  frontend/src/components/Product/ProductRecipeList/ProductRecipeList.tsx
  frontend/src/components/Rank/RecipeRankingItem/RecipeRankingItem.tsx
Labels: 🔑 FE, ✨ Feature

#526 [FE] refactor: 이미지 경로 및 스타일 수정
  frontend/src/components/Common/RegisterButton/RegisterButton.tsx
  frontend/src/components/Layout/DefaultLayout.tsx
  frontend/src/components/Layout/HeaderOnlyLayout.tsx
  frontend/src/components/Layout/MinimalLayout.tsx
  frontend/src/components/Members/MemberRecipeList/MemberRecipeList.tsx
  frontend/src/components/Members/MembersInfo/MembersInfo.tsx
  frontend/src/components/Product/PBProductItem/PBProductItem.tsx
  frontend/src/components/Product/ProductDetailItem/ProductDetailItem.tsx
  frontend/src/components/Product/ProductItem/ProductItem.tsx
  frontend/src/components/Product/ProductOverviewItem/ProductOverviewItem.tsx
  frontend/src/components/Rank/RecipeRankingItem/RecipeRankingItem.tsx
  frontend/src/components/Recipe/RecipeItem/RecipeItem.tsx
  frontend/src/components/Review/ReviewItem/ReviewItem.tsx
  frontend/src/mocks/data/recipeDetail.json
  frontend/src/pages/MemberModifyPage.tsx
  frontend/src/pages/MemberRecipePage.tsx
  frontend/src/pages/RecipeDetailPage.tsx
  frontend/src/types/recipe.ts
  frontend/src/utils/image.ts
Labels: 🔑 FE, 🔧 Refactor

#530 [FE] refactor: 꿀조합 랭킹 컴포넌트 너비 수정
  frontend/src/components/Rank/RecipeRankingItem/RecipeRankingItem.tsx
  frontend/src/components/Rank/RecipeRankingList/RecipeRankingList.tsx
Labels: 🔑 FE, 🔧 Refactor, 🎨 UI

#542 [FE] refactor: 개행 문자 스타일 처리
  frontend/src/components/Product/ProductDetailItem/ProductDetailItem.tsx
  frontend/src/components/Product/ProductRecipeList/ProductRecipeList.tsx
  frontend/src/components/Review/ReviewItem/ReviewItem.tsx
  frontend/src/mocks/data/productDetail.json
  frontend/src/mocks/data/productDetails.json
  frontend/src/pages/LoginPage.tsx
  frontend/src/pages/ProductDetailPage.tsx
Labels: 🔑 FE, 🔧 Refactor

#520 [BE] refactor: 정팩메 수정, 태그 종류 변경
  backend/src/main/java/com/funeat/member/domain/favorite/ReviewFavorite.java
  backend/src/main/java/com/funeat/review/application/ReviewService.java
  backend/src/main/java/com/funeat/tag/domain/TagType.java
  backend/src/test/java/com/funeat/fixture/TagFixture.java
  backend/src/test/java/com/funeat/member/persistence/ReviewFavoriteRepositoryTest.java
  backend/src/test/java/com/funeat/product/domain/favorite/ReviewFavoriteTest.java
Labels: 🔒 BE, 🔧 Refactor

#531 [FE] refactor: tag variant 타입 PRICE->QUANTITY로 네이밍 변경
  frontend/src/components/Review/ReviewTagItem/ReviewTagItem.tsx
  frontend/src/constants/index.ts
  frontend/src/mocks/data/productDetail.json
  frontend/src/mocks/data/productDetails.json
  frontend/src/mocks/data/reviewTagList.json
  frontend/src/types/common.ts
  frontend/src/utils/convertTagColor.ts
Labels: 🔑 FE, 🔧 Refactor

#551 [BE] 검색 정렬 우선 순위 반대로 적용중 버그 해결
  backend/src/main/java/com/funeat/product/persistence/ProductRepository.java
  backend/src/test/java/com/funeat/acceptance/product/ProductAcceptanceTest.java
Labels: 🔒 BE, 🐛 Bug

#552 [FE] fix: 수정 안 된 import문 수정
  frontend/src/types/review.ts
Labels: 🔑 FE, 🐛 Bug
