Repository woowacourse-teams/2023-fun-eat, pull requests merged in 2023-10, with the labels that each got.

#721 [FE] feat: GA 이벤트 추가
  frontend/src/components/Common/CategoryFoodList/CategoryFoodList.tsx
  frontend/src/components/Common/CategoryFoodTab/CategoryFoodTab.tsx
  frontend/src/components/Common/CategoryStoreList/CategoryStoreList.tsx
  frontend/src/components/Common/CategoryStoreTab/CategoryStoreTab.tsx
  frontend/src/components/Rank/ProductRankingList/ProductRankingList.tsx
  frontend/src/components/Rank/RecipeRankingList/RecipeRankingList.tsx
  frontend/src/components/Rank/ReviewRankingList/ReviewRankingList.tsx
  frontend/src/components/Recipe/RecipeRegisterForm/RecipeRegisterForm.tsx
  frontend/src/hooks/common/index.ts
  frontend/src/hooks/common/useGA.ts
  frontend/src/hooks/search/useSearch.ts
  frontend/src/pages/HomePage.tsx
  frontend/src/pages/ProductDetailPage.tsx
  frontend/src/pages/ProductListPage.tsx
  frontend/src/pages/RecipePage.tsx
  frontend/src/utils/category.ts
Labels: 🔑 FE, ✨ Feature

#687 [BE] feat: 이미지 업로드 확장자 추가
  backend/src/main/java/com/funeat/common/s3/S3Uploader.java
Labels: 🔒 BE, ✨ Feature

#608 [FE] feat: 토스트 구현
  frontend/.storybook/preview-body.html
  frontend/public/index.html
  frontend/public/mockServiceWorker.js
  frontend/src/components/Common/Toast/Toast.stories.tsx
  frontend/src/components/Common/Toast/Toast.tsx
  frontend/src/components/Common/index.ts
  frontend/src/contexts/ToastContext.tsx
  frontend/src/hooks/common/index.ts
  frontend/src/hooks/common/useToast.ts
  frontend/src/hooks/context/index.ts
  frontend/src/hooks/context/useToastActionContext.ts
  frontend/src/hooks/context/useToastValueContext.ts
  frontend/src/index.tsx
  frontend/src/styles/animations.ts
  frontend/src/styles/globalStyle.ts
  frontend/yarn.lock
Labels: 🔑 FE, ✨ Feature

#725 [FE] 로그인 안했을 때도 리뷰를 1개 확인할 수 있는 기능 구현
  frontend/package.json
  frontend/src/components/Common/TagList/TagList.tsx
  frontend/src/components/Product/ProductDetailItem/ProductDetailItem.tsx
  frontend/src/components/Review/BestReviewItem/BestReviewItem.stories.tsx
  frontend/src/components/Review/BestReviewItem/BestReviewItem.tsx
  frontend/src/components/Review/index.ts
  frontend/src/hooks/queries/rank/index.ts
  frontend/src/hooks/queries/rank/useBestReviewQuery.ts
  frontend/src/mocks/handlers/rankingHandlers.ts
  frontend/src/pages/ProductDetailPage.tsx
  frontend/yarn.lock
Labels: 🔑 FE, ✨ Feature

#724 [BE] 특정 상품에서 좋아요를 가장 많이 받은 리뷰를 응답하는 API 연결
  backend/src/main/java/com/funeat/review/application/ReviewService.java
  backend/src/main/java/com/funeat/review/dto/MostFavoriteReviewResponse.java
  backend/src/main/java/com/funeat/review/persistence/ReviewRepository.java
  backend/src/main/java/com/funeat/review/presentation/ReviewApiController.java
  backend/src/main/java/com/funeat/review/presentation/ReviewController.java
  backend/src/test/java/com/funeat/acceptance/auth/AuthAcceptanceTest.java
  backend/src/test/java/com/funeat/acceptance/member/MemberAcceptanceTest.java
  backend/src/test/java/com/funeat/acceptance/product/ProductAcceptanceTest.java
  backend/src/test/java/com/funeat/acceptance/recipe/RecipeAcceptanceTest.java
  backend/src/test/java/com/funeat/acceptance/review/ReviewAcceptanceTest.java
  backend/src/test/java/com/funeat/acceptance/review/ReviewSteps.java
  backend/src/test/java/com/funeat/review/application/ReviewServiceTest.java
  backend/src/test/java/com/funeat/review/persistence/ReviewRepositoryTest.java
Labels: 🔒 BE, ✨ Feature

#732 [FE] feat: 홈에서 카테고리 눌렀을 때 context에 저장하는 방식으로 변경
  frontend/src/components/Common/CategoryFoodList/CategoryFoodList.stories.tsx
  frontend/src/components/Common/CategoryFoodList/CategoryFoodList.tsx
  frontend/src/components/Common/CategoryFoodTab/CategoryFoodTab.tsx
  frontend/src/components/Common/CategoryItem/CategoryItem.stories.tsx
  frontend/src/components/Common/CategoryItem/CategoryItem.tsx
  frontend/src/components/Common/CategoryStoreList/CategoryStoreList.stories.tsx
  frontend/src/components/Common/CategoryStoreList/CategoryStoreList.tsx
  frontend/src/components/Common/CategoryStoreTab/CategoryStoreTab.tsx
Labels: 🔑 FE, 🔧 Refactor

#736 [FE] refactor: 캐러셀 Index 수정
  frontend/src/components/Common/Carousel/Carousel.tsx
Labels: 🔑 FE, 🔧 Refactor

#731 [BE] feat: 어드민 관리자 api 구현
  backend/src/main/java/com/funeat/FuneatApplication.java
  backend/src/main/java/com/funeat/admin/application/AdminChecker.java
  backend/src/main/java/com/funeat/admin/application/AdminService.java
  backend/src/main/java/com/funeat/admin/domain/AdminAuthInfo.java
  backend/src/main/java/com/funeat/admin/dto/AdminCategoryResponse.java
  backend/src/main/java/com/funeat/admin/dto/AdminProductResponse.java
  backend/src/main/java/com/funeat/admin/dto/AdminProductSearchResponse.java
  backend/src/main/java/com/funeat/admin/dto/AdminReviewResponse.java
  backend/src/main/java/com/funeat/admin/dto/AdminReviewSearchResponse.java
  backend/src/main/java/com/funeat/admin/dto/ProductCreateRequest.java
  backend/src/main/java/com/funeat/admin/dto/ProductSearchCondition.java
  backend/src/main/java/com/funeat/admin/dto/ProductUpdateRequest.java
  backend/src/main/java/com/funeat/admin/dto/ReviewSearchCondition.java
  backend/src/main/java/com/funeat/admin/presentation/AdminController.java
  backend/src/main/java/com/funeat/admin/presentation/AdminLoginController.java
  backend/src/main/java/com/funeat/admin/repository/AdminProductRepository.java
  backend/src/main/java/com/funeat/admin/repository/AdminReviewRepository.java
  backend/src/main/java/com/funeat/admin/specification/AdminProductSpecification.java
  backend/src/main/java/com/funeat/admin/specification/AdminReviewSpecification.java
  backend/src/main/java/com/funeat/admin/util/AdminCheckInterceptor.java
  backend/src/main/java/com/funeat/auth/exception/AuthErrorCode.java
  backend/src/main/java/com/funeat/common/WebConfig.java
  backend/src/main/java/com/funeat/common/repository/BaseRepository.java
  backend/src/main/java/com/funeat/common/repository/BaseRepositoryImpl.java
  backend/src/main/java/com/funeat/member/presentation/MemberApiController.java
  backend/src/main/java/com/funeat/member/presentation/MemberController.java
  backend/src/main/java/com/funeat/product/domain/Product.java
  backend/src/main/java/com/funeat/product/persistence/ProductRepository.java
  backend/src/main/resources/application-local.yml
  backend/src/main/resources/application.yml
  backend/src/test/java/com/funeat/acceptance/member/MemberAcceptanceTest.java
  backend/src/test/resources/application.yml
Labels: 🔒 BE, ✨ Feature

#742 [FE] fix: 베스트리뷰 요청 204 처리
  frontend/src/components/Review/BestReviewItem/BestReviewItem.tsx
  frontend/src/hooks/queries/rank/useBestReviewQuery.ts
Labels: 🔑 FE, 🐛 Bug

#730 [BE] refactor: 로그인 세션 정보를 DB에 저장하는 기능 추가
  backend/build.gradle
  backend/src/main/java/com/funeat/auth/application/AuthService.java
  backend/src/main/resources/application.yml
  backend/src/test/java/com/funeat/acceptance/auth/LoginSteps.java
  backend/src/test/java/com/funeat/acceptance/member/MemberSteps.java
  backend/src/test/java/com/funeat/acceptance/recipe/RecipeSteps.java
  backend/src/test/java/com/funeat/acceptance/review/ReviewSteps.java
  backend/src/test/resources/application.yml
Labels: 🔒 BE, 🔧 Refactor

#749 [BE] fix: 로그아웃시 쿠키가 삭제되도록 수정
  backend/src/main/java/com/funeat/auth/application/AuthService.java
Labels: 🔒 BE, 🐛 Bug

#751 [BE] hotfix: id, key Session 에 따로 저장
  backend/src/main/java/com/funeat/admin/presentation/AdminLoginController.java
  backend/src/main/java/com/funeat/admin/util/AdminCheckInterceptor.java
Labels: 🔒 BE, 🐛 Bug

#744 [FE] feat: 꿀조합 댓글 기능 구현
  frontend/.storybook/preview-body.html
  frontend/src/components/Common/Input/Input.tsx
  frontend/src/components/Common/Svg/SvgIcon.tsx
  frontend/src/components/Common/Svg/SvgSprite.tsx
  frontend/src/components/Common/Toast/Toast.tsx
  frontend/src/components/Recipe/CommentForm/CommentForm.stories.tsx
  frontend/src/components/Recipe/CommentForm/CommentForm.tsx
  frontend/src/components/Recipe/CommentItem/CommentItem.stories.tsx
  frontend/src/components/Recipe/CommentItem/CommentItem.tsx
  frontend/src/components/Recipe/CommentList/CommentList.stories.tsx
  frontend/src/components/Recipe/CommentList/CommentList.tsx
  frontend/src/components/Recipe/index.ts
  frontend/src/contexts/ToastContext.tsx
  frontend/src/hooks/queries/recipe/index.ts
  frontend/src/hooks/queries/recipe/useInfiniteRecipeCommentQuery.ts
  frontend/src/hooks/queries/recipe/useRecipeCommentMutation.ts
  frontend/src/mocks/data/comments.json
  frontend/src/mocks/handlers/recipeHandlers.ts
  frontend/src/pages/RecipeDetailPage.tsx
  frontend/src/router/index.tsx
  frontend/src/types/recipe.ts
  frontend/src/types/response.ts
Labels: 🔑 FE, ✨ Feature

#752 [FE] feat: 라우팅 관련 처리
  frontend/src/constants/index.ts
  frontend/src/hooks/common/index.ts
  frontend/src/pages/AuthPage.tsx
  frontend/src/pages/ProductDetailPage.tsx
  frontend/src/router/index.tsx
  frontend/src/utils/localStorage.ts
Labels: 🔑 FE, ✨ Feature

#760 [FE] fix: 로컬스토리지 유틸 import 대소문자 수정
  frontend/src/pages/AuthPage.tsx
  frontend/src/pages/ProductDetailPage.tsx
Labels: 🔑 FE, 🐛 Bug

#762 [FE] feat: 리뷰 상세 페이지 구현
  frontend/.storybook/preview-body.html
  frontend/package.json
  frontend/src/apis/index.ts
  frontend/src/components/Common/Loading/Loading.tsx
  frontend/src/components/Common/SectionTitle/SectionTitle.stories.tsx
  frontend/src/components/Common/SectionTitle/SectionTitle.tsx
  frontend/src/components/Common/Svg/SvgIcon.tsx
  frontend/src/components/Common/Svg/SvgSprite.tsx
  frontend/src/components/Members/MemberReviewList/MemberReviewList.tsx
  frontend/src/components/Rank/ReviewRankingItem/ReviewRankingItem.tsx
  frontend/src/components/Rank/ReviewRankingList/ReviewRankingList.tsx
  frontend/src/constants/path.ts
  frontend/src/hooks/queries/review/index.ts
  frontend/src/hooks/queries/review/useReviewDetailQuery.ts
  frontend/src/mocks/data/productDetail.json
  frontend/src/mocks/data/productDetails.json
  frontend/src/mocks/data/reviewDetail.json
  frontend/src/mocks/handlers/reviewHandlers.ts
  frontend/src/pages/ProductDetailPage.tsx
  frontend/src/pages/ReviewDetailPage.tsx
  frontend/src/router/index.tsx
  frontend/src/types/product.ts
  frontend/src/types/ranking.ts
  frontend/src/types/response.ts
  frontend/src/types/review.ts
  frontend/src/types/search.ts
  frontend/yarn.lock
Labels: 🔑 FE, ✨ Feature

#765 [FE] feat: 랭킹 기준 텍스트 추가
  frontend/.storybook/preview-body.html
  frontend/src/components/Common/Svg/SvgIcon.tsx
  frontend/src/components/Common/Svg/SvgSprite.tsx
  frontend/src/components/Product/ProductDetailItem/ProductDetailItem.tsx
  frontend/src/components/Product/ProductItem/ProductItem.tsx
  frontend/src/pages/HomePage.tsx
Labels: 🔑 FE, 🎨 UI

#735 [BE] feat: 리뷰 삭제 기능 구현
  backend/src/main/java/com/funeat/FuneatApplication.java
  backend/src/main/java/com/funeat/common/ImageUploader.java
  backend/src/main/java/com/funeat/common/exception/CommonException.java
  backend/src/main/java/com/funeat/common/s3/S3Uploader.java
  backend/src/main/java/com/funeat/member/persistence/ReviewFavoriteRepository.java
  backend/src/main/java/com/funeat/member/presentation/MemberApiController.java
  backend/src/main/java/com/funeat/member/presentation/MemberController.java
  backend/src/main/java/com/funeat/review/application/ReviewDeleteEvent.java
  backend/src/main/java/com/funeat/review/application/ReviewDeleteEventListener.java
  backend/src/main/java/com/funeat/review/application/ReviewService.java
  backend/src/main/java/com/funeat/review/domain/Review.java
  backend/src/main/java/com/funeat/review/exception/ReviewErrorCode.java
  backend/src/main/java/com/funeat/review/exception/ReviewException.java
  backend/src/main/java/com/funeat/review/persistence/ReviewTagRepository.java
  backend/src/main/java/com/funeat/review/presentation/ReviewApiController.java
  backend/src/main/java/com/funeat/review/presentation/ReviewController.java
  backend/src/main/resources/application.yml
  backend/src/test/java/com/funeat/acceptance/member/MemberAcceptanceTest.java
  backend/src/test/java/com/funeat/acceptance/member/MemberSteps.java
  backend/src/test/java/com/funeat/common/EventTest.java
  backend/src/test/java/com/funeat/common/TestImageUploader.java
  backend/src/test/java/com/funeat/member/persistence/ReviewFavoriteRepositoryTest.java
  backend/src/test/java/com/funeat/review/application/ReviewDeleteEventListenerTest.java
  backend/src/test/java/com/funeat/review/application/ReviewServiceTest.java
  backend/src/test/java/com/funeat/review/persistence/ReviewTagRepositoryTest.java
Labels: 🔒 BE, ✨ Feature

#747 [BE] feat: 꿀조합 댓글 작성 기능 구현
  backend/src/main/java/com/funeat/admin/specification/AdminProductSpecification.java
  backend/src/main/java/com/funeat/admin/specification/AdminReviewSpecification.java
  backend/src/main/java/com/funeat/comment/domain/Comment.java
  backend/src/main/java/com/funeat/comment/persistence/CommentRepository.java
  backend/src/main/java/com/funeat/comment/specification/CommentSpecification.java
  backend/src/main/java/com/funeat/member/domain/bookmark/ProductBookmark.java
  backend/src/main/java/com/funeat/member/domain/bookmark/RecipeBookmark.java
  backend/src/main/java/com/funeat/member/persistence/ProductBookmarkRepository.java
  backend/src/main/java/com/funeat/member/persistence/RecipeBookMarkRepository.java
  backend/src/main/java/com/funeat/product/domain/Product.java
  backend/src/main/java/com/funeat/recipe/application/RecipeService.java
  backend/src/main/java/com/funeat/recipe/dto/RecipeCommentCondition.java
  backend/src/main/java/com/funeat/recipe/dto/RecipeCommentCreateRequest.java
  backend/src/main/java/com/funeat/recipe/dto/RecipeCommentMemberResponse.java
  backend/src/main/java/com/funeat/recipe/dto/RecipeCommentResponse.java
  backend/src/main/java/com/funeat/recipe/dto/RecipeCommentsResponse.java
  backend/src/main/java/com/funeat/recipe/presentation/RecipeApiController.java
  backend/src/main/java/com/funeat/recipe/presentation/RecipeController.java
  backend/src/test/java/com/funeat/acceptance/common/AcceptanceTest.java
  backend/src/test/java/com/funeat/acceptance/recipe/RecipeAcceptanceTest.java
  backend/src/test/java/com/funeat/acceptance/recipe/RecipeSteps.java
  backend/src/test/java/com/funeat/acceptance/review/ReviewSteps.java
  backend/src/test/java/com/funeat/common/RepositoryTest.java
  backend/src/test/java/com/funeat/common/ServiceTest.java
  backend/src/test/java/com/funeat/recipe/application/RecipeServiceTest.java
  backend/src/test/java/com/funeat/recipe/persistence/RecipeRepositoryTest.java
  backend/src/test/java/com/funeat/review/application/ReviewServiceTest.java
Labels: 🔒 BE, ✨ Feature

#768 [FE] feat: 꿀조합 댓글 조회에 credentials 추가
  frontend/src/hooks/queries/recipe/useInfiniteRecipeCommentQuery.ts
Labels: 🔑 FE, ✨ Feature

#770 [FE] fix: totalElements가 없는 경우 query string에서 제외
  frontend/src/hooks/queries/recipe/useInfiniteRecipeCommentQuery.ts
Labels: 🔑 FE, 🐛 Bug

#772 [FE] feat: 꿀조합 댓글이 없는 경우 예외처리
  frontend/src/components/Recipe/CommentList/CommentList.tsx
  frontend/src/hooks/queries/recipe/useInfiniteRecipeCommentQuery.ts
Labels: 🔑 FE, ✨ Feature, 🐛 Bug

#774 [FE] feat: totalElements가 null일 때 아예 쿼리를 보내지 않도록 수정
  frontend/src/hooks/queries/recipe/useInfiniteRecipeCommentQuery.ts
Labels: 🔑 FE, 🔧 Refactor

#607 [BE] feat: 상품에 대한 리뷰 목록 조회 동적 쿼리 구현 및 API 성능 개선
  backend/src/main/java/com/funeat/review/application/ReviewService.java
  backend/src/main/java/com/funeat/review/dto/SortingReviewDto.java
  backend/src/main/java/com/funeat/review/dto/SortingReviewDtoWithoutTag.java
  backend/src/main/java/com/funeat/review/dto/SortingReviewRequest.java
  backend/src/main/java/com/funeat/review/dto/SortingReviewsResponse.java
  backend/src/main/java/com/funeat/review/exception/ReviewErrorCode.java
  backend/src/main/java/com/funeat/review/exception/ReviewException.java
  backend/src/main/java/com/funeat/review/persistence/ReviewCustomRepository.java
  backend/src/main/java/com/funeat/review/persistence/ReviewRepository.java
  backend/src/main/java/com/funeat/review/persistence/ReviewRepositoryImpl.java
  backend/src/main/java/com/funeat/review/presentation/ReviewApiController.java
  backend/src/main/java/com/funeat/review/presentation/ReviewController.java
  backend/src/main/java/com/funeat/review/specification/LongTypeReviewSortSpec.java
  backend/src/main/java/com/funeat/review/specification/SortingReviewSpecification.java
  backend/src/main/java/com/funeat/tag/persistence/TagRepository.java
  backend/src/test/java/com/funeat/acceptance/common/CommonSteps.java
  backend/src/test/java/com/funeat/acceptance/review/ReviewAcceptanceTest.java
  backend/src/test/java/com/funeat/acceptance/review/ReviewSteps.java
  backend/src/test/java/com/funeat/fixture/PageFixture.java
  backend/src/test/java/com/funeat/fixture/ReviewFixture.java
  backend/src/test/java/com/funeat/recipe/application/RecipeServiceTest.java
  backend/src/test/java/com/funeat/recipe/persistence/RecipeRepositoryTest.java
  backend/src/test/java/com/funeat/review/application/ReviewServiceTest.java
  backend/src/test/java/com/funeat/review/persistence/ReviewRepositoryTest.java
Labels: 🔒 BE, 🔧 Refactor

#779 [FE] feat: 꿀조합 댓글 버그 수정 및 개선
  frontend/src/components/Recipe/CommentForm/CommentForm.tsx
  frontend/src/components/Recipe/CommentList/CommentList.tsx
  frontend/src/mocks/data/comments.json
  frontend/src/pages/RecipeDetailPage.tsx
Labels: 🔑 FE, ✨ Feature

#778 [BE] fix: ReviewDeleteEventListenerTest 통과하도록 수정
  backend/src/main/java/com/funeat/review/application/ReviewDeleteEventListener.java
  backend/src/test/java/com/funeat/common/EventTest.java
  backend/src/test/java/com/funeat/fixture/ReviewFixture.java
  backend/src/test/java/com/funeat/review/application/ReviewDeleteEventListenerTest.java
Labels: 🔒 BE, 🐛 Bug

#737 [BE] refactor: 리뷰 랭킹 알고리즘 개선
  backend/src/main/java/com/funeat/review/application/ReviewService.java
  backend/src/main/java/com/funeat/review/domain/Review.java
  backend/src/main/java/com/funeat/review/persistence/ReviewRepository.java
  backend/src/test/java/com/funeat/fixture/ReviewFixture.java
  backend/src/test/java/com/funeat/review/application/ReviewServiceTest.java
  backend/src/test/java/com/funeat/review/domain/ReviewTest.java
  backend/src/test/java/com/funeat/review/persistence/ReviewRepositoryTest.java
Labels: 🔒 BE, 🔧 Refactor

#755 [BE] refactor: 꿀조합 랭킹 알고리즘 개선
  backend/src/main/java/com/funeat/product/domain/Category.java
  backend/src/main/java/com/funeat/recipe/application/RecipeService.java
  backend/src/main/java/com/funeat/recipe/domain/Recipe.java
  backend/src/main/java/com/funeat/recipe/persistence/RecipeRepository.java
  backend/src/main/java/com/funeat/review/presentation/ReviewApiController.java
  backend/src/test/java/com/funeat/fixture/RecipeFixture.java
  backend/src/test/java/com/funeat/recipe/application/RecipeServiceTest.java
  backend/src/test/java/com/funeat/recipe/domain/RecipeTest.java
  backend/src/test/java/com/funeat/recipe/persistence/RecipeRepositoryTest.java
Labels: 🔒 BE, 🔧 Refactor

#780 [FE] 리뷰 삭제 기능 구현
  frontend/.storybook/preview-body.html
  frontend/src/components/Common/Svg/SvgIcon.tsx
  frontend/src/components/Common/Svg/SvgSprite.tsx
  frontend/src/components/Members/MemberRecipeList/MemberRecipeList.tsx
  frontend/src/components/Members/MemberReviewItem/MemberReviewItem.stories.tsx
  frontend/src/components/Members/MemberReviewItem/MemberReviewItem.tsx
  frontend/src/components/Members/MemberReviewList/MemberReviewList.tsx
  frontend/src/components/Members/index.ts
  frontend/src/components/Rank/ReviewRankingItem/ReviewRankingItem.tsx
  frontend/src/hooks/queries/members/index.ts
  frontend/src/hooks/queries/members/useDeleteReview.ts
  frontend/src/mocks/handlers/memberHandlers.ts
  frontend/src/pages/MemberPage.tsx
  frontend/src/types/review.ts
Labels: 🔑 FE, ✨ Feature

#783 [FE] fix: storybook에서 바뀐 변수명 수정
  frontend/src/components/Members/MemberReviewItem/MemberReviewItem.stories.tsx
Labels: 🔑 FE, 🐛 Bug

#781 [FE] refactor: 무한스크롤 페이징 관련 api 변경 적용
  frontend/src/hooks/queries/product/useInfiniteProductReviewsQuery.ts
  frontend/src/hooks/queries/product/useInfiniteProductsQuery.ts
  frontend/src/mocks/data/pbProducts.json
  frontend/src/mocks/data/products.json
  frontend/src/mocks/data/reviews.json
  frontend/src/mocks/handlers/productHandlers.ts
  frontend/src/mocks/handlers/reviewHandlers.ts
  frontend/src/types/response.ts
Labels: 🔑 FE, 🔧 Refactor

#756 [BE] refactor: 상품 랭킹 알고리즘 개선
  backend/src/main/java/com/funeat/product/application/ProductService.java
  backend/src/main/java/com/funeat/product/persistence/ProductRepository.java
  backend/src/test/java/com/funeat/product/application/ProductServiceTest.java
  backend/src/test/java/com/funeat/product/persistence/ProductRepositoryTest.java
Labels: 🔒 BE, 🔧 Refactor

#786 [FE] refactor: 이미지 압축 라이브러리 도입
  frontend/.storybook/preview-body.html
  frontend/package.json
  frontend/public/index.html
  frontend/src/components/Common/ImageUploader/ImageUploader.tsx
  frontend/src/components/Common/SortOptionList/SortOptionList.stories.tsx
  frontend/src/components/Review/ReviewRegisterForm/ReviewRegisterForm.tsx
  frontend/src/hooks/common/useImageUploader.ts
  frontend/src/pages/MemberModifyPage.tsx
  frontend/src/pages/ProductDetailPage.tsx
  frontend/src/pages/ProductListPage.tsx
  frontend/src/pages/RecipePage.tsx
  frontend/yarn.lock
Labels: 🔑 FE, 🔧 Refactor

#789 [FE] refactor: alert를 toast로 변경
  frontend/src/components/Recipe/RecipeFavorite/RecipeFavorite.tsx
  frontend/src/components/Recipe/RecipeRegisterForm/RecipeRegisterForm.tsx
  frontend/src/components/Review/ReviewItem/ReviewItem.tsx
  frontend/src/hooks/queries/members/useLogoutMutation.ts
  frontend/src/hooks/search/useSearch.ts
  frontend/src/pages/MemberModifyPage.tsx
Labels: 🔑 FE, 🔧 Refactor

#788 [BE] test: 테스트 환경에 영향받는 비동기 로직 작동 검증 테스트 제거
  backend/src/test/java/com/funeat/review/application/ReviewDeleteEventListenerTest.java
Labels: 🔒 BE, 🐛 Bug, 💻 Test

#758 [BE] feat: 리뷰 상세 조회 API 구현
  backend/src/main/java/com/funeat/review/application/ReviewService.java
  backend/src/main/java/com/funeat/review/dto/ReviewDetailResponse.java
  backend/src/main/java/com/funeat/review/presentation/ReviewApiController.java
  backend/src/main/java/com/funeat/review/presentation/ReviewController.java
  backend/src/test/java/com/funeat/acceptance/review/ReviewAcceptanceTest.java
  backend/src/test/java/com/funeat/acceptance/review/ReviewSteps.java
  backend/src/test/java/com/funeat/review/application/ReviewServiceTest.java
Labels: 🔒 BE, ✨ Feature

#791 [BE] feat: Banner entity 구현, Banner 전체 조회 구현
  backend/src/main/java/com/funeat/banner/application/BannerService.java
  backend/src/main/java/com/funeat/banner/domain/Banner.java
  backend/src/main/java/com/funeat/banner/dto/BannerResponse.java
  backend/src/main/java/com/funeat/banner/persistence/BannerRepository.java
  backend/src/main/java/com/funeat/banner/presentation/BannerApiController.java
  backend/src/main/java/com/funeat/banner/presentation/BannerController.java
  backend/src/main/java/com/funeat/common/OpenApiConfig.java
  backend/src/test/java/com/funeat/acceptance/banner/BannerAcceptanceTest.java
  backend/src/test/java/com/funeat/acceptance/banner/BannerSteps.java
  backend/src/test/java/com/funeat/acceptance/common/AcceptanceTest.java
  backend/src/test/java/com/funeat/banner/application/BannerServiceTest.java
  backend/src/test/java/com/funeat/banner/persistence/BannerRepositoryTest.java
  backend/src/test/java/com/funeat/common/RepositoryTest.java
  backend/src/test/java/com/funeat/common/ServiceTest.java
  backend/src/test/java/com/funeat/fixture/BannerFixture.java
  backend/src/test/java/com/funeat/review/application/ReviewDeleteEventListenerTest.java
Labels: 🔒 BE, ✨ Feature

#796 [FE] fix: 리뷰 상세 api 수정
  frontend/src/hooks/queries/review/useReviewDetailQuery.ts
  frontend/src/mocks/data/reviewDetail.json
  frontend/src/pages/ReviewDetailPage.tsx
  frontend/src/router/index.tsx
  frontend/src/types/response.ts
Labels: 🔑 FE, 🐛 Bug

#795 [BE] feat: HikariCP 옵션 설정
  backend/src/main/resources/application.yml
Labels: 🔒 BE, ✨ Feature

#790 [FE] feat: 배너 조회 API 연결 및 배너 컴포넌트 작성
  frontend/src/apis/index.ts
  frontend/src/components/Common/Banner/Banner.tsx
  frontend/src/components/Common/index.ts
  frontend/src/hooks/queries/banner/index.ts
  frontend/src/hooks/queries/banner/useBannerQuery.ts
  frontend/src/mocks/browser.ts
  frontend/src/mocks/data/banners.json
  frontend/src/mocks/handlers/bannerHandlers.ts
  frontend/src/mocks/handlers/index.ts
  frontend/src/pages/HomePage.tsx
  frontend/src/types/banner.ts
Labels: 🔑 FE, ✨ Feature

#800 fix: 꿀조합 등록 토스트 위치 이동
  frontend/src/components/Recipe/RecipeFavorite/RecipeFavorite.tsx
  frontend/src/components/Recipe/RecipeRegisterForm/RecipeRegisterForm.tsx
Labels: 🔑 FE, 🐛 Bug

#801 [FE] fix: 꿀조합 무한스크롤 되지 않는 버그 해결
  frontend/src/components/Recipe/CommentList/CommentList.tsx
Labels: 🔑 FE, 🐛 Bug

#805 [FE] feat: 꿀조합 상세 이미지 크기 조정
  frontend/src/mocks/data/recipeDetail.json
  frontend/src/pages/RecipeDetailPage.tsx
Labels: 🔑 FE, 🎨 UI

#806 [FE] router 리팩터링
  frontend/src/router/index.tsx
Labels: 🔑 FE, 🔧 Refactor

#803 [BE] feat: 리뷰 삭제시 상품 정보 업데이트 로직 추가
  backend/src/main/java/com/funeat/product/application/ProductService.java
  backend/src/main/java/com/funeat/product/domain/Product.java
  backend/src/main/java/com/funeat/product/dto/ProductResponse.java
  backend/src/main/java/com/funeat/review/application/ReviewService.java
  backend/src/test/java/com/funeat/product/domain/ProductTest.java
  backend/src/test/java/com/funeat/review/application/ReviewServiceTest.java
Labels: 🔒 BE, ✨ Feature

#808 [BE] fix: 좋아요 취소도 좋아요를 누르지 않은 것으로 설정
  backend/src/main/java/com/funeat/review/dto/SortingReviewDtoWithoutTag.java
Labels: 🔒 BE, 🐛 Bug

#815 [BE] fix: 상품의 썸네일이었던 리뷰를 삭제했을 경우 썸네일이 업데이트 되지 않는 문제 해결
  backend/src/main/java/com/funeat/review/application/ReviewService.java
Labels: 🔒 BE, 🐛 Bug

#814 [FE] feat: 꿀조합 페이지 접속 시 이전 페이지 로컬스토리지에 경로 저장
  frontend/src/constants/index.ts
  frontend/src/mocks/handlers/recipeHandlers.ts
  frontend/src/pages/AuthPage.tsx
  frontend/src/pages/ProductDetailPage.tsx
  frontend/src/pages/RecipePage.tsx
Labels: 🔑 FE, ✨ Feature

#822 [BE] fix: 상품에 이미지가 있는 리뷰가 없을 경우 기본 이미지로 설정
  backend/src/main/java/com/funeat/product/domain/Category.java
  backend/src/main/java/com/funeat/product/domain/Product.java
  backend/src/main/java/com/funeat/review/application/ReviewService.java
  backend/src/main/resources/application-dev.yml
  backend/src/main/resources/application-local.yml
  backend/src/main/resources/application-prod.yml
  backend/src/test/resources/application.yml
Labels: 🔒 BE, 🐛 Bug

#821 [BE] refactor: 리뷰 및 꿀조합 랭킹 Response 수정
  backend/src/main/java/com/funeat/recipe/dto/RankingRecipeDto.java
  backend/src/main/java/com/funeat/review/dto/RankingReviewDto.java
Labels: 🔒 BE, 🔧 Refactor

#819 [BE] refactor: 프로덕션 로그인 쿠키 이름과 테스트 로그인 쿠키 이름 통일
  backend/src/test/java/com/funeat/acceptance/auth/LoginSteps.java
  backend/src/test/java/com/funeat/acceptance/member/MemberSteps.java
  backend/src/test/java/com/funeat/acceptance/recipe/RecipeSteps.java
  backend/src/test/java/com/funeat/acceptance/review/ReviewSteps.java
  backend/src/test/resources/application.yml
Labels: 🔒 BE, 🔧 Refactor

#818 [FE] feat: PB 상품 목록에서 상품 썸네일 삼김이로 변경
  frontend/src/components/Product/ProductDetailItem/ProductDetailItem.tsx
  frontend/src/components/Product/ProductItem/ProductItem.tsx
  frontend/src/mocks/data/pbProducts.json
Labels: 🔑 FE, 🎨 UI

#826 [FE] feat: 랭킹 상대 시간 추가
  frontend/src/components/Rank/RecipeRankingItem/RecipeRankingItem.tsx
  frontend/src/components/Rank/ReviewRankingItem/ReviewRankingItem.stories.tsx
  frontend/src/components/Rank/ReviewRankingItem/ReviewRankingItem.tsx
  frontend/src/mocks/data/recipeRankingList.json
  frontend/src/mocks/data/reviewRankingList.json
  frontend/src/types/ranking.ts
Labels: 🔑 FE, 🎨 UI

#827 [ALL] docs: 로고 이미지 수정
  README.md
Labels: 📃 Docs

#830 [BE] hotfix: 기본 이미지로 업데이트 로직에 환경변수 제거
  backend/src/main/java/com/funeat/product/domain/Product.java
  backend/src/main/resources/application-dev.yml
  backend/src/main/resources/application-local.yml
  backend/src/main/resources/application-prod.yml
Labels: 🔒 BE, 🐛 Bug

#832 [FE] fix: 상품 아이템 null 처리 제거
  frontend/src/components/Product/ProductItem/ProductItem.tsx
Labels: 🔑 FE, 🐛 Bug
