Repository woowacourse-teams/2023-fun-eat, pull requests merged in 2023-09, with the labels that each got.

#565 [BE] feat: 로그인 정보가 존재하지 않을 때, 새로운 세션을 생성하지 않도록 하는 설정 추가
  backend/src/main/java/com/funeat/auth/application/AuthService.java
  backend/src/main/java/com/funeat/auth/presentation/AuthApiController.java
  backend/src/main/java/com/funeat/auth/presentation/AuthController.java
  backend/src/main/java/com/funeat/auth/util/AuthArgumentResolver.java
  backend/src/main/java/com/funeat/auth/util/AuthHandlerInterceptor.java
  backend/src/main/java/com/funeat/recipe/util/RecipeDetailHandlerInterceptor.java
  backend/src/main/java/com/funeat/recipe/util/RecipeHandlerInterceptor.java
  backend/src/main/resources/application.yml
  backend/src/test/java/com/funeat/acceptance/auth/AuthAcceptanceTest.java
  backend/src/test/java/com/funeat/acceptance/auth/LoginSteps.java
  backend/src/test/java/com/funeat/acceptance/member/MemberAcceptanceTest.java
  backend/src/test/java/com/funeat/acceptance/member/MemberSteps.java
  backend/src/test/java/com/funeat/acceptance/recipe/RecipeAcceptanceTest.java
  backend/src/test/java/com/funeat/acceptance/recipe/RecipeSteps.java
  backend/src/test/java/com/funeat/acceptance/review/ReviewAcceptanceTest.java
  backend/src/test/java/com/funeat/acceptance/review/ReviewSteps.java
  backend/src/test/resources/application.yml
Labels: 🔒 BE, 🔧 Refactor

#571 [FE] feat: 구글 애널리틱스 js에서 처리하도록 이동
  frontend/package.json
  frontend/public/index.html
  frontend/src/hooks/common/index.ts
  frontend/src/hooks/common/useRouteChangeTracker.ts
  frontend/src/index.tsx
  frontend/src/pages/ProductDetailPage.tsx
  frontend/src/router/App.tsx
  frontend/yarn.lock
Labels: 🔑 FE, ✨ Feature

#572 [BE] refactor: 리뷰 관련 dto 패키지 분리
  backend/src/main/java/com/funeat/review/application/ReviewService.java
  backend/src/main/java/com/funeat/review/dto/RankingReviewDto.java
  backend/src/main/java/com/funeat/review/dto/RankingReviewsResponse.java
  backend/src/main/java/com/funeat/review/dto/ReviewCreateRequest.java
  backend/src/main/java/com/funeat/review/dto/ReviewFavoriteRequest.java
  backend/src/main/java/com/funeat/review/dto/SortingReviewDto.java
  backend/src/main/java/com/funeat/review/dto/SortingReviewsResponse.java
  backend/src/main/java/com/funeat/review/presentation/ReviewApiController.java
  backend/src/main/java/com/funeat/review/presentation/ReviewController.java
  backend/src/test/java/com/funeat/acceptance/review/ReviewAcceptanceTest.java
  backend/src/test/java/com/funeat/acceptance/review/ReviewSteps.java
  backend/src/test/java/com/funeat/fixture/ReviewFixture.java
  backend/src/test/java/com/funeat/review/application/ReviewServiceTest.java
Labels: 🔒 BE, 🔧 Refactor

#568 [BE] refactor: image url만 받게 수정
  backend/build.gradle
  backend/src/main/java/com/funeat/common/ImageService.java
  backend/src/main/java/com/funeat/common/ImageUploader.java
  backend/src/main/java/com/funeat/member/application/MemberService.java
  backend/src/main/java/com/funeat/member/dto/MemberRequest.java
  backend/src/main/java/com/funeat/member/presentation/MemberApiController.java
  backend/src/main/java/com/funeat/member/presentation/MemberController.java
  backend/src/main/java/com/funeat/recipe/application/RecipeService.java
  backend/src/main/java/com/funeat/recipe/dto/RecipeCreateRequest.java
  backend/src/main/java/com/funeat/recipe/presentation/RecipeApiController.java
  backend/src/main/java/com/funeat/recipe/presentation/RecipeController.java
  backend/src/main/java/com/funeat/review/application/ReviewService.java
  backend/src/main/java/com/funeat/review/dto/ReviewCreateRequest.java
  backend/src/main/java/com/funeat/review/presentation/ReviewApiController.java
  backend/src/main/java/com/funeat/review/presentation/ReviewController.java
  backend/src/main/resources/application-dev.yml
  backend/src/main/resources/application-local.yml
  backend/src/main/resources/application-prod.yml
  backend/src/test/java/com/funeat/acceptance/member/MemberAcceptanceTest.java
  backend/src/test/java/com/funeat/acceptance/member/MemberSteps.java
  backend/src/test/java/com/funeat/acceptance/product/ProductAcceptanceTest.java
  backend/src/test/java/com/funeat/acceptance/recipe/RecipeAcceptanceTest.java
  backend/src/test/java/com/funeat/acceptance/recipe/RecipeSteps.java
  backend/src/test/java/com/funeat/acceptance/review/ReviewAcceptanceTest.java
  backend/src/test/java/com/funeat/acceptance/review/ReviewSteps.java
  backend/src/test/java/com/funeat/common/ServiceTest.java
  backend/src/test/java/com/funeat/common/TestImageUploader.java
  backend/src/test/java/com/funeat/fixture/RecipeFixture.java
  backend/src/test/java/com/funeat/fixture/ReviewFixture.java
  backend/src/test/java/com/funeat/member/application/MemberServiceTest.java
  backend/src/test/java/com/funeat/member/application/TestMemberService.java
  backend/src/test/java/com/funeat/recipe/application/RecipeServiceTest.java
  backend/src/test/java/com/funeat/review/application/ReviewServiceTest.java
Labels: 🔒 BE, 🔧 Refactor

#579 [FE] refactor: 이미지 S3로 업로드
  frontend/package.json
  frontend/src/apis/ApiClient.ts
  frontend/src/components/Members/MembersInfo/MembersInfo.tsx
  frontend/src/components/Product/PBProductItem/PBProductItem.tsx
  frontend/src/components/Product/ProductDetailItem/ProductDetailItem.tsx
  frontend/src/components/Product/ProductItem/ProductItem.tsx
  frontend/src/components/Product/ProductOverviewItem/ProductOverviewItem.tsx
  frontend/src/components/Rank/RecipeRankingItem/RecipeRankingItem.tsx
  frontend/src/components/Recipe/RecipeItem/RecipeItem.tsx
  frontend/src/components/Recipe/RecipeRegisterForm/RecipeRegisterForm.tsx
  frontend/src/components/Review/ReviewItem/ReviewItem.tsx
  frontend/src/components/Review/ReviewRegisterForm/ReviewRegisterForm.tsx
  frontend/src/constants/path.ts
  frontend/src/contexts/RecipeFormContext.tsx
  frontend/src/contexts/ReviewFormContext.tsx
  frontend/src/hooks/common/index.ts
  frontend/src/hooks/common/useFormData.ts
  frontend/src/hooks/common/useImageUploader.ts
  frontend/src/hooks/queries/members/useMemberModifyMutation.ts
  frontend/src/hooks/queries/recipe/useRecipeRegisterFormMutation.ts
  frontend/src/hooks/queries/review/useReviewRegisterFormMutation.ts
  frontend/src/pages/MemberModifyPage.tsx
  frontend/src/pages/RecipeDetailPage.tsx
  frontend/src/types/member.ts
  frontend/src/types/recipe.ts
  frontend/src/types/review.ts
  frontend/src/utils/image.ts
  frontend/yarn.lock
Labels: 🔑 FE, 🔧 Refactor

#582 [FE] fix: S3 이미지 업로드 수정
  frontend/package.json
  frontend/src/hooks/common/useImageUploader.ts
  frontend/src/index.tsx
  frontend/yarn.lock
Labels: 🔑 FE, 🐛 Bug

#583 [FE] feat: 이미지 업로드 에러 콘솔 추가
  frontend/src/hooks/common/useImageUploader.ts
Labels: 🔑 FE

#585 [BE] refactor: @ManyToOne의 FetchType을 LAZY로 수정
  backend/src/main/java/com/funeat/member/domain/favorite/RecipeFavorite.java
  backend/src/main/java/com/funeat/member/domain/favorite/ReviewFavorite.java
  backend/src/main/java/com/funeat/product/domain/Product.java
  backend/src/main/java/com/funeat/product/domain/ProductRecipe.java
  backend/src/main/java/com/funeat/recipe/domain/Recipe.java
  backend/src/main/java/com/funeat/recipe/domain/RecipeImage.java
  backend/src/main/java/com/funeat/recipe/persistence/RecipeRepository.java
  backend/src/main/java/com/funeat/review/domain/Review.java
  backend/src/test/java/com/funeat/acceptance/recipe/RecipeAcceptanceTest.java
Labels: 🔒 BE, 🔧 Refactor

#591 [BE] feat: S3 pre-singed-url 반환 기능 구현
  backend/build.gradle
  backend/src/main/java/com/funeat/common/OpenApiConfig.java
  backend/src/main/java/com/funeat/common/controller/PreSingedApiController.java
  backend/src/main/java/com/funeat/common/controller/PreSingedController.java
  backend/src/main/java/com/funeat/common/dto/S3UrlRequest.java
  backend/src/main/java/com/funeat/common/dto/S3UrlResponse.java
  backend/src/main/java/com/funeat/common/s3/AwsConfig.java
  backend/src/main/java/com/funeat/common/s3/S3UploadUrlGenerator.java
  backend/src/main/java/com/funeat/recipe/presentation/RecipeController.java
  backend/src/main/resources/application-dev.yml
  backend/src/main/resources/application-prod.yml
  backend/src/test/resources/application.yml
Labels: 🔒 BE, ✨ Feature

#593 [BE] style: presinged -> presigned
  backend/src/main/java/com/funeat/common/controller/PreSignedApiController.java
  backend/src/main/java/com/funeat/common/controller/PreSignedController.java
  backend/src/main/java/com/funeat/common/dto/S3UrlResponse.java
Labels: 🔒 BE, 🔧 Refactor

#586 [FE] refactor: stylelint 도입
  frontend/.stylelintrc.js
  frontend/package.json
  frontend/src/components/Common/Carousel/Carousel.tsx
  frontend/src/components/Common/Header/Header.tsx
  frontend/src/components/Common/ImageUploader/ImageUploader.tsx
  frontend/src/components/Common/Input/Input.tsx
  frontend/src/components/Common/MarkedText/MarkedText.tsx
  frontend/src/components/Common/MoreButton/MoreButton.tsx
  frontend/src/components/Common/NavigableSectionTitle/NavigableSectionTitle.tsx
  frontend/src/components/Common/NavigationBar/NavigationBar.tsx
  frontend/src/components/Common/ScrollButton/ScrollButton.tsx
  frontend/src/components/Common/SectionTitle/SectionTitle.tsx
  frontend/src/components/Common/SortButton/SortButton.tsx
  frontend/src/components/Common/SortOptionList/SortOptionList.tsx
  frontend/src/components/Common/Title/Title.tsx
  frontend/src/components/Layout/DefaultLayout.tsx
  frontend/src/components/Layout/HeaderOnlyLayout.tsx
  frontend/src/components/Layout/MinimalLayout.tsx
  frontend/src/components/Members/MembersInfo/MembersInfo.tsx
  frontend/src/components/Product/PBProductItem/PBProductItem.tsx
  frontend/src/components/Product/PBProductList/PBProductList.tsx
  frontend/src/components/Product/ProductDetailItem/ProductDetailItem.tsx
  frontend/src/components/Product/ProductItem/ProductItem.tsx
  frontend/src/components/Product/ProductOverviewItem/ProductOverviewItem.tsx
  frontend/src/components/Rank/RecipeRankingItem/RecipeRankingItem.tsx
  frontend/src/components/Rank/ReviewRankingItem/ReviewRankingItem.tsx
  frontend/src/components/Recipe/RecipeItem/RecipeItem.tsx
  frontend/src/components/Recipe/RecipeRegisterForm/RecipeRegisterForm.tsx
  frontend/src/components/Recipe/RecipeUsedProducts/RecipeUsedProducts.tsx
  frontend/src/components/Recipe/RecipeUsedProducts/SearchedProductList.tsx
  frontend/src/components/Review/ReviewItem/ReviewItem.tsx
  frontend/src/components/Review/ReviewRegisterForm/ReviewRegisterForm.tsx
  frontend/src/components/Review/ReviewTagList/ReviewTagList.tsx
  frontend/src/components/Review/ReviewTextarea/ReviewTextarea.tsx
  frontend/src/components/Review/StarRate/StarRate.tsx
  frontend/src/components/Search/RecommendList/RecommendList.tsx
  frontend/src/pages/HomePage.tsx
  frontend/src/pages/LoginPage.tsx
  frontend/src/pages/MemberModifyPage.tsx
  frontend/src/pages/ProductDetailPage.tsx
  frontend/src/pages/RecipeDetailPage.tsx
  frontend/src/pages/RecipePage.tsx
  frontend/src/pages/SearchPage.tsx
  frontend/yarn.lock
Labels: 🔑 FE, 🔧 Refactor

#592 [FE] feat: pre-signed url 요청 및 S3 이미지 업로드 추가
  frontend/package.json
  frontend/src/apis/index.ts
  frontend/src/components/Common/ImageUploader/ImageUploader.tsx
  frontend/src/components/Recipe/RecipeRegisterForm/RecipeRegisterForm.tsx
  frontend/src/components/Review/ReviewRegisterForm/ReviewRegisterForm.tsx
  frontend/src/constants/index.ts
  frontend/src/hooks/common/useImageUploader.ts
  frontend/src/hooks/common/useTimeout.ts
  frontend/src/hooks/queries/s3/index.ts
  frontend/src/hooks/queries/s3/usePresignedMutation.ts
  frontend/src/hooks/s3/index.ts
  frontend/src/hooks/s3/useS3Upload.ts
  frontend/src/pages/MemberModifyPage.tsx
  frontend/src/types/s3.ts
  frontend/src/utils/uuid.ts
  frontend/yarn.lock
Labels: 🔑 FE, ✨ Feature

#597 [BE] feat: 서버에서 s3 에 이미지 업로드 구현
  backend/src/main/java/com/funeat/common/ImageUploader.java
  backend/src/main/java/com/funeat/common/OpenApiConfig.java
  backend/src/main/java/com/funeat/common/controller/PreSignedApiController.java
  backend/src/main/java/com/funeat/common/controller/PreSignedController.java
  backend/src/main/java/com/funeat/common/dto/S3UrlRequest.java
  backend/src/main/java/com/funeat/common/dto/S3UrlResponse.java
  backend/src/main/java/com/funeat/common/exception/CommonException.java
  backend/src/main/java/com/funeat/common/s3/S3UploadUrlGenerator.java
  backend/src/main/java/com/funeat/common/s3/S3Uploader.java
  backend/src/main/java/com/funeat/exception/CommonErrorCode.java
  backend/src/main/java/com/funeat/member/application/MemberService.java
  backend/src/main/java/com/funeat/member/domain/Member.java
  backend/src/main/java/com/funeat/member/dto/MemberRequest.java
  backend/src/main/java/com/funeat/member/presentation/MemberApiController.java
  backend/src/main/java/com/funeat/member/presentation/MemberController.java
  backend/src/main/java/com/funeat/recipe/application/RecipeService.java
  backend/src/main/java/com/funeat/recipe/dto/RecipeCreateRequest.java
  backend/src/main/java/com/funeat/recipe/presentation/RecipeApiController.java
  backend/src/main/java/com/funeat/recipe/presentation/RecipeController.java
  backend/src/main/java/com/funeat/review/application/ReviewService.java
  backend/src/main/java/com/funeat/review/dto/ReviewCreateRequest.java
  backend/src/main/java/com/funeat/review/presentation/ReviewApiController.java
  backend/src/main/java/com/funeat/review/presentation/ReviewController.java
  backend/src/main/resources/application-dev.yml
  backend/src/main/resources/application-prod.yml
  backend/src/test/java/com/funeat/acceptance/member/MemberAcceptanceTest.java
  backend/src/test/java/com/funeat/acceptance/member/MemberSteps.java
  backend/src/test/java/com/funeat/acceptance/product/ProductAcceptanceTest.java
  backend/src/test/java/com/funeat/acceptance/recipe/RecipeAcceptanceTest.java
  backend/src/test/java/com/funeat/acceptance/recipe/RecipeSteps.java
  backend/src/test/java/com/funeat/acceptance/review/ReviewAcceptanceTest.java
  backend/src/test/java/com/funeat/acceptance/review/ReviewSteps.java
  backend/src/test/java/com/funeat/common/TestImageUploader.java
  backend/src/test/java/com/funeat/fixture/RecipeFixture.java
  backend/src/test/java/com/funeat/fixture/ReviewFixture.java
  backend/src/test/java/com/funeat/member/application/MemberServiceTest.java
  backend/src/test/java/com/funeat/member/application/TestMemberService.java
  backend/src/test/java/com/funeat/recipe/application/RecipeServiceTest.java
  backend/src/test/java/com/funeat/review/application/ReviewServiceTest.java
  backend/src/test/resources/application.yml
Labels: 🔒 BE, ✨ Feature

#601 [BE] hotfix: s3 path 를 file full path 로 수정
  backend/src/main/java/com/funeat/common/s3/S3Uploader.java
Labels: 🔒 BE, 🐛 Bug

#602 [BE] hotfix: s3 권한을 얻을 때 읽기 권한 추가 삭제
  backend/src/main/java/com/funeat/common/s3/S3Uploader.java
Labels: 🔒 BE, 🐛 Bug

#603 [BE] hotfix: cloudfront path 로 이미지 url 변경
  backend/src/main/java/com/funeat/common/s3/S3Uploader.java
  backend/src/main/resources/application-dev.yml
  backend/src/main/resources/application-prod.yml
  backend/src/test/resources/application.yml
Labels: 🔒 BE, 🐛 Bug

#604 [BE] hotfix: image 문자열 자르기 에러 수정
  backend/src/main/java/com/funeat/common/s3/S3Uploader.java
Labels: 🔒 BE, 🐛 Bug

#606 [FE] fix: 리뷰 이미지 예외처리 수정
  frontend/src/components/Review/ReviewItem/ReviewItem.tsx
Labels: 🔑 FE, 🐛 Bug

#614 [BE] feat: 리뷰 랭킹 조회api와 마이페이지 리뷰 조회api에서 반환값에 상품의 categoryType 추가
  backend/src/main/java/com/funeat/member/dto/MemberReviewDto.java
  backend/src/main/java/com/funeat/review/dto/RankingReviewDto.java
Labels: 🔒 BE, ✨ Feature

#617 [FE] refactor: 프로덕션 환경에서만 ga 동작하게 수정
  frontend/src/constants/index.ts
  frontend/src/hooks/common/useRouteChangeTracker.ts
  frontend/src/index.tsx
Labels: 🔑 FE, 🔧 Refactor

#630 [FE] fix: 변수명 수정
  frontend/src/components/Product/ProductTitle/ProductTitle.stories.tsx
Labels: 🔑 FE, 🐛 Bug

#621 [FE] feat: 화면 전환 시 선택된 카테고리 유지 및 스크롤 유지
  frontend/src/components/Common/CategoryMenu/CategoryMenu.tsx
  frontend/src/components/Layout/DefaultLayout.tsx
  frontend/src/components/Product/PBProductList/PBProductList.tsx
  frontend/src/components/Product/ProductList/ProductList.tsx
  frontend/src/contexts/CategoryContext.tsx
  frontend/src/hooks/common/index.ts
  frontend/src/hooks/common/useScrollRestoration.ts
  frontend/src/hooks/context/index.ts
  frontend/src/hooks/context/useCategoryActionContext.ts
  frontend/src/hooks/context/useCategoryContext.ts
  frontend/src/hooks/context/useCategoryValueContext.ts
  frontend/src/pages/HomePage.tsx
  frontend/src/pages/ProductListPage.tsx
  frontend/src/router/index.tsx
Labels: 🔑 FE, ✨ Feature

#626 [BE] API에 대한 로깅 기능 추가
  backend/src/main/java/com/funeat/common/logging/Logging.java
  backend/src/main/java/com/funeat/common/logging/LoggingAspect.java
  backend/src/main/java/com/funeat/member/presentation/MemberApiController.java
  backend/src/main/java/com/funeat/recipe/presentation/RecipeApiController.java
  backend/src/main/java/com/funeat/review/presentation/ReviewApiController.java
Labels: 🔒 BE, ✨ Feature

#623 [FE] fix: 리뷰 작성 시 리뷰 탭 이동 및 유지
  frontend/__tests__/hooks/useTabMenu.test.ts
  frontend/src/components/Common/TabMenu/TabMenu.tsx
  frontend/src/components/Review/ReviewRegisterForm/ReviewRegisterForm.tsx
  frontend/src/hooks/common/index.ts
  frontend/src/hooks/common/useTabMenu.ts
  frontend/src/pages/IntegratedSearchPage.tsx
  frontend/src/pages/ProductDetailPage.tsx
  frontend/src/pages/SearchPage.tsx
Labels: 🔑 FE, 🐛 Bug

#632 [BE] refactor: 코드 포맷 적용, 컨벤션 적용
  backend/src/main/java/com/funeat/FuneatApplication.java
  backend/src/main/java/com/funeat/auth/presentation/AuthController.java
  backend/src/main/java/com/funeat/auth/util/KakaoPlatformUserProvider.java
  backend/src/main/java/com/funeat/common/CustomPageableHandlerMethodArgumentResolver.java
  backend/src/main/java/com/funeat/common/WebConfig.java
  backend/src/main/java/com/funeat/common/s3/S3Uploader.java
  backend/src/main/java/com/funeat/exception/presentation/GlobalControllerAdvice.java
  backend/src/main/java/com/funeat/member/dto/MemberRecipeDto.java
  backend/src/main/java/com/funeat/member/dto/MemberReviewDto.java
  backend/src/main/java/com/funeat/member/presentation/MemberApiController.java
  backend/src/main/java/com/funeat/member/presentation/MemberController.java
  backend/src/main/java/com/funeat/product/application/ProductService.java
  backend/src/main/java/com/funeat/product/domain/Product.java
  backend/src/main/java/com/funeat/product/persistence/ProductRepository.java
  backend/src/main/java/com/funeat/product/presentation/ProductApiController.java
  backend/src/main/java/com/funeat/product/presentation/ProductController.java
  backend/src/main/java/com/funeat/recipe/dto/RankingRecipeDto.java
  backend/src/main/java/com/funeat/recipe/presentation/RecipeController.java
  backend/src/main/java/com/funeat/recipe/util/RecipeHandlerInterceptor.java
  backend/src/main/java/com/funeat/review/application/ReviewService.java
  backend/src/main/java/com/funeat/review/domain/Review.java
  backend/src/main/java/com/funeat/review/domain/ReviewTag.java
  backend/src/main/java/com/funeat/review/dto/RankingReviewDto.java
  backend/src/main/java/com/funeat/review/presentation/ReviewApiController.java
  backend/src/main/java/com/funeat/review/presentation/ReviewController.java
  backend/src/main/resources/application-local.yml
  backend/src/test/java/com/funeat/FuneatApplicationTests.java
  backend/src/test/java/com/funeat/acceptance/member/MemberSteps.java
  backend/src/test/java/com/funeat/acceptance/review/ReviewSteps.java
  backend/src/test/java/com/funeat/recipe/persistence/RecipeRepositoryTest.java
Labels: 🔒 BE, 🔧 Refactor

#628 [FE] refactor: 홈 화면 변경
  frontend/src/components/Common/Carousel/Carousel.tsx
  frontend/src/components/Common/CategoryItem/CategoryItem.stories.tsx
  frontend/src/components/Common/CategoryItem/CategoryItem.tsx
  frontend/src/components/Common/CategoryList/CategoryList.stories.tsx
  frontend/src/components/Common/CategoryList/CategoryList.tsx
  frontend/src/components/Common/CategoryTab/CategoryTab.stories.tsx
  frontend/src/components/Common/CategoryTab/CategoryTab.tsx
  frontend/src/components/Common/index.ts
  frontend/src/components/Product/PBProductList/PBProductList.tsx
  frontend/src/components/Product/ProductList/ProductList.tsx
  frontend/src/components/Rank/RecipeRankingItem/RecipeRankingItem.tsx
  frontend/src/constants/index.ts
  frontend/src/mocks/data/foodCategory.json
  frontend/src/mocks/data/storeCategory.json
  frontend/src/pages/HomePage.tsx
  frontend/src/pages/ProductListPage.tsx
Labels: 🔑 FE, 🔧 Refactor

#638 [BE] feat: 카테고리 이미지 추가
  backend/src/main/java/com/funeat/product/domain/Category.java
  backend/src/main/java/com/funeat/product/dto/CategoryResponse.java
  backend/src/test/java/com/funeat/fixture/CategoryFixture.java
  backend/src/test/java/com/funeat/recipe/application/RecipeServiceTest.java
Labels: 🔒 BE, ✨ Feature

#637 [FE] refactor: 카테고리 로직 수정
  frontend/src/components/Common/CategoryList/CategoryList.tsx
  frontend/src/constants/index.ts
  frontend/src/mocks/data/foodCategory.json
  frontend/src/mocks/data/storeCategory.json
  frontend/src/pages/HomePage.tsx
  frontend/src/types/common.ts
Labels: 🔑 FE, 🔧 Refactor

#640 [FE] refactor: 레이아웃 스타일 수정
  frontend/src/components/Common/Carousel/Carousel.tsx
  frontend/src/components/Common/CategoryItem/CategoryItem.tsx
  frontend/src/components/Layout/DefaultLayout.tsx
  frontend/src/components/Layout/SimpleHeaderLayout.tsx
  frontend/src/pages/HomePage.tsx
  frontend/src/pages/MemberPage.tsx
  frontend/src/pages/MemberRecipePage.tsx
  frontend/src/pages/MemberReviewPage.tsx
  frontend/src/pages/RecipeDetailPage.tsx
Labels: 🔑 FE, 🎨 UI

#639 [FE] refactor: scrollTop에서 ref로 접근하는 방식으로 변경
  frontend/src/components/Common/ScrollButton/ScrollButton.tsx
  frontend/src/components/Product/ProductList/ProductList.tsx
  frontend/src/contexts/CategoryContext.tsx
  frontend/src/hooks/common/useScroll.ts
  frontend/src/pages/HomePage.tsx
  frontend/src/pages/MemberRecipePage.tsx
  frontend/src/pages/MemberReviewPage.tsx
  frontend/src/pages/ProductDetailPage.tsx
  frontend/src/pages/ProductListPage.tsx
  frontend/src/pages/RecipePage.tsx
Labels: 🔑 FE, 🔧 Refactor

#644 [FE] fix: 리뷰, 꿀조합 작성 함수 디바운스 적용
  frontend/src/components/Recipe/RecipeRegisterForm/RecipeRegisterForm.tsx
  frontend/src/components/Review/ReviewRegisterForm/ReviewRegisterForm.tsx
Labels: 🔑 FE, 🐛 Bug

#646 [FE] refactor: 리뷰 태그 리스트 스타일 수정
  frontend/src/components/Review/ReviewTagList/ReviewTagList.tsx
Labels: 🔑 FE, 🎨 UI

#647 [FE] refactor: 자잘한 디자인 수정 및 배너 링크 연결
  frontend/src/components/Product/ProductItem/ProductItem.tsx
  frontend/src/pages/HomePage.tsx
  frontend/src/pages/ProductListPage.tsx
Labels: 🔑 FE, 🔧 Refactor

#649 [FE] fix: 리뷰, 꿀조합 전송 에러 수정
  frontend/src/components/Recipe/RecipeRegisterForm/RecipeRegisterForm.tsx
  frontend/src/components/Review/ReviewRegisterForm/ReviewRegisterForm.tsx
Labels: 🔑 FE, 🐛 Bug

#616 [BE] Product 엔티티에 reviewCount 필드 추가
  backend/src/main/java/com/funeat/product/domain/Product.java
  backend/src/main/java/com/funeat/review/application/ReviewService.java
Labels: 🔒 BE, ✨ Feature

#660 [FE] fix: 갤럭시에서 무한스크롤 안되는 문제 해결
  frontend/src/components/Product/ProductTitle/ProductTitle.tsx
  frontend/src/hooks/common/useIntersectionObserver.ts
  frontend/src/pages/RecipePage.tsx
Labels: 🔑 FE, 🐛 Bug

#661 [BE] refactor: Product의 reviewCount 자료형을 Long으로 변경
  backend/src/main/java/com/funeat/product/domain/Product.java
Labels: 🔒 BE, 🐛 Bug, 🔧 Refactor

#657 [BE] fix: LocalDateTime이 들어간 Response도 로깅할 수 있도록 설정
  backend/src/main/java/com/funeat/common/logging/LoggingAspect.java
Labels: 🔒 BE, 🐛 Bug

#665 [BE] fix: 테스트 컨텍스트가 초기화될 때, 새로운 테스트 환경에서 테스트하도록 설정
  backend/src/test/resources/application.yml
Labels: 🔒 BE, 🐛 Bug

#667 [BE] fix: 이미지가 없는 리뷰는 상품 이미지 변경 대상에 제외
  backend/src/main/java/com/funeat/review/persistence/ReviewRepository.java
  backend/src/test/java/com/funeat/fixture/ReviewFixture.java
  backend/src/test/java/com/funeat/review/application/ReviewServiceTest.java
Labels: 🔒 BE, 🐛 Bug

#653 [BE] refactor: 인수 테스트 리팩터링
  backend/src/test/java/com/funeat/acceptance/auth/AuthAcceptanceTest.java
  backend/src/test/java/com/funeat/acceptance/auth/LoginSteps.java
  backend/src/test/java/com/funeat/acceptance/common/AcceptanceTest.java
  backend/src/test/java/com/funeat/acceptance/common/CommonSteps.java
  backend/src/test/java/com/funeat/acceptance/common/TestPlatformUserProvider.java
  backend/src/test/java/com/funeat/acceptance/member/MemberAcceptanceTest.java
  backend/src/test/java/com/funeat/acceptance/member/MemberSteps.java
  backend/src/test/java/com/funeat/acceptance/product/CategoryAcceptanceTest.java
  backend/src/test/java/com/funeat/acceptance/product/ProductAcceptanceTest.java
  backend/src/test/java/com/funeat/acceptance/product/ProductSteps.java
  backend/src/test/java/com/funeat/acceptance/recipe/RecipeAcceptanceTest.java
  backend/src/test/java/com/funeat/acceptance/recipe/RecipeSteps.java
  backend/src/test/java/com/funeat/acceptance/review/ReviewAcceptanceTest.java
  backend/src/test/java/com/funeat/acceptance/review/ReviewSteps.java
  backend/src/test/java/com/funeat/acceptance/tag/TagAcceptanceTest.java
  backend/src/test/java/com/funeat/auth/application/AuthServiceTest.java
  backend/src/test/java/com/funeat/fixture/CategoryFixture.java
  backend/src/test/java/com/funeat/fixture/ImageFixture.java
  backend/src/test/java/com/funeat/fixture/MemberFixture.java
  backend/src/test/java/com/funeat/fixture/PageFixture.java
  backend/src/test/java/com/funeat/fixture/ProductFixture.java
  backend/src/test/java/com/funeat/fixture/RecipeFixture.java
  backend/src/test/java/com/funeat/fixture/ReviewFixture.java
  backend/src/test/java/com/funeat/fixture/ScoreFixture.java
  backend/src/test/java/com/funeat/member/application/MemberServiceTest.java
  backend/src/test/java/com/funeat/member/domain/MemberTest.java
  backend/src/test/java/com/funeat/member/domain/favorite/RecipeFavoriteTest.java
  backend/src/test/java/com/funeat/member/persistence/RecipeFavoriteRepositoryTest.java
  backend/src/test/java/com/funeat/product/domain/ProductTest.java
  backend/src/test/java/com/funeat/product/persistence/ProductRepositoryTest.java
  backend/src/test/java/com/funeat/recipe/application/RecipeServiceTest.java
  backend/src/test/java/com/funeat/recipe/persistence/RecipeRepositoryTest.java
  backend/src/test/java/com/funeat/review/application/ReviewServiceTest.java
  backend/src/test/java/com/funeat/review/persistence/ReviewRepositoryTest.java
Labels: 🔒 BE, 🔧 Refactor, 💻 Test

#668 [ALL] Github Actions workflows 버전 관리
  .github/workflows/test-fe.yml
  .github/workflows/test.yml
Labels: 🔒 BE, 🔑 FE, 🌎 Infra

#590 [FE] feat: 로딩 스피너 추가
  frontend/src/components/Common/Loading/Loading.tsx
Labels: 🔑 FE, ✨ Feature

#675 [FE] fix: 좋아요 요청 시 상품 리뷰와 꿀조합 상세 쿼리 무효화
  frontend/src/hooks/queries/recipe/useRecipeFavoriteMutation.ts
  frontend/src/hooks/queries/review/useReviewFavoriteMutation.ts
Labels: 🔑 FE, 🐛 Bug

#676 [FE] fix: 검색 결과 두 번 요청 수정
  frontend/src/hooks/search/useSearch.ts
  frontend/src/pages/IntegratedSearchPage.tsx
  frontend/src/pages/SearchPage.tsx
Labels: 🔑 FE, 🐛 Bug

#672 [FE] feat: 폰트 추가
  frontend/public/index.html
  frontend/src/styles/font.ts
  frontend/src/styles/index.ts
Labels: 🔑 FE, ✨ Feature

#681 [FE] feat: lazy 적용
  frontend/src/index.tsx
  frontend/src/pages/AuthPage.tsx
  frontend/src/pages/HomePage.tsx
  frontend/src/pages/IntegratedSearchPage.tsx
  frontend/src/pages/LoginPage.tsx
  frontend/src/pages/MemberModifyPage.tsx
  frontend/src/pages/MemberPage.tsx
  frontend/src/pages/MemberRecipePage.tsx
  frontend/src/pages/MemberReviewPage.tsx
  frontend/src/pages/ProductDetailPage.tsx
  frontend/src/pages/ProductListPage.tsx
  frontend/src/pages/RecipeDetailPage.tsx
  frontend/src/pages/RecipePage.tsx
  frontend/src/pages/SearchPage.tsx
  frontend/src/router/index.tsx
  frontend/tsconfig.json
  frontend/webpack.common.js
  frontend/webpack.prod.js
Labels: 🔑 FE, ✨ Feature

#690 [FE] fix: webpack-bundle-analyzer 설치
  frontend/package.json
  frontend/yarn.lock
Labels: 🔑 FE, 🐛 Bug

#692 [FE] fix: webpack-bundle-analyzer 삭제
  frontend/package.json
  frontend/webpack.common.js
  frontend/yarn.lock
Labels: 🔑 FE, 🐛 Bug

#695 [BE] feat: application.yml에 톰캣 스레드 설정 항목 추가
  backend/src/main/resources/application.yml
Labels: 🔒 BE, ✨ Feature, 🌎 Infra

#684 [FE] feat: Skeleton UI 추가
  frontend/src/components/Common/MoreButton/MoreButton.stories.tsx
  frontend/src/components/Common/MoreButton/MoreButton.tsx
  frontend/src/components/Common/Skeleton/Skeleton.stories.tsx
  frontend/src/components/Common/Skeleton/Skeleton.tsx
  frontend/src/components/Common/index.ts
  frontend/src/components/Members/MembersInfo/MembersInfo.tsx
  frontend/src/components/Product/PBProductItem/PBProductItem.stories.tsx
  frontend/src/components/Product/PBProductItem/PBProductItem.tsx
  frontend/src/components/Product/PBProductList/PBProductList.stories.tsx
  frontend/src/components/Product/PBProductList/PBProductList.tsx
  frontend/src/components/Product/ProductItem/ProductItem.tsx
  frontend/src/components/Product/index.ts
  frontend/src/components/Rank/RecipeRankingItem/RecipeRankingItem.tsx
  frontend/src/components/Recipe/RecipeItem/RecipeItem.tsx
  frontend/src/components/Review/ReviewItem/ReviewItem.tsx
  frontend/src/pages/HomePage.tsx
Labels: 🔑 FE, ✨ Feature

#693 [FE] feat: 꿀조합 페이지 디자인 수정
  frontend/src/pages/RecipePage.tsx
Labels: 🔑 FE, 🔧 Refactor

#701 [FE] refactor: 폰트 가변 다이나믹으로 변경과 상품 랭킹 말줄임표
  frontend/public/index.html
  frontend/src/components/Product/ProductOverviewItem/ProductOverviewItem.tsx
  frontend/src/mocks/data/productRankingList.json
Labels: 🔑 FE, 🔧 Refactor

#703 [FE] chore: 디자인 시스템 버전 업
  frontend/package.json
  frontend/yarn.lock
Labels: 🔑 FE, 🔧 Refactor

#700 [FE] fix: 상품 목록 페이지에서 스크롤이 2개 생기는 버그 해결
  frontend/src/components/Product/ProductItem/ProductItem.tsx
  frontend/src/components/Recipe/RecipeItem/RecipeItem.tsx
Labels: 🔑 FE, 🐛 Bug

#705 [FE] refactor: 상품, 꿀조합, 리뷰 아이템 메모이제이션
  frontend/src/components/Product/ProductItem/ProductItem.tsx
  frontend/src/components/Rank/ReviewRankingItem/ReviewRankingItem.tsx
  frontend/src/components/Recipe/RecipeItem/RecipeItem.tsx
  frontend/src/components/Review/ReviewItem/ReviewItem.tsx
Labels: 🔑 FE, 🔧 Refactor

#709 [FE] feat: 이벤트 링크 변경
  frontend/src/pages/HomePage.tsx
Labels: 🔑 FE
